### ISSUE TITLE
id_rsa-key already exists - how to create a new one for Github

### ISSUE THREAD

**Issue by nekoCC01** [susanBuck/dwa15-fall2017#10]
Hi everyone!
I just wanted to share some experiences with my SSH-key-creation and ask, if anyone had similar problems and found a better solution.

I **already had an id_rsa-key in my .ssh/folder**, which I use for work, so **created a new one with a new name for my Github access**.

But Github seems to be configured to look for the standard "id_rsa" file, so it didn´t work at the beginning. But after **adding the new SSH key to the ssh-agent** (as described in the [second section under this link](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)), the connection worked.
This included writing a **config-file** within the .ssh-folder, with the following content:
```
Host github.com
 HostName github.com
 AddKeysToAgent yes
 UseKeychain yes
 IdentityFile ~/.ssh/[name-of-my-key]
 User git
```
But although the key should be added automatically, I have to enter the following command each time manually:
```bash
sudo ssh-add -K ~/.ssh/[name-of-my-key]
```

I wrote an alias for this, but still I guess there is a better solution to the whole problem.
Did anyone had a similar issue, or can tell an easier way to deal with a different key?
 
Thanks,
Daniel

**Comment by susanBuck** [comment]
Daniel do you have to run the ssh-add command before any attempts to connect with Github, or just after you've restarted Terminal?

Also, what operating system version are you running?

**Comment by HeinrichTremblay** [comment]
I was confronted with the same issue, I already had an **id_rsa** key in my `.ssh` folder from previous projects. I went with a _**Keep It Simple Stupid**_ solution: simply skipped the step to generate a new key and reuse the key I already had. 

Although i'm not quite sure what is the best practise in this case.

**Comment by nekoCC01** [comment]
I only have to run the ssh-add command, when I open the Terminal for the first time (and after reboot). I´m working with macOS Sierra 10.12.6.

I also wanted to just use my existing id_rsa key, but I don´t have the corresponding public key (that one is placed on the server of the company I´m working for.)

**Comment by HeinrichTremblay** [comment]
@nekoCC01 I found this step by step [tutorial](https://coderwall.com/p/7smjkq/multiple-ssh-keys-for-different-accounts-on-github-or-gitlab) that is well explained. Let me know if it solve or not your problem.

**Comment by nekoCC01** [comment]
@HeinrichTremblay  Thanks a lot, that was helpful. The problem is now resolved.
