### ISSUE TITLE
(dev env) running composer update after configuring composer.json for cebe/markdown updates all packages

### ISSUE THREAD

**Issue by dlabelle101** [susanBuck/dwa15-fall2017#100]
it appears all of my packages where updated, and the cebe/markdown package was installed....did anyone else have this happen?

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 18 updates, 0 removals
  - Updating symfony/css-selector (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/polyfill-mbstring (v1.5.0 => v1.6.0): Downloading (100%)
  - Updating symfony/var-dumper (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/routing (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/process (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/http-foundation (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/event-dispatcher (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/debug (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/http-kernel (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/finder (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating symfony/console (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating swiftmailer/swiftmailer (v6.0.1 => v6.0.2): Downloading (100%)
  - Updating symfony/translation (v3.3.9 => v3.3.10): Downloading (100%)
  - Updating laravel/framework (v5.5.13 => v5.5.18): Downloading (100%)
  - Updating filp/whoops (2.1.10 => 2.1.12): Downloading (100%)
  - Updating myclabs/deep-copy (1.6.1 => 1.7.0): Downloading (100%)
  - Updating phpunit/phpunit (6.3.1 => 6.4.3): Downloading (100%)
  - Updating psy/psysh (v0.8.11 => v0.8.13): Downloading (100%)
  - Installing cebe/markdown (1.1.2): Downloading (100%)

**Comment by zeroender** [comment]
I believe this is due to using composer update, rather than install (I'm assuming this is your production environment, where you wouldn't want cebe/markdown).  Install won't install the dev components unless specified, but update will install everything in your composer.json, including the dev stuff (https://adamcod.es/2013/03/07/composer-install-vs-composer-update.html)

**Comment by dlabelle101** [comment]
i changed to the title to clarify, this is in the dev environment on a windows 10 PC.

**Comment by susanBuck** [comment]
Any time you run `composer update` it will do a check to see what needs updating. 

This may include new packages you've just added, and also updates to existing packages (if the developers of those packages released updates).

Looking at the output, you can see that each of the listed packages had a small version jump, for example:

```
Updating symfony/css-selector (v3.3.9 => v3.3.10): Downloading (100%)
```
If we look at [the version history](https://github.com/symfony/css-selector/releases) for `symfony/css-selector` you can see that `v3.3.10` was released 15 days ago, and so when you ran `composer update` it picked up on this change and updated the package for you.

The require statement for this particular package (from`/vendor/laravel/framework/composer.json`) looks like this:
```
"symfony/css-selector": "~3.3",
```

That tilde character indicates that we're interested in having any version of this package >= 3.3 but less than 4. Composer will abide by this when we run `composer update`.

Ref:
+ [Version constraints](https://getcomposer.org/doc/articles/versions.md#writing-version-constraints)
+ [Tilde version range](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-)
