### ISSUE TITLE
Views and Index.php

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#101]
So, thanks to routes, view and controllers, we are able to control what's displayed to the user when they enter a route in our url. Is it possible to use this (routes, controllers, and views), to change the content on our main page? Lets say  my url is www.test.com, can I create a route, controller, view, that will allow me to manage what is displayed on this screen? Hence, is there a way to force larvel to not use the index.php file in the public directory?

**Comment by susanBuck** [comment]
The homepage/main page is dictated by the `/` route URL:

```php
/**
* Homepage
*/
Route::get('/', 'WelcomeController');
```

The WelcomeController (or any controller you wish) can then load the appropriate view.

It's unclear to me why we'd want to bypass Laravel using the index.php file in the public directory - it's the crux of how the system starts up. Let me know if I'm misinterpreting your question. : )

**Comment by APuente21** [comment]
My project 3 page is currently set up in a path that is different from that home directory - my index.php has the standard Larval welcome message. As such, I wanted to add a route and controller that would return the view related to my project. 

As for the route, I tried creating the route, with the appropriate controller and view, and it dosn't work. It defaults to the Larvel file.
Route::get('/', 'TipController@index');

**Comment by ruthnphillips** [comment]
Maybe post your Git repo URL, so we can better assist

**Comment by gregorycoleman** [comment]
I am looking at this repo <https://github.com/APuente21/TipCalculator_Larvel> , that code hasn't been updated in 8 days, so if you could push your current version, we can have a better idea of whats going on.
