### ISSUE TITLE
Keep value after Submit

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#103]
So far we retain the values during validation fail using ("old" wording).
```<input type='text' name='title' id='title' value='{{ old('title') }}'>```

Let's say I have only one page and I post answers to the same page. However, I want to retain/keep the values **after** passing validation and submit.

**Comment by susanBuck** [comment]
We see an example of this with the Foobooks search feature -

A view is returned and we're making data available to that view, including data from the request (`searchTerm` and `caseSensitive`):

```php
$searchTerm = $request->input('searchTerm', null);

# [...]

# Return the view, with the searchTerm *and* searchResults (if any)
return view('book.search')->with([
    'searchTerm' => $searchTerm,
    'caseSensitive' => $request->has('caseSensitive'),
    'searchResults' => $searchResults
]);
```

Alternatively, you could make all the request data available:
```php
return view('example')->with([
    'request' => $request->input();
]
```

**Comment by dianakleban** [comment]
I am not sure I am clear on this one. I am doing post redirecting to this create method (the same way you showed in the lecture) that returns the view with these sessions, however, the values are not kept after I submit.
public function create(Request $request)
    {
      return view('student.index')->with([
        'name'=>session('name'),
        'email'=>session('email'),
        'comments'=>session('comments'),
        'lang'=>session('lang')
      ]);
    }

**Comment by zeroender** [comment]
It looks like you are passing the view a reference to the values from the session, rather than the values from the request object.  If you've defined a variable session as $response->all() then this might work (but be potentially confusing), but I believe you can substitute $response for session here such, eg:

```
public function create(Request $request)
{
  return view('student.index')->with([
  'name'=>$response->input('name'),
  'email'=>$response->input('email'),
  'comments'=>$response->input('comments'),
  'lang'=>$response->input('lang')
]);
}
```

Also, this will allow the input to be accessed in the other view - you'd still need to conditionally populate the fields with that information.

HTH!

**Comment by dianakleban** [comment]
This is the **POST** example similar to what was discussed in the lecture. Store function redirect values to create. Create needs to catch **sessions** and pass to the view. However, when it is completed, all fields are blank, the same way it was in the lecture. I was wondering if they can retain values when POST is done and sessions used.

**Comment by susanBuck** [comment]
To keep values from a form after a __redirect__ you can use the `withInput` method on the redirect.

Example:
```php
return redirect('/book/create')->with([
    'title' => $title
])->withInput();
```

Reference: [HTTP Requests -> Old Input](https://laravel.com/docs/5.5/requests#old-input)

If I amend the Foobooks `BookController` `store` method to have a redirect like above, then the values will be retained in the *Add a book* form after the user is redirected back to that page.

Assuming, of course, your inputs are attempting to prefill with `old`:

```html
<input type='text' name='title' id='title' value='{{ old('title') }}'>
```

In action:
![search](https://user-images.githubusercontent.com/237711/31958403-a5c74faa-b8bf-11e7-8def-46e0e9bdce25.gif)

**Comment by dianakleban** [comment]
Yes, it works great and such an each change to implement. Thank you very much.

Also, just wondering, is it better to retain the values or clear them in the case of Add book example. In my case it is a contact us form that posts back to itself with the message.

**Comment by susanBuck** [comment]
In the case of a contact form, I don't think it makes sense to retain the values - unless you want users sending you repeat messages. : ) 

In fact, it might not even make sense to redirect to the contact form at all, but instead to a confirmation page. Presumably, they should not to re-contact you again immediately.
