### ISSUE TITLE
Alpha Validation

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#104]
Let's say you have One field - Name and you want it to be **alpha** characters only. But you can also expect that some people can enter first and and last name separated by space like this "First Last". When we used form validation in the past, "alpha" validation got rid of space in between and then validated. But here in Laravel we are using built in validation, that does not accept any spaces or get rid of them during the process. I tried customizing, but it did not work for me. Are there any suggestions?

**Comment by susanBuck** [comment]
## Option 1
[Validate using a regular expression](https://laravel.com/docs/5.5/validation#rule-regex) as your rule.

Example:
```php
$this->validate($request, [
    'name' => 'regex:/^[\pL\s\-]+$/u'
]);
```

(regular expression taken from this Stackoverflow post: [validation rule alpha cannot take whitespace](https://stackoverflow.com/questions/34099777/laravel-5-1-validation-rule-alpha-cannot-take-whitespace))


## Option 2
Create a custom validation rule: <https://laravel.com/docs/5.5/validation#custom-validation-rules>

Sounds like this is the approach you attempted but it didn't work?

For reference, I created an example in Foobooks: <http://foobooks.dwa15.me/practice/6>

Relevant files:
+ [foobooks/blob/master/app/Rules/AlphaAndSpaces.php](https://github.com/susanBuck/foobooks/blob/master/app/Rules/AlphaAndSpaces.php)
+ [app/Http/Controllers/PracticeController.php#L17](https://github.com/susanBuck/foobooks/blob/e2b784bfce0e6b2389be8b59fea04b40c95481c7/app/Http/Controllers/PracticeController.php#L17)
+ [/views/practice/6.blade.php](https://github.com/susanBuck/foobooks/blob/master/resources/views/practice/6.blade.php)

If you'd like help troubleshooting why your custom validation rule attempts didn't work, you can post your repo for the relevant code and we can help debug.

**Comment by dianakleban** [comment]
I used option 1 and it worked for me. Thank you. This issue can be closed.
