### ISSUE TITLE
POST Structure Routes Naming Conventions

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#105]
@susanBuck Let's say I have only one page and I want to POST it back to the same page. In the class, you provided these route examples, which make sense.  
**```Route::get('/book/create', 'BookController@create'); ```
``` Route::post('/book', 'BookController@store'); ```**

However, we are supposed to use http://p3.myName.me as a main display page. It means that you need to see the form right when you login ('/') and post back to the same form (main root ('/')). Does it mean, that we need to change the routes to these? But then we are changing naming conventions for the routes?
**``` Route::get('/', 'BookController@create'); ```
``` Route::post('/book', 'BookController@store'); ```**

**Comment by susanBuck** [comment]
It's okay to break the REST naming conventions I discussed in lecture for the scenario you're describing.  In P3 you're not actually doing CRUD operations so there's no reason you need to aim for the REST naming conventions.

The [Add a book](http://foobooks.dwa15.me/book/create) feature touches on a lot of skills we need for P3 (and eventually P4), but it's not an exact model of what you're doing in P3. [Trivia](http://foobooks.dwa15.me/trivia) and [Search](http://foobooks.dwa15.me/search) have a closer parallel to what you're creating for P3.
