### ISSUE TITLE
Tip: How to Use session in Laravel

### ISSUE THREAD

**Issue by Diegometro1** [susanBuck/dwa15-fall2017#106]
Sessions are used to store information about the user across the requests. Laravel provides various drivers like file, cookie, apc, array, Memcached, Redis, and database to handle session data. By default, file driver is used because it is lightweight. Session can be configured in the file stored at config/session.php.
_# **more information click on the link**_
[Session](https://learninglaravel.net/how-to-use-session-in-laravell)

**Comment by dukesnuz** [comment]
@Diegometro1 Good link.

**Comment by susanBuck** [comment]
As of this writing, when I follow that link, it fails to load the article and instead redirects me to the the blog's homepage (<https://learninglaravel.net/blog>)

Perhaps you have to have purchased the e-book to see?

**Comment by Diegometro1** [comment]
No , i didn't purchase the e-book
This is the link
[How to use session in laravel
](https://learninglaravel.net/how-to-use-session-in-laravel)

**Comment by susanBuck** [comment]
Ah got it. The first URL had an extra `l` at the end.
