### ISSUE TITLE
Syntax error using Blade control-structure

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#108]
In my html form, the below code (based on lecture [notes](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/19_Forms_GET.md)) works:
`{{ ($shipType === 'ground') ? 'CHECKED' : '' }}`

However, when I use blade control-structure
(from https://laravel.com/docs/5.5/blade#control-structures)
`{{ @if ($shipType === 'ground') 'CHECKED' @endif }}`

I get error:
`Parse error: syntax error, unexpected '<' `

Html code:
`<input type="radio" name="shipType" required id="ground" value="ground" {{ @if ($shipType === 'ground') 'CHECKED' @endif }} />`

is translated to

`<input type="radio" name="shipType" required id="ground" value="ground" <?php echo e(<?php if($shipType === 'ground'): ?> 'CHECKED' <?php endif; ?>); ?> />`

Why?

**Comment by ALiborio** [comment]
From my understanding, the blade syntax acts similar to a macro/alias, where it just replaces the blade syntax with the php tags/code.

So `{{ }}` would create `<?php echo e(); ?>` and `@if ()` would create `<?php if(): ?>` and `@endif` would create `<?php endif; ?>`.

So when you put the `@if` and `@endif` inside of the `{{ }}` it's inserting those additional `<?php` tags into the `e()` function, which results in the syntax error. It simply replaces the blade syntax with php tags and code that they translate to.

`@if ($shipType === 'ground') CHECKED @endif` would accomplish what you are trying to do without the syntax error. It translates to `<?php if($shipType === 'ground'): ?> CHECKED <?php endif; ?>`

**Comment by HeinrichTremblay** [comment]
I think the `@if @endif` statement should be keep outside the `{{ }}` syntax.

**Comment by luke777gu** [comment]
I agree that `@if` and `@endif` need to be outside of `{{ }}`.

**Comment by ysrinu** [comment]
Thanks all!
