### ISSUE TITLE
Can't login at the moment

### ISSUE THREAD

**Issue by stbenjam** [susanBuck/dwa15-fall2017#11]
Hi,

I'm trying to login to view this week's lectures, but at https://dwa15.com/login I get a message "There was a problem processing your request."  

I've logged in before and connected my GitHub account, seems something is wrong with the callback after GitHub authenticates.

**Comment by gabrielsanna** [comment]
Can confirm that I'm seeing the same error. There's also a link back to http://localhost/, which seems weird.

**Comment by dianakleban** [comment]
I am having the same issue when I am try to click on Week 2 link. It is something about Github connection from dwa15.com site since if I go directly to Github, it is fine.

**Comment by susanBuck** [comment]
Checking on this now.

**Comment by susanBuck** [comment]
It should be resolved now. Inadvertently reverted a github-related config while doing some upgrades.
