### ISSUE TITLE
Naming Other Controllers and Views

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#110]
Say we have other child templates. ie Welcome/home, about, contact or register pages. Would it be best practice to have a controller and view folder named maybe utilities?

**Comment by susanBuck** [comment]
Sure - creating a designated controller for simple "static" pages like welcome, about, contact, etc. is a good idea. You can call it whatever you want... `UtilitiesController`, `StaticController`, `PageController`, `MiscController`, etc.

I would not include a registration page under this category, though, as that'll be a little more involved than a static page and should instead be categorized under a UserController (we'll cover this in a few weeks).

**Comment by dukesnuz** [comment]
**__Cool !__**
