### ISSUE TITLE
Keep old values on validation pass

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#111]
@susanBuck 
We have seen that 'old' syntax is useful to retain values if the validation fails.
However, 'old' makes the input fields to be cleared if validation passes.
And in https://github.com/susanBuck/dwa15-fall2017/issues/103
https://laravel.com/docs/5.5/requests#old-input
you suggested using 'withInput'.

However, 'withInput' works with 'redirect' command but not on 'return view command'.
If I call
```
        return view('cost.index')->with([
        'custName' => $custName
    ])->withInput();
```
I get 'undefined offset:0' error from the framework view.php at the line:
`return $this->with(Str::camel(substr($method, 4)), $parameters[0]);`

My use case is, I am using GET, submit and route to self (I know this is a bad idea!), I want to be able to retain old values if validation fails by using 'old' syntax, but also retain when validation passes?

If tried replacing 'return view' with 'redirect':
```
        return redirect('/cost')->with([
        'custName' => $custName
    ])->withInput();
    }
```
and it goes into endless loop!

**Comment by zeroender** [comment]
If I understand correctly, your application uses GET for both routes, which have the same URI?  I believe that would cause an endless loop - you would either need to change the form action and second route to a POST (and add CSRF protection) or use different URI.  Otherwise whenever you submit your form it is redirecting to an exact copy of itself - it will always hit the first route that matches the URI and action (GET) and never get to the second route.

**Comment by ysrinu** [comment]
@zeroender , route: /cost calls controller that returns view that has form with GET action submit to /cost.
In other words, the form submits to itself. I want to show the user the same form on submission if any previous entered as pre-filled now.

**Comment by susanBuck** [comment]
@ysrinu I just made a new post (#112) which I think also addresses this question. Can you take a look and let us know?

**Comment by ysrinu** [comment]
@susanBuck  Thank you, I will try it out (not tonight!) and let the class know.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
