### ISSUE TITLE
Laravel books: recommendations?

### ISSUE THREAD

**Issue by peggyo** [susanBuck/dwa15-fall2017#113]
I would like to know whether any classmates have purchased either of the online Laravel books listed in the Readings section. If so, which one(s), and do you think they have been valuable for your projects beyond the Laravel documentation? Any additional information or comments that we may find useful if considering buying them? Thank you!

**Comment by gregorycoleman** [comment]
Try <http://proquest.safaribooksonline.com.ezp-prod1.hul.harvard.edu/> and login with your pin. Search for `Laravel` and there are a few books. I like the Laravel cookbook.

**Comment by SridharSubramaniam** [comment]
While books are great, may not be a great idea for programming frameworks(specifically the open source ones) They tend to change a lot and in very short release cycles. 

I generally recommend books for general programming concepts like design patterns, best practices etc and stick to GitHub and official documentation for specific frameworks.

**Comment by zeroender** [comment]
I've read through 3 of the 4 books recommended in the readings section.  The two books by Dayle Rees I found pretty useful.  His PHP book is a good read to get the basics, the Laravel book is very in depth.  I actually wish I'd read Easy Laravel first, I think it is a quicker primer.  However, they're all only okay if you read without doing the exercises.

I was also taking a udemy PHP class upon start of this term, which I've paused (https://www.udemy.com/learn-php-programming-from-scratch/).  A lot of it at this point we've covered in this class.  Some of it is also a bit out of date - I'd only recommend for someone who really wanted to be in depth with PHP specifically, the Laravel stuff is on Laravel 4.

**Comment by luke777gu** [comment]
I read the book by Dayle Rees as well. It provided a lot of examples which we might face when we do our project.

**Comment by dmbartles** [comment]
Hey, I've been surfing Github for how other people are using Lavarel and PHP. I go to the search bar, pick a random topic, filter on PHP and sort by most stars. Then, I'll dig in to see how they are structuring things. I learn more from doing and examples tan books.

**Comment by peggyo** [comment]
Thanks all for the feedback. I find the resources we have are great for the course, but I also find myself wondering how well I would do without access to the lectures, class documentation, the issues forum, and the chat. It is useful to have advice from others!
