### ISSUE TITLE
Using Wikidata-package - Installing PHP curl-extension on digitalocean?

### ISSUE THREAD

**Issue by nekoCC01** [susanBuck/dwa15-fall2017#116]
I would like to use [this wikidata-package](https://github.com/freearhey/wikidata) to fetch some data.
The installation of the package worked locally and live.

But now a bit more complex query throws an **error live** (not locally).
By temporarily enabling Debugging on the live server, I got the message

`Call to undefined function Sparql\curl_init()`

I guess, the **missing curl-extension** is the reason:
I can see a curl-section in my **phpinfo()**-output locally (with curl being "enabled"), whereas on the live/production-server such a section is missing.

Could I just run the **installation command for curl**?

`sudo apt-get install php-curl`

like indicated in [this stackoverflow-post](https://stackoverflow.com/questions/33775897/how-do-i-install-the-ext-curl-extension-with-php-7)?

I´m always a bit cautious before running bash commands on the live server, that´s why I´m asking here.
Thanks for your advice!

**Comment by gregorycoleman** [comment]
I installed curl on my server some time ago, and I have not had any problems. I think you should be OK, just remember to restart apache after you install.

**Comment by nekoCC01** [comment]
@gregorycoleman  Thanks for letting me know!
I used the "sudo apt-get install php-curl" command and the right version got automatically installed.
Works fine!
