### ISSUE TITLE
Adding Custom Class

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#117]
I made a custom class which I  want my controller to use. I am not sure what folder we add custom classes to.  I remember seeing it in lecture- just not sure where I saw this.  I am thinking it should go in the app folder. ie app/mylibrary/myclass.php.  Then we add a line to composer.json ?
maybe?

**Comment by SridharSubramaniam** [comment]
I have added it to App directory.

https://github.com/sriworks/dwa-p3-laravel-expense-log/blob/master/app/ExpenseManagement/ExpenseDAO.php

**Comment by dukesnuz** [comment]
@SridharSubramaniam Thank you
I did something similar and created a Library folder and added it in this folder. Did you have to add anything to composer.json, do anything else or did it just work?

**Comment by dukesnuz** [comment]
@SridharSubramaniam Thank you. I also found this on [stackoverflow](https://stackoverflow.com/questions/28816707/how-can-i-add-external-class-in-laravel-5). I added a line to ```classmap``` in ```composer.json```. All is working with a new namespace.
