### ISSUE TITLE
PHP coding style

### ISSUE THREAD

**Issue by gvardany** [susanBuck/dwa15-fall2017#119]
I was wondering if there is a way to automatically check the server side code against [PSR1](http://www.php-fig.org/psr/psr-1/) and [PSR2](http://www.php-fig.org/psr/psr-2/) rules?

**Comment by zeroender** [comment]
I was wondering about this myself, did a search after seeing your question.

There are a couple plugins one utilize:

https://www.matthewsetter.com/enforcing-psr1-and-psr2-with-phpstorm/ - seems more like a checker, which is probally okay.

http://cs.sensiolabs.org/ - this auto-fixes php code to conform to psr standards.  Seems a little like cheating to me - esp as the point would be to learn or at least somewhat learn the standards.

The best option seems like PHP code sniffer (see blog post - https://akrabat.com/checking-your-code-for-psr-2/).  This checks PHP files but doesn't autocorrect, and you don't have to be using PHPStorm/don't have to switch at this point in the class if you're not already using it.  

Note: I haven't tried any of these yet!  I might try the sniffer... I guess I have an open question, however, of how ethical it is to use such a tool in this class (in a professional context I think it would be totally fine).

**Comment by susanBuck** [comment]
>> I have an open question, however, of how ethical it is to use such a tool in this class.

It's a-ok to use code checkers in this course. 

Adding to @zeroender's suggestions above:
Atom can tap into PHPCS (once phpcs has been installed): https://atom.io/packages/linter-phpcs

**Comment by zeguy** [comment]
Thanks for the info. I looked into adding sensiolabs PHP Fixer as a Visual Studio extension but it's not as beginner friendly as some of the other ones I've installed. Guess I have a little project this weekend.

**Comment by davida26** [comment]
For anyone using Sublime Text 3 - I have this configured with:

1. Package Control - Install from [here](https://packagecontrol.io/)
2. Using package control i installed SublimeLinter - requires additional packages
3. I then installed SublimeLinter-phpcs - see docs [here](https://packagecontrol.io/packages/SublimeLinter-phpcs)

Originally, I also had an issue (didnt even notice) - phpcs was a bit of a hassle at first. It was throwing errors in Sublime Console and I didnt realize until I accidentally ran another command which triggered that to open. Hopefully that helps someone on sublime.

**Comment by asmatmuradi** [comment]
I found this link very convenient to install the fixer and make the changes automatically. 
[http://cs.sensiolabs.org/]

There are clear instructions on how to install the checker itself and how to use it.

**Comment by gvardany** [comment]
Thank you all for the useful answers. 👍
