### ISSUE TITLE
Tracking changes clarification - changing doc root on local

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#12]
I am reading notes for Tracking changes and confused about point number 1 (in yellow).  How and where  do you change the document root to point to hello-world. Also, why would you change document root to point to hello-world directory if we know that it has been pointing to htdocs. Maybe I missed it, but I don't remember seeing it mentioned in the lecture videos.
![image](https://user-images.githubusercontent.com/31451809/30229141-bd78a408-94ae-11e7-9e7e-6ea48724bb37.png)

**Comment by peggyo** [comment]
You edit the httpd.conf file for your server. For windows it is in \xampp\apache\conf
There are 2 lines to change - mine originally looked like, so I modified the path:
```
DocumentRoot "C:/xampp/htdocs"
<Directory "C:/xampp/htdocs">
```
I have a note to myself in my progress log to see whether there is an easier alternative to just editing the file.

**Comment by susanBuck** [comment]
Changing the doc root for Mac/MAMP users is discussed here: https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/01_Setup_local_server.md

If you're on Windows/XAMPP, those instructions do fail to mention how to change the doc root, it just tells you what it's set to by default. (I'll update the instructions to address this)

@peggyo's instructions above are correct. Find your Apache config (click the button in XAMPP that says config, select apache (httpd.conf), then edit the document root. Save and restart your server.

As to the *why* we want to change the document root - we want to serve the application directly, not via a subdirectory, to match how it's being served on the production server. This ensures any URL routing, paths, etc. are consistent.

**Comment by susanBuck** [comment]
Update:

I've improved the notes to cover document root switching for both MAMP and XAMPP: 
[Tracking changes: View hello-world on your local server](https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/06_Tracking_changes.md#view-hello-world-on-your-local-server)

I also elaborated on why we switch the doc root for different apps: 
[Tracking changes: Why do we have to switch the document root for each application?](https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/06_Tracking_changes.md#why-do-we-have-to-switch-the-document-root-for-each-application).
