### ISSUE TITLE
Getting error: Uninitialized string offset: 0

### ISSUE THREAD

**Issue by erictracy11492** [susanBuck/dwa15-fall2017#120]
I'm running into this error on line 42 and I cannot get past it. It was all working fine up until this point - I have not changed the logic here and I had used something nearly identical in P2. Once I started adding and removing validation this error kept appearing. I cannot seem to do anything to get back to where I was before. Any help is appreciated, thank you.

<img width="751" alt="screen shot 2017-10-31 at 11 57 04 pm" src="https://user-images.githubusercontent.com/31494476/32259497-4f5831ce-be97-11e7-951a-d383390258ab.png">

**Comment by nekoCC01** [comment]
This error message occurs when you try to access a string like an array (--> https://stackoverflow.com/questions/1263636/what-causes-notice-uninitialized-string-offset-to-appear ).
Are you sure that $word is always an array at line 42?

(At line 39 for example $word seems to be a string.)

**Comment by dukesnuz** [comment]
Try ```dump($word)```

**Comment by susanBuck** [comment]
Thumbs up to @nekoCC01 and @dukesnuz's suggestions above. 

Also, it'd be helpful to see where/how you're initially setting up $word.

**Comment by ALiborio** [comment]
`$word[0]` is attempting to retrieve the first character of the string. If `$word` is empty, it's going to throw that error.

We're going to have to see more of your code to get down to the root cause, but if `$word` does not have at least one letter in it `$word[0]` is going to give you that error.

**Comment by gabrielsanna** [comment]
@nekoCC01 

You should actually be able to access a string like an array in this way. Here's a quick test using `php artisan tinker`:

```
>>> $testStr = "abcdefg";
=> "abcdefg"
>>> echo $testStr;
abcdefg⏎
>>> echo $testStr[0];
a⏎
>>> 
```

**Comment by erictracy11492** [comment]
I added a check to make sure it was not empty and the error disappeared. Thanks all for the help!

**Comment by nekoCC01** [comment]
@gabrielsanna 
I see, the string is accessed as an array of letters then.
Thanks for letting me know!
