### ISSUE TITLE
How to tell blade to return a given view if the validation fails?

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#122]
From
https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/20_Forms_POST.md

We have:
`Route::post('/book', 'BookController@store');`

In the store function, the last line does a redirect.
Let's assume that there's a validation ahead of redirect.
`return redirect('/book/'.$title);`

Now, when a user access url as localhost/book, it will execute the store function, and let's say the validation fails (because the url was accessed directly instead of form POST submission), then the redirect view call is not executed.

I then get the error:
`Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException`

from:
```
C:\xampp\htdocs\p3\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php
    protected function methodNotAllowed(array $others)
    {
        throw new MethodNotAllowedHttpException($others);
    }
```
How to handle this scenario?
How to tell blade to return a given view if the validation fails?

Thanks,
-Sri

**Comment by gvardany** [comment]
@ysrinu , I think there is some confusion here. The error you are getting is because when you type access `localhost/book` in your browser URL, you are making a `GET` request, however your route declares as `post`, hence you get the `MethodNotAllowed` exception. The correct way is to have another route for the same URL but with `GET` method, that will invoke another action of your controller where there is no form processing and you can return the corresponding view.

**Comment by ysrinu** [comment]
@gvardany that's a very good suggestion and thanks for reminding that 'enter' in url makes the request GET (we keep forgetting when too focussed on debugging!) I would think there would be an easy way to 'fix' this symptom instead of using GET route for all POST routes?

**Comment by gvardany** [comment]
True that it will mitigate the confusion, however for a form submission which has to insert/alter/delete some database entry on the server it is recommended to use POST. In this case you probably don't want to allow someone to trigger this action with a URL entry, but only with the submit button.

**Comment by susanBuck** [comment]
Confirming the comments above - you don't want a user to be able to directly visit a POST route, so the `MethodNotAllowedHttpException` is logical. Also note that on production it would just display a generic "There was a problem" message which is also a logical result in the off chance a user tries to directly access a POST route.

**Comment by mfs780** [comment]
@susanBuck thanks for the clarification

**Comment by ysrinu** [comment]
@gvardany  and @susanBuck  thanks for the clarification. Now, it's beginning to make sense where GET and POST are more meaningful, I mean by practice hands-on experience!
Users clicking browser 'back' button or 'refresh' button can provide undesirable user experience, not uncommon with many enterprise web applications.
