### ISSUE TITLE
Check out my site and share yours!

### ISSUE THREAD

**Issue by dmbartles** [susanBuck/dwa15-fall2017#123]
Hey all, here's a link to my P3!

http://p3.kodiakjetpack.club

It's a Ninja-styled password generator. It uses a simple combinations of nouns, verbs and adverbs to create passwords that sound like ninja moves. In total, there's over 3 million combinations of passwords

Why use ninja moves ?

They create funny visualizations and are easy to commit to memory
They are lengthy enough to have the entropy to be nearly unhackable
Ninjas are awesome
Additionally, I made up a fictional character, Master Po, who makes comments about passwords in general when the page is initially loaded or random comments about the ninja moves.

Please share your feedback.

**Comment by nekoCC01** [comment]
@dmbartles  Hi, sounds interesting, but unfortunately I get an 404 error message when clicking the link.

**Comment by dmbartles** [comment]
Thanks fr the feedback I fixed it!!

**Comment by gvardany** [comment]
Thanks for sharing your work, it is an interesting idea and implementation. One general remark I would make is that in real life applications it is preferable to have more readable and eye-friendly fonts. Though I sympathise your wish to make it look unique.

**Comment by natethegreat418** [comment]
hey @dmbartles : good stuff! I am reminded of the famous XKCD comic on making good passwords. This passes his test!

I made a DnD character name generator (p3.marcustechnologies.tech). The personalized match does some fuzzy matching based on the name entered to rank the possible matches and return a "best" match. Enjoy.

**Comment by susanBuck** [comment]
Closing this out as we conclude week 10, but feel free to keep sharing your projects!
