### ISSUE TITLE
foreach loop inserting whitespace

### ISSUE THREAD

**Issue by TheLivingNick** [susanBuck/dwa15-fall2017#124]
A low priority issue, since I found a workaround, but thought I'd ask it for the future. Part of my site has a @foreach loop in a view that is supposed to output a series of images that line up next to each other. The issue was that when I wrote the code like this
```
@foreach ($arrayName as $elementName)
    <img src="/images/fileName-{{ $elementName }}.png">
@endforeach
```
the final file outputted to the browser would have whitespace in between each of the image tags. Not much. but enough to look a bit off. Writing it all on one line
`@foreach ($arrayName as $elementName)<img src="/images/fileName-{{ $elementName }}.png">@endforeach`
fixed the issue, but looks less than elegant. Is there any other way to prevent the white space?

**Comment by dukesnuz** [comment]
@TheLivingNick Have you tried using list tags and then styling with css?

**Comment by TheLivingNick** [comment]
@dukesnuz No, I haven't tried something like that. What sort of CSS would remove whitespace, though? Nothing I search seems to do the job.

**Comment by dukesnuz** [comment]
@TheLivingNick I was thinking of what I had done to display a list using foreach loop.  Using list tags will display images in a list format, To display images horizontally see this [stackoverflow](https://stackoverflow.com/questions/27697549/how-can-i-use-css-to-style-multiple-images-differently)

I am assuming you mean the space between each image when rendered in the browser.

**Comment by TheLivingNick** [comment]
@dukesnuz I made a change to the production server so I can show you an example of what I mean. The first link shows the result of having the entire foreach on one line, the second on separate lines and the resultant whitespace.
[One line no whitespace](http://p3.beyondthepage.org/?userWord=hello&bonusMult=noBonus)
[Separate line with whitespace](http://p3.beyondthepage.org/example?userWord=hello&bonusMult=noBonus)

**Comment by dukesnuz** [comment]
Unless I am missing something the second link looks more correct than first.  I would take out the ```<br>``` tag and add a new ```<p class="points">``` tag for  "is worth 8 points" and
add this to my style sheet: 

```
tilePic {
    float: left;
}
``` 

```
points {
   clear left;
}
```
Add some styles to align above.

Is this what your are trying to accomplish?  I am not an expert dev so not sure if I am giving good advise.

**Comment by TheLivingNick** [comment]
The issue is the whitespace showing up between the tile images in the second link, i.e. H  E  L  L  O instead of HELLO.

**Comment by rrtx2000** [comment]
I was thinking you could try something like this:
```
<?php
	$html = '';
	$teststr = ['H','e','l','l','o',' ','W','o','r','l','d'];
?>
@foreach ($teststr as $char)
	<?php $html .= $char; ?>
@endforeach
{{ $html }}
<br/>It worked but if the spaces were still there, str_replace would remove them:<br/>
<?php $html = str_replace(" ","",$html);?>
{{ $html }}
```
Here's the output:
Hello World
It worked but if the spaces were still there, str_replace would remove them:
HelloWorld 

Obviously, your $elementName wouldn't be in blade syntax:
`<?php $html .= '<img src="/images/fileName-' . $elementName . '.png">';`

**Comment by dukesnuz** [comment]
@TheLivingNick Try this. In your tilePic style at this ```margin: 0 -3px;```

**Comment by ysrinu** [comment]
@TheLivingNick I@foreach loop adds a new line that's translating into a white space. 
I guess even if you use the below syntax, alternative to the template syntax (only pseudo-code below):
```
<?php foreach($arrayName => $elementName) : ?>
<img src="/images/fileName-{{ $elementName }}.png"
<?php endforeach ?>
```
I would think you would still get the white space, because there's newline for each loop iteration.

Your workaround is the best solution. I have seen this issue, native to html code where I had to put the entire code in one line, as the 'newline' would differ the number of pixels by 1 horizontally.

**Comment by mfs780** [comment]
```
<div class="haveResult">
    <div style="display: flex;  justify-content: center;">
        <img class="tilePic" src="/images/letter-h.png" alt="h">
        <img class="tilePic" src="/images/letter-e.png" alt="e">
        <img class="tilePic" src="/images/letter-l.png" alt="l">
        <img class="tilePic" src="/images/letter-l.png" alt="l">
        <img class="tilePic" src="/images/letter-o.png" alt="o">
    </div>
    <p>is worth 8 points</p>
</div>
```

@TheLivingNick this should work. Also `<p>` tag should typically not have other elements contained within it. A `<div>` is more appropriate.

**Comment by dmbartles** [comment]
Hey bud, 
I would use a bit of padding to your CSS file likeso:
`.haveResult{
    text-align: center;
    font-size: 50px;
    padding: 0px 2px 0px 2px;
}`

Hope that helps!

**Comment by TheLivingNick** [comment]
I'm going to close it because I think we've explored as deep as we need to for such a small issue. Thanks for all the help!
