### ISSUE TITLE
Project 4 Naming Conventions

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#125]
I am confused about naming conventions for Project 4. We are supposed to name github 
```https://github.com/something/p4```  and  production URL should be ```http://p4.yourdomain.com```. But it mentioned in the lecture and progress log, that our application name should be different, not p4? I am confused on the naming conventions of the project/application locally? Shouldn't it the same locally, github and production?

**Comment by susanBuck** [comment]
Project 4 (p4) is the name of the project, but the application you're building for this project should have its own name/title (e.g., "Foobooks").

**Comment by susanBuck** [comment]
Project 4 (p4) is the name of the project, but the application you're building for this project should have its own name/title (e.g., "Foobooks").
