### ISSUE TITLE
1045 - Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#126]
I had this issue and thought I would share with you guys how I solved it. 

phpmyadmin defaults to user root with **NO** password. If, when you set up mysql, you did not create a root user or if you specified a password for your account, you will get an error when you try to connect to phpmyadmin. To solver this, go to `xampp\phpMyAdmin\config.inc`. Then change the below configurations to how you set up your mysql account

`$cfg['Servers'][$i]['user'] = 'root';`
`$cfg['Servers'][$i]['password'] = 'your password';`

**Comment by susanBuck** [comment]
@APuente21 Can you elaborate on what you mean by setting up mysql? Just want to avoid any confusion, as there were no user creation steps for mysql in the process we've seen thus far.

**Comment by APuente21** [comment]
When I originally installed mysql, for another class, I set up a password for my root account. I think with Larvel, by default, the password is blank, but because I specified a password in my original set up, I was getting an error message, the one I mentioned above. So, in order for me to get everything working I had to change the config file to include my password.

**Comment by susanBuck** [comment]
Got it. Thanks for confirming and sharing. 

Just to clarify for MAMP/XAMPP students - your username/password defaults to what is documented in the notes - no need to alter it. But, if you do alter it, @APuente21's note above is useful.
