### ISSUE TITLE
Project 4 Tables design

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#128]
@susanBuck I am confused about tables design for Project 4 progress log this week. We specify primary keys, but not foreign keys (which we did not cover yet?) Also, in P4 requirements it says to use 2 database tables and 1 pivot table. Does it mean that we must have many to many relationships with linking table in the middle? Is linking table the same as pivot table? We did not cover anything about foreign keys, linking tables, or different kind of relationships yet, so our tables will not be complete and fully designed?

**Comment by susanBuck** [comment]
Do not worry about foreign keys, pivot tables or relationships right now. We haven't covered them yet. As discussed in lecture, the design of your tables are a work in progress.

**Comment by dukesnuz** [comment]
@dianakleban Check out the links for [SQL for Beginers](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/22_Database_Primer.md) towards the bottom of this lecture page. Very good read.
