### ISSUE TITLE
ssh-keygen crash

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#13]
Did anyone encounter issues with ssh-keygen crashing?

I know I didn't pass any parameter to the keygen command, but it doesn't matter, it crashes neverthless

![image](https://user-images.githubusercontent.com/25366909/30244745-3d2865a6-9592-11e7-83e4-dee3279eb5d6.png)

I then used PuTTY Key Generator (PuTTYgen 0.70) to create RSA private/public keys. Removed the .ppk extension from private key and copied both keys to my .ssh folder.

![image](https://user-images.githubusercontent.com/25366909/30244846-ebbb17ba-9594-11e7-92b3-b8476703f5b2.png)

SSH connection still fails
Note the debug message : PEM_read_PrivateKey failed

![image](https://user-images.githubusercontent.com/25366909/30244850-f7939b2a-9594-11e7-95aa-61c061fce0d8.png)

**Comment by mildredfakoya** [comment]
[read this. it might help](http://www.solvusoft.com/en/files/error-virus-removal/exe/windows/lutris-technologies/enhydra-2-3/ssh-keygen-exe/)

[try the suggestions from this link and see if it helps](https://stackoverflow.com/questions/8780654/git-ssh-exe-has-stopped-working )
let me know if it helps and shich helped

**Comment by gregorycoleman** [comment]
If you have a Digital Ocean server, you can generate a ssh on Linux, and copy to you Windows machine. I have found that it is less problematic than ssh-keygen on Windows.

If you need to get to your D.O. server, you can use a password initially, instead of ssh.

**Comment by ysrinu** [comment]
Last night I ran Cmder with 'administrator' privileges but didn't help.
The Cmder we downloaded for the course is v1.4.1.1 and with custom changes (such as packaged nano 2.4.2), changes in the Readme.md file.

I now downloaded the latest cmder v1.3.2 and 'full' (with git-for-windows) from
http://cmder.net/

On running cmder, it prompts to update to the latest ConEmu and I went for it and restart the cmder.

Now, ssh-keygen doesn't crash
![image](https://user-images.githubusercontent.com/25366909/30249068-7c9ea4ec-9601-11e7-92b9-cbbf7e07ddad.png)

I downloaded the latest nano executable v2.7.5 for windows from https://www.nano-editor.org/dist/win32-support/
and saved it in Cmder bin folder, renamed nano-git-0d9a7347243.exe to nano.exe

![image](https://user-images.githubusercontent.com/25366909/30249113-7afb2e84-9602-11e7-976b-f16957c7529a.png)

Since I am more comfortable with 'vi' editor, I downloaded Win32 console executable (vim80w32.zip) from https://vim.sourceforge.io/download.php#pc
extracted the files, and copied vim.exe to my cmder bin folder
![image](https://user-images.githubusercontent.com/25366909/30249156-a8c07f4e-9603-11e7-8dc6-d5dc9a17c169.png)

I didn't make other changes that our professor made to the Cmder (like changing default prompt, missing dll files), will do as I find it necessary.

**Comment by EricXDing** [comment]
Meanwhile, I think if you really need a pair of keys, you can generate a pair online?
For example
http://travistidwell.com/blog/2013/09/06/an-online-rsa-public-and-private-key-generator/
http://www.csfieldguide.org.nz/en/interactives/rsa-key-generator/index.html

**Comment by stbenjam** [comment]
That seems like a terrible idea since you have no idea who those people are and now they have a copy of your private key.

Those keys are are also transmitted in plain text over HTTP so the guy next to you at Starbucks has it now too.

**Comment by susanBuck** [comment]
@ysrinu I haven't seen other reports of ssh-keygen failing like this in the course version of cmder, but I'm going to run some tests. Your workaround of downloading the latest cmder and bundling in what you need seems like it's getting the job done.

@stbenjam @EricXDing 
FWIW - The keys in both those tools are generated with JS in the browser, and I see no server side call being invoked when they're generated. I also don't see them being stored locally (where the site owners could then retrieve them on a later request). So they're not being transmitted over plain HTTP and they're not being retained by the site owner. 

I wouldn't say it's a terrible idea, but I do agree it does feel a little weird, and it's useful to be cautious of tools like these. We know how to check how the keys are generated, but not everyone does, and this means copycat sites might exist that aren't as benign.

**Comment by ysrinu** [comment]
Thanks @susanBuck , I didn't check the release notes of intermediate versions of cmder to see if there's a specific change to fix crashes in certain instances, although it does look like the latest is more stable on my machine.
Thanks everyone for the suggestions and feedback.
This thread can be closed now.
-Sri
