### ISSUE TITLE
Commit Migrations to Github

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#130]
I am just wondering: after creating migrations, do we need to commit them to github or leave them locally at this point.

**Comment by gregorycoleman** [comment]
You commit them to GitHub. Migrations are meant to be run in different environments. You have your migrations locally, but they also need to be run on your production server. 

Commit them to git, ssh into your production server and run `php artisan migrate` and that will bring your production server up to the same database level as your local development setup.

**Comment by dianakleban** [comment]
Unless I missed it, I don't think we covered it in the lectures yet?

**Comment by susanBuck** [comment]
You should commit your migrations to Github, per the note in the Week 10 progress log:

> Commit and deploy all changes to your Project 4 repository on Github before submitting this progress log so I can skim your work in progress (if necessary).

However, it is not expected that you run migrations in production yet. This is not something I've shown how to do and we'll cover it in Week 11.
