### ISSUE TITLE
Connecting to DB from production server

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#131]
How do we connect to our database from our production server? Also, do we need to update our DB_HOST?

```
> DB_CONNECTION=mysql
> DB_HOST=127.0.0.1
> DB_PORT=3306
```

**Comment by susanBuck** [comment]
I'll cover this in Week 11 (this wed):

> Week 11 - Nov 8
> Laravel: Seeders, Production DB setup, Models

**Comment by luke777gu** [comment]
Thanks, I was wondering the same.

**Comment by luke777gu** [comment]
Thanks, I was wondering the same.

**Comment by luke777gu** [comment]
Thanks, I was wondering the same.

**Comment by luke777gu** [comment]
Thanks, I was wondering the same.

**Comment by luke777gu** [comment]
Thanks, I was wondering the same.

**Comment by luke777gu** [comment]
Thanks, I was wondering the same.
