### ISSUE TITLE
DWA-workflows in one document

### ISSUE THREAD

**Issue by nekoCC01** [susanBuck/dwa15-fall2017#132]
Hi, just wanted to share a simple document, where I assembled the steps and workflows we learnt so far, copy&pasted from the course notes. I did it for my convenience, perhaps it´s helpful to someone. You can find it [under this link](https://docs.google.com/document/d/1Gx4TGVUzFm5ccPM7vKRlZxVGrmhnToI18m_GHK9Qzbs/edit?usp=sharing).

**Comment by ysrinu** [comment]
@nekoCC01 This is a great cheat sheet! Thanks

**Comment by dukesnuz** [comment]
Like this a lot Adding a link to my list I created on github.

**Comment by drumph33** [comment]
Thanks for this it will be a good place to refer back to

**Comment by asmatmuradi** [comment]
@nekoCC01 thanks for sharing, this is a great link.

**Comment by helhaggaz** [comment]
Thanks .. thats very helpful.

**Comment by SridharSubramaniam** [comment]
Thanks for sharing @nekoCC01
