### ISSUE TITLE
Table 'users' already exist

### ISSUE THREAD

**Issue by Diegometro1** [susanBuck/dwa15-fall2017#133]
_i've created a new table and when i tried to migrate a error msg appear. Any ideas How can i fix it?_
I have delete the table and created again.

i used :php artisan migrate:rollback
            php artisan migrate
            
<img width="1335" alt="screen shot 2017-11-07 at 11 35 19 pm" src="https://user-images.githubusercontent.com/8799504/32532320-692e6ffc-c417-11e7-9139-902afd4597f1.png">

**Comment by gregorycoleman** [comment]
`php artisan migrate:rollback` This command rolls back the last "batch" of migrations. Try `php artisan migrate:fresh` command to drop all tables from the database and then execute the migrate command.

**Comment by drumph33** [comment]
Not sure if its relevant but the existing migration that comes with laravel creates a table called users.  If you were trying to create your own called users there may be an issue.

**Comment by susanBuck** [comment]
👍 to @gregorycoleman's suggestion: `php artisann migrate:fresh`

If that fails, go into phpMyAdmin and manually delete all the tables then try running your migrations again.

**Comment by TheLivingNick** [comment]
Ran into the same issue. Deleting the tables and starting fresh with a renamed table solved the problem. Just make sure that all instances of 'Users' in the migration are replaced, or just delete the migration and create a new one.

**Comment by susanjiang03** [comment]
use "CREATE TABLE  IF NOT EXISTS users" in migration.
