### ISSUE TITLE
Undefined Variable

### ISSUE THREAD

**Issue by tericson1** [susanBuck/dwa15-fall2017#136]
I keep running into where I can successfully dump variables via request after submitting a form, but when I try to print them {{ variable }} I get the error on my local server "Undefined variable:"

I am attempting to access input from the from in order to display it. 

Has anyone seen this?

**Comment by ysrinu** [comment]
@tericson1, are you missing the '$' in the blade syntax?
`{{ $variable }}`

**Comment by tericson1** [comment]
thanks for the comment - no, I did use the $

**Comment by susanjiang03** [comment]
use {{ old('yourvariablename')}}

**Comment by susanBuck** [comment]
Few troubleshooting questions:
* Are you dumping the variables in your controller methods or views?
* Are the variables being passed to the views?
* Are you able to consistently recreate the problem, and if so, can you point to where in your repository is the code in question so we can take a look?

**Comment by HeinrichTremblay** [comment]
Can you share the complete error message as well as the part of the code causing it?

**Comment by dmbartles** [comment]
I run into this issue occasionally when I use forms, but haven't set up the method or action properly. We'd need the code to figure it out though.

**Comment by tericson1** [comment]
Hi, 

Thanks everyone - my controller file is here - 

https://github.com/tericson1/p3/blob/master/app/Http/Controllers/BillController.php

Blade file
https://github.com/tericson1/p3/blob/master/resources/views/calc.blade.php

Full error message - 
ErrorException (E_ERROR)
Undefined variable: tip (View: /Applications/MAMP/htdocs/p3/resources/views/calc.blade.php)

To the earlier question-
Are you dumping the variables in your controller methods or views? --> I am in the controller- I removed this locally but still getting the same error
Are the variables being passed to the views? I attempted to but maybe I am missing something here 
Are you able to consistently recreate the problem, and if so, can you point to where in your repository is the code in question so we can take a look? Yes, happens every time w/ any variable I try. This line is my blade file is what generates it 

<p> tippy {{$tip}}</p>

**Comment by HeinrichTremblay** [comment]
@tericson1 Just a quick tip,  take some time to refactor your code indentation, good code readability helps to debug faster and is nicer for people who are trying to help you. Here is a [gist as an exemple](https://gist.github.com/HeinrichTremblay/e2edd51d7edbe534fb18e758531bca73) of how your code could be better indented.

I just installed your P3 locally and found the bug. If you look at your routes, you'll see that your `/` route point to `BillController@index`. 

``` php
public function index()
{
    return view ('calc');
}
```

You'll have to pass some default values to your `calc` view, just as you did with `BillController@calc`. That's why your view crash.

It should look something like this instead:
``` php
public function index()
{
    return view('calc')->with([  ... Put your default values here ... ]);
}

```

**Comment by susanBuck** [comment]
Bumping this post to see if this issue can be closed or if it's still pending.

**Comment by tericson1** [comment]
i haven't had a chance to test it, but I Heinrichs solution makes sense (thank you!) so closing is fine

**Comment by susanBuck** [comment]
Thanks @tericson1 ! Feel free to start a new thread if the problem persists.
