### ISSUE TITLE
undefined index error in View

### ISSUE THREAD

**Issue by arow510** [susanBuck/dwa15-fall2017#138]
Hello everyone, I'm running into an issue with one of my views... For some reason I'm getting an error saying that there is an undefined index. Can someone take a look at this for me and provide some guidance please? 

![image](https://user-images.githubusercontent.com/31460880/32633399-3366c748-c55c-11e7-813c-5afd7fec12dd.png)

**Comment by susanjiang03** [comment]
You do not post anything yet on the page. so the $_POST values are not set.
you can use put your codes inside ` if (isset($_POST['subtotal'])){}`

**Comment by arow510** [comment]
So if would look like this?

  $subtotal = if (isset($_POST['subtotal'])) {}

**Comment by susanjiang03** [comment]
<?php  if (isset($_POST['subtotal'])){ ?>
      your line 85 - 100 
      ....
<?php } ?>
you can do like  this . 
but  in your code, you need to validate your  valuable subtotal , percentage and custom-percentage are all submitted.

**Comment by arow510** [comment]
that worked... 

Now I'm getting a new error after submitting the form!

![image](https://user-images.githubusercontent.com/31460880/32635082-98464bdc-c563-11e7-9aa3-fa91e118ad38.png)

**Comment by susanjiang03** [comment]
You do not correctly registered the route with the form method.  either change on the form method or on the router.

**Comment by arow510** [comment]
Where would i make these changes?

**Comment by susanjiang03** [comment]
if you form method is "POST", in your routes/web.php, you should have:
Route::post('/nameOfYourFormAction', 'nameOfYourController@nameOfyourFormPostFunction')

**Comment by arow510** [comment]
This is what I have... 

![image](https://user-images.githubusercontent.com/31460880/32636805-3e315cb0-c56b-11e7-8350-a4b5cde6c3d3.png)


![image](https://user-images.githubusercontent.com/31460880/32636809-4324ede0-c56b-11e7-818a-8f01e8e220dc.png)

**Comment by arow510** [comment]
In my controller

![image](https://user-images.githubusercontent.com/31460880/32636835-76849bc2-c56b-11e7-9511-8db17cb26618.png)

**Comment by susanjiang03** [comment]
you have duplicate post router and  do not need to return view there.  use different function name for form submit.  change first one to : 
`Router:get('/','CalcuController@index'` this is your welcome page. 
second one to : 
`Router:post('/','CalcuController@calculation')`   if calculation is the function for submit the form.

**Comment by arow510** [comment]
Okay, after making these changes.. I got the same error.. So I changed everything to the below, when I submit the form now, I get no errors but there is no calculation performed.. All values are cleared from the form as if its resetting..

![image](https://user-images.githubusercontent.com/31460880/32639558-554a3f9e-c579-11e7-9a74-88518bd48f90.png)

![image](https://user-images.githubusercontent.com/31460880/32639650-be7975ac-c579-11e7-8da7-5095b240b48c.png)

![image](https://user-images.githubusercontent.com/31460880/32639663-c9b772e8-c579-11e7-889c-9a7c1de80c1b.png)

**Comment by susanjiang03** [comment]
I would suggest you do the calculation in your function, then display the result on the page. for e.g.
in your function the param should be `function calculation(Request $request)`
you get your form input by : `$subtotal = $request->input('subtotal');`
after calculation, you return the result on view
`return view('calcu')->with(
[   ''tip" => $tip,
     "total" => $total,
])`;
on your view, you add  `{{$tip}}` to display the value

**Comment by arow510** [comment]
Like this?

![image](https://user-images.githubusercontent.com/31460880/32642735-2801be24-c58b-11e7-9139-0b3b7d3fa6bd.png)

![image](https://user-images.githubusercontent.com/31460880/32642760-568b0b7e-c58b-11e7-9195-d24b71a9398d.png)


![image](https://user-images.githubusercontent.com/31460880/32642769-66acc2c2-c58b-11e7-924e-f553fc3f88b4.png)

**Comment by susanjiang03** [comment]
no. the return should be the last line in your calculation function .

**Comment by arow510** [comment]
in the second picture?

**Comment by susanjiang03** [comment]
yes. remove return in the second picture.

**Comment by arow510** [comment]
Wait im confused.. Remove return or add?

[welcome.txt](https://github.com/susanBuck/dwa15-fall2017/files/1460159/welcome.txt)

[calcu.txt](https://github.com/susanBuck/dwa15-fall2017/files/1460160/calcu.txt)


[web.txt](https://github.com/susanBuck/dwa15-fall2017/files/1460175/web.txt)

[CalcuConT.txt](https://github.com/susanBuck/dwa15-fall2017/files/1460177/CalcuConT.txt)


Are you referring to the welcome file, calcu file, web file or calcuConT

**Comment by susanjiang03** [comment]
I am sorry. I mean remove return that after `Route::`, put in your calculation function. and your php codes to do the calculation should be in the function also.

**Comment by arow510** [comment]
Like this

![image](https://user-images.githubusercontent.com/31460880/32645024-0344a380-c59a-11e7-8e3b-3c5e92e112d5.png)

**Comment by susanjiang03** [comment]
yes. and your logic code should be in the function also. and you return the variable you need to display on the view.

**Comment by susanBuck** [comment]
The scope of this question is quite large, so @arow510 and I are addressing it one-on-one. Closing this thread.
