### ISSUE TITLE
seeders, generate sample data

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#139]
I was looking forward to see laravel generate sample data in the 'seeders' topic. However, I see that the 'seeder' classes here are simply to seed data into the tables, not really generate the source data itself in the first place.
I use http://www.generatedata.com/ to generate 100s (or 1000s) or rows of data and works with foreign key constriants too. The generated data can be exported as csv,xls, json, xml,... formats.
I would take the json format and include in the laravel seeder class and write the loop to iterate and insert each record.

**Comment by susanBuck** [comment]
Along these same lines, by default Laravel comes with a package called Faker that is really useful for generating dummy data in your seeders: <https://github.com/fzaninotto/Faker>

(Note: It's not required that you dynamically create your seed data; for project purposes hard-coding it as I did in the lecture demo/notes is fine)
