### ISSUE TITLE
Cloning a repository crashes cmder

### ISSUE THREAD

**Issue by rrtx2000** [susanBuck/dwa15-fall2017#14]
I'm having a problem cloning a repository using Windows 10.
**The short version:** 
When I run "git clone git@github.com:rrtx2000/hello-world.git" it crashes the cmder window. The hello-world directory gets created with the .git subdirectory but it doesn't copy the README.md file to my local drive. The command "git log" returns "fatal: bad default revision 'HEAD'"

**The long version:**
The ssh -T git@github.com command works:
Hi rrtx2000! You've successfully authenticated, but GitHub does not provide shell access.
git --version returns git version 1.9.4.msysgit.0
My path has the cmder files: PATH=C:\Program Files\cmder-master\bin;C:\Program Files\cmder-master\vendor\msysgit\bin;C:\Program Files\cmder-
master\vendor\msysgit\mingw\bin;C:\Program Files\cmder-master\vendor\msysgit\cmd;C:\Program Files\cmder-master\
vendor\msysgit\share\vim\vim74;C:\Program Files\cmder-master;C:\Program Files\cmder-master\vendor\conemu-maximu
s5\ConEmu;C:\Program Files\cmder-master\vendor\conemu-maximus5;...

I create the repository on github with the README.md file
In cmder I go to C:\xampp\htdocs
I run git clone git@github.com:rrtx2000/hello-world.git
It initially says "Cloning into hello-world..." but then it crashes the cmder window
![git_problem1](https://user-images.githubusercontent.com/25423639/30251925-1f2f02b0-962f-11e7-8a94-fb2156a9842f.jpg)
The hello-world directory gets created at C:\xampp\htdocs\hello-world and has the .git subdirectory but nothing else (the README.md file is missing)
Reopen cmder and go back to C:\xampp\htdocs\hello-world
The command "git log" returns "fatal: bad default revision 'HEAD'"
![git_problem2](https://user-images.githubusercontent.com/25423639/30251928-2b7f66ea-962f-11e7-80fb-54bc6ba92065.jpg)
git pull crashes the cmder window
git status shows:
On branch master
Initial commit
nothing to commit (create/copy files and use "git add" to track)

The github page showed another method so I tried it:
I deleted the repository on github 
I deleted the hello-world directory on my local drive.
git init
md hello-world
cd hello-world
echo "hello world" >> test.txt (create a test.txt file)
git add test.txt
git commit -m "commit the test file"
git remote add origin git@github.com:rrtx2000/hello-world.git
git log crashes the cmder window
git push -u origin master	crashes the cmder window
Nothing shows up on github.com

Any ideas?

**Comment by peggyo** [comment]
From this link https://stackoverflow.com/questions/6214711/git-log-and-show-on-a-bare-repo  it looks like 'HEAD' should be a pointer to a branch, which in this case would be 'master'.  Does running `git log master` give you anything more useful than just `git log`? 
I am new to git, so only guessing.

**Comment by gregorycoleman** [comment]
In your second try, you have to create the repo on GitHub before you push to it. That is why you did not see anything on GitHub.

**Comment by susanBuck** [comment]
Piggy-backing on the above suggestions - also try cloning with another repo we know is working. For example, you can try the demo I set up:

```
git clone git@github.com:susanBuck/hello-world.git
```

If that fails as well, we know it's system specific, not repo specific.

**Comment by rrtx2000** [comment]
I tried using a regular command window instead of cmder and ran the same commands.
It showed "Permission denied (publickey)."
I ran "ssh -vT git@github.com" in cmder and the regular command window and both showed the same error.
I deleted my keys and made new ones.
Now running "ssh -vT git@github.com" in cmder says it's OK but it is still crashing when I try to do the git clone.
Running "ssh -vT git@github.com" in a regular command window fails. 

The difference between cmder and the regular command window appears to be the identity file

regular command window (partial)
debug1: identity file /.ssh/identity type -1
debug1: Trying private key: /.ssh/id_rsa
debug1: No more authentication methods to try.
Permission denied (publickey).
![regular](https://user-images.githubusercontent.com/25423639/30254000-ae171dce-9656-11e7-816e-8bf4ad2dcafa.jpg)

cmder window (partial)
debug1: identity file /c/Users/Alan/.ssh/identity type -1
debug1: Trying private key: /c/Users/Alan/.ssh/identity
Hi rrtx2000! You've successfully authenticated, but GitHub does not provide shell access.
debug1: Exit status 1 
![cmder](https://user-images.githubusercontent.com/25423639/30253998-a900f922-9656-11e7-8435-ac0ae9631400.jpg)

git clone git@github.com:susanBuck/hello-world.git also crashes the cmder window.

Are we supposed to have a config file in the .ssh directory? 
I don't have one although I tried some different things but none worked.

**Comment by rrtx2000** [comment]
I got it to work in a regular command prompt window but it still crashes in cmder. I found the solution here:
https://stackoverflow.com/questions/17846529/could-not-open-a-connection-to-your-authentication-agent
It's the answer with 31 upvotes that starts with "In Windows 10 I tried all answers listed here but none of them seemed to work. In fact they give a clue. To solve a problem simply you need 3 commands..."
