### ISSUE TITLE
Logo not displaying in all views

### ISSUE THREAD

**Issue by ruthnphillips** [susanBuck/dwa15-fall2017#140]
I have created a master view, and child views. In my child view `success.blade.php` my logo is not rendered. I can't figure out why. 

Master view: `resources\views\layouts\master.blade.php`
Working child view: `resources\views\athlete\register.blade.php`
Not working view: `resources\views\athlete\success.blade.php`
Repo: https://github.com/ruthnphillips/dwa_project4

**Comment by nekoCC01** [comment]
I had the same issue. Try to change the img-path in the "master.blade.php"-file (line 25) to a non-relative path beginning from the root, like so:

`src='/img/logo2.png'`

Did this solve the problem?

**Comment by ALiborio** [comment]
I had something similar happen.

I originally had this in my master blade:
`<img src="images/logo.png">`
On some of the views this worked fine, but others it was broken. It looked like it was looking for it in a sub directory so if I was on the URL `p4.dev` or `p4.dev/character` it worked just fine. However on `p4.dev/character/1` it did not.

I changed it to this:
`<img src="{{ asset('images/logo.png') }}">`
And that fixed it for all views.

**Comment by ruthnphillips** [comment]
@nekoCC01: Nope, didnt work for me
@ALiborio: Yes that worked.
Thanks both for responding!
