### ISSUE TITLE
Multiple Seeders invocation

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#141]
If we need to invoke multiple seeders, do we need to make multiple call() statements in the DatabaseSeeder.php file?
![image](https://user-images.githubusercontent.com/31451809/32703784-74b6b896-c7c0-11e7-9632-fcac93f9803d.png)

Also, what if we want to run some specific seeders and not all of them?

**Comment by zeroender** [comment]
Each seeder should have it's own call statement in DatabaseSeeder.  Once there, they'll all be run on a db:seed command.  You can pass an argument to specify which table should be seeded -  see https://laravel.com/docs/5.5/seeding#calling-additional-seeders

Eg, to only seed the books table, you could run

`php artisan db:seed --class=BooksTableSeeder`

**Comment by ysrinu** [comment]
@dianakleban If you want only few seeders to run, comment out the other seeder call lines from the master seeder file (your screenshot)

**Comment by susanBuck** [comment]
Student answers hit the nail on the head. Closing this post.
