### ISSUE TITLE
Seeders Dates Clarification

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#142]
I just wanted to clarify something. When you subtracted some days from the time stamps, did you do it just for testing and example purpose, or we need to do the same for our seeders in project 4? 

![image](https://user-images.githubusercontent.com/31451809/32703843-4aca033e-c7c1-11e7-87dd-ec16adb1adc1.png)

**Comment by susanBuck** [comment]
I did it so created_at/updated_at would be different for each book. I recommend doing something similar for your seeds because it makes it more similar to what real-world data (vs. if the timestamps were exactly the same).
