### ISSUE TITLE
Dynamic query builder, from string url

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#143]
1. Is there a way to build query based on the parameters in the string url (GET).
For example, the below code is hardcoded for published and author fields

`$results = Book::where('published', '>', 1950)->where('author', '=', 'F. Scott Fitzgerald')->get();`

I am looking for a query builder that will 'match' (all exact or all like) for all 'id (keyname)' in the string url that are applicable to the model, while ignoring those that have empty/null values in the string url.
For example: `http://localhost/search?name='abc'&title='great'&&publisher=&year='1990'`
should automatically run the query where the fields name, title, year match with values passed in the string url (but field publisher ignored)

2. Is it possible to programmatically build the query and execute it? For example (pseudo-code):
```
$QryBuilder = 'Book:'
for each (keyname in stringurl & keyname in model)
{ 
  if $keyvalue is null then next; // skip if the corresponding value is null
  $results+= '->where($keyname,'=',$keyvalue) //else
}
$results = exec $QryBuilder
```

**Comment by susanBuck** [comment]
Yes this is possible, but via a slightly different approach than you've shown.

foreach($request->keywords as $keyword)

**Comment by susanBuck** [comment]
Here are two examples (with comments for explanation) that demonstrate what I think you're trying to accomplish. Let me know if you have follow-up questions, or if this doesn't quite fit what you're trying to do.

# Example 1
```php
    /**
    * Example 1 of 2 for dynamically creating a query via a loop
    * Search across a single field (title)
    * https://github.com/susanBuck/dwa15-fall2017/issues/143
    */
    public function practice14()
    {
        # Example keywords to mock what you might get from the Request
        $keywords = ['harry', 'gatsby'];

        # Initiate a query using the `select` method with no params
        # This will will get all the fields from the rows that match our query
        $query = Book::select();

        # Build on the query
        foreach ($keywords as $keyword) {
            $query->orWhere('title', 'LIKE', '%'.$keyword.'%');
        }

        # Execute the query
        $results = $query->get();

        # Show the title of each book found
        foreach ($results as $result) {
            dump($result->title);
        }

        # Notes:
        # select * from `books` where `title` LIKE '%harry%' or `title` LIKE '%gatsby%'
        # "The Great Gatsby"
        # "Harry Potter and the Sorcerer's Stone"
        # "Harry Potter and the Chamber of Secrets"
        # "Harry Potter and the The Prisoner of Azkaban"
    }
```

# Example 2
```php
    /**
    * Example 2 of 2 for dynamically creating a query via a loop
    * Search across multiple fields
    * https://github.com/susanBuck/dwa15-fall2017/issues/143
    */
    public function practice13()
    {
        # Example keywords to mock what you might get from the Request
        $keywords = ['harry', 'gatsby', 1963];

        # Fields you want to search
        $fieldsToSearch = ['title', 'published'];

        # Initiate a query using the `select` method with no params
        # This will will get all the fields from the rows that match our query
        $query = Book::select();

        # Build on the query
        foreach ($keywords as $keyword) {
            foreach ($fieldsToSearch as $field) {
                $query->orWhere($field, 'LIKE', '%'.$keyword.'%');
            }
        }

        # Execute the query
        $results = $query->get();

        # Show the title of each book found
        foreach ($results as $result) {
            dump($result->title);
        }

        # Notes:
        # select * from `books` where `title` LIKE '%harry%'
        #    or `published` LIKE '%harry%'
        #    or `title` LIKE '%gatsby%'
        #    or `published` LIKE '%gatsby%'
        #    or `title` LIKE '%1963%'
        #    or `published` LIKE '%1963%'
        # "The Great Gatsby"
        # "The Bell Jar"
        # "Harry Potter and the Sorcerer's Stone"
        # "Harry Potter and the Chamber of Secrets"
        # "Harry Potter and the The Prisoner of Azkaban"
    }
```

**Comment by ysrinu** [comment]
Thanks @susanBuck Your examples search for the keyword across multiple fields in the table.

My requirement differs as below:
My search form has multiple search input fields.
For example, say there are 5 search input text boxes (for firstName, lastName, zipcode, city, state; say). The eloquent query should run only for those fields that have values populated.
So, in the search form if firstName, lastName and zipcode are entered and submitted, the server should automatically run the query equivalent to:
`$results = Book:Where('firstname,'=',$strSearchFirstName)->Where('lastname','=',$strSearchLastName)->Where('zipcode','=',$strSearchZipcode)`

The reason I have multiple search boxes (by field) and not a single is because the user wants to be able to filter by multiple search criteria, for example, list all customers with firstname 'Andy' and from state 'MA'.

**Comment by sheetaldalvi** [comment]
You may construct the query selectively (using if condition) if the field is set within the foreach loop.

**Comment by susanBuck** [comment]
@ysrinu Ok, I see how your scenario differs. As @sheetaldalvi suggested, you should be able to adapt the examples I provided using some if logic.

For example, in pseudo-code:
```
if there's a strSearchFirstName in the request {
    $query->orWhere('firstName', 'LIKE', '%'.$strSearchFirstName.'%');
}

if there's a strSearchLastName in the request {
    $query->orWhere('lastName', 'LIKE', '%'.$strSearchLastName.'%');
}
```

**Comment by ysrinu** [comment]
Thanks @sheetaldalvi and @susanBuck 
I don't see _append_ operator, but assume that '$query->' will automatically add the new filter clause to it (and not replace).
I would think it would look like (pseudo-code):
```
if (..) {
$query += $query->orWhere('firstName', 'LIKE', '%'.$strSearchFirstName.'%');
}
```
I will try and findout!
Thanks again.

**Comment by susanBuck** [comment]
> but assume that '$query->' will automatically add the new filter clause to it (and not replace).

Yup, this assumption is true.

Going to close this out, but if your tests to get this working failed, feel free to continue this discussion.
