### ISSUE TITLE
Unable to access phpmyadmin

### ISSUE THREAD

**Issue by natethegreat418** [susanBuck/dwa15-fall2017#144]
Hey all,

Been having a really hard time geting MySQL set up on my localhost environment.  Here is what I have done thus far.

1. Orgiinally couldn't get MySQL through XAMPP to start at all, but changed port in my.ini file to 8889 - then server would start appropriately. Changes made are below, in case this is somehow related.

```
# The following options will be passed to all MySQL clients
[client] 
# password       = ''
port            = 8889
socket          = "C:/xampp/mysql/mysql.sock"


# Here follows entries for some specific programs 

# The MySQL server
[mysqld]
port= 8889
socket = "C:/xampp/mysql/mysql.sock"
basedir = "C:/xampp/mysql" 
tmpdir = "C:/xampp/tmp" 
datadir = "C:/xampp/mysql/data"
pid_file = "mysql.pid"
# enable-named-pipe
key_buffer = 16M
max_allowed_packet = 1M
sort_buffer_size = 512K
net_buffer_length = 8K
read_buffer_size = 256K
read_rnd_buffer_size = 512K
myisam_sort_buffer_size = 8M
log_error = "mysql_error.log"
```

2. Then when I hit http://localhost/phpmyadmin/ , I get attached error messages.
![image](https://user-images.githubusercontent.com/17519260/32751440-ec4cdb3c-c893-11e7-8e07-4b400d8a09c5.png)

3. I attempted changing settings in XAMPP->Apache, phpMyAdmin (config.inc.php) but while I could get the "using password YES/NO values to update, I couldnt get access to the MyAdmin portal.

I've attached the config.inc.php file. I really appreciate the help.

-Nate
[copy of php.inc.php.txt](https://github.com/susanBuck/dwa15-fall2017/files/1468782/copy.of.php.inc.php.txt)

**Comment by susanBuck** [comment]
Can you add the debug route described in the notes on local database setup under [Test your connection](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/24_Local_database_config.md#test-your-connection) and report back on the details it provides?

That way we can isolate whether it's just your phpMyAdmin connection to MySQL that is failing, or any connection to MySQL.

**Comment by susanBuck** [comment]
Also, can you share the contents of `c:\xampp\phpMyAdmin\config.inc.php` ?

**Comment by ysrinu** [comment]
@natethegreat418 Did you open the phpmyadmin from the MySQL 'admin' link from XAMPP control panel?
In your screenshot I can see the PID and port (mysql) values. Can you run netstat command to check if the server is listening on that port?

`netstat -ano | find <port#>`

For example, for mine:
![image](https://user-images.githubusercontent.com/25366909/32754316-47b3413c-c89e-11e7-96c2-c25368f10bd5.png)

![image](https://user-images.githubusercontent.com/25366909/32754345-566bdf68-c89e-11e7-9cf1-23a738f64e3d.png)

**Comment by natethegreat418** [comment]
Hey all,

Thanks for the guidance.

@susanBuck,
Contents of c:\xampp\phpMyAdmin\config.inc.php below.
Return from the debug route (added to the Foobooks project i had laying around):
array:3 [▼
  "Environment" => "local"
  "Database defaultStringLength" => 255
  "Database connection test" => "FAILED: SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: SHOW DATABASES;)"
]

@ysrinu, I have attempted through Chrome (localhost/phpMyAdmin) as well as through the XAMPP application.  Running that test yields the below results:
C:\Users\Nathan Marcus
$ netstat -ano | find "4628"
find: 4628: No such file or directory



**c:\xampp\phpMyAdmin\config.inc.php**

```

<?php
/*
 * This is needed for cookie based authentication to encrypt password in
 * cookie
 */
$cfg['blowfish_secret'] = 'xampp'; /* YOU SHOULD CHANGE THIS FOR A MORE SECURE COOKIE AUTH! */

/*
 * Servers configuration
 */
$i = 0;

/*
 * First server
 */
$i++;

/* Authentication type and info */
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Lang'] = '';

/* Bind to the localhost ipv4 address and tcp */
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['connect_type'] = 'tcp';

/* User for advanced features */
$cfg['Servers'][$i]['controluser'] = 'pma';
$cfg['Servers'][$i]['controlpass'] = '';

/* Advanced phpMyAdmin features */
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';

/*
 * End of servers configuration
 */

?>


```

**Comment by natethegreat418** [comment]
Hey all,

Just realized that I have MySQL installed and that it was running in the background (even though it didnt appear in the CurrPorts list...). So I uninstalled that changed the ports back to 3306 in the my.ini file. That appears to have removed the PMA permission issues I was seeing (above). I still have the root access denied errors.

Maybe that helps. Or I just screwed it up more :D 

-NM

**Comment by susanBuck** [comment]
From your debug route I see `Access denied for user 'homestead'@'localhost'`
This means the app you tested this in is still trying to connect with the default username Laravel uses for databases which is `homestead`. This needs to be updated to `root`.

**Comment by natethegreat418** [comment]
@susanBuck ,

Thanks for pointing that out! I just changed my .env file without my test application (foobooks) to the below:
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=root
DB_USERNAME=root
DB_PASSWORD=

When running the debug route I am still getting:
array:3 [▼
  "Environment" => "local"
  "Database defaultStringLength" => 255
  "Database connection test" => "FAILED: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) (SQL: SHOW DATABASES;)"
]

Thoughts? Thanks for all the help.

**Comment by susanBuck** [comment]
@natethegreat418 - I just re-read through the posts above and wanted to summarize where we're at:

* MySQL wouldn't start via XAMPP, changed to port `8889` in `my.ini` to fix
* Changed settings via XAMPP -> Apache, phpMyAdmin (`config.inc.php`) (Not sure what settings were changed?)
* Had separate install of MySQL running; stopped that; switched XAMPP MySQL port back to `3306`; still getting `root access denied errors`

Because you've made some config changes, I think it might be helpful to start at square one to make sure we're on the same page. 

To do this, I've sharing copies of my working/non-modified XAMPP config files here:

1. [`C:\xampp\mysql\bin\my.ini`](https://gist.github.com/susanBuck/52f8a8508d94834332b1d565fb3a0e00)
2. [`C:\xampp\phpMyAdmin\config.inc.php`](https://gist.github.com/susanBuck/b58de59b0dacebebd72e0ba71652ecdf)

Take the contents of these files and replace them with the contents of your files. 

When doing this, please navigate to the exact directories I specified and open the files from there to make your edits- don't get to them via the XAMPP interface. (I know it's the same, I just want to be 100% sure we're editing the correct files).

After you sync up your copies of these files...
1. Exit out of XAMPP completely.
2. Re-open XAMPP and start Apache/MySQL
3. Report back if that progresses the situation at all. : )

Also let me know if there are any other config files you've modified that I should provide copies of.

If the above doesn't produce any helpful results - any chance you're free during [office hours](https://dwa15.com/office-hours) tomorrow (Thu) ? This is one of those problems that can be easier to troubleshoot in "real time"

**Comment by natethegreat418** [comment]
Hey @susanBuck ,

Thanks for the further instruction. Unfortunately that still doesn't remedy the situation. I have the below errors returned. When are the next office hours when we can connect? 

-NM
![image](https://user-images.githubusercontent.com/17519260/32983820-012b069a-cc69-11e7-9970-052859bf5ae8.png)

**Comment by ysrinu** [comment]
@natethegreat418 is your DB_DATABASE value correct? Do you have a database schema with name 'root'?

**Comment by susanBuck** [comment]
@natethegreat418 See the office hour schedule linked in my last post. Next office hours is this evening (Mon Nov 20) 5:30-7:30pm Eastern.

@ysrinu's note above is correct in that the DB_DATABASE should be not `root`. That's the username, not the database name. Regardless, though, that would not explain why phpMyAdmin is unable to connect.

**Comment by susanBuck** [comment]
Update: After troubleshooting with @natethegreat418 we found out the `root` password had been changed. We also worked through how to reset it. The following are the steps we took:

**Comment by ysrinu** [comment]
@natethegreat418 @susanBuck 
This a great debugging scenario and thanks for providing the fix steps. This is a good example how things will not (and almost never) go smoothly all the time in real production env and that's how we learn by actually finding the root cause and fix it.
