### ISSUE TITLE
System Restart

### ISSUE THREAD

**Issue by gnodar01** [susanBuck/dwa15-fall2017#146]
When doing an ssh into Digital Ocean we receive this message

```
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64)

... stuff ...

86 packages can be updated.
0 updates are security updates.


*** System restart required ***

... more stuff ...
```

Should we do a system restart, and if so how?

**Comment by gabrielsanna** [comment]
This means your droplet has automatically installed OS updates that require
a reboot.

To install the rest of the updates and reboot the machine, you can run the
following commands, in order:

`sudo apt update` This will update your software repository so you're
getting the most recent version
`sudo apt upgrade` This will install all those pending updates
`sudo apt autoremove` This will remove any packages that aren't needed
anymore
`sudo reboot` This will immediately reboot that droplet. It will kick you
off the ssh session, but you'll be able to reconnect in a minute.
