### ISSUE TITLE
Problem: Git Clone Foobooks from Github to Local

### ISSUE THREAD

**Issue by EricXDing** [susanBuck/dwa15-fall2017#148]
Hi all! 

So I am trying to git clone Susan's foobooks into my local computer to dissect the code; but when I try to access localhost/foobooks/public, this message came out

> Fatal error: Uncaught ReflectionException: Class App\Http\Kernel does not exist in C:\xampp\htdocs\foobooks\vendor\laravel\framework\src\Illuminate\Container\Container.php:752 Stack trace: #0 C:\xampp\htdocs\foobooks\vendor\laravel\framework\src\Illuminate\Container\Container.php(752): ReflectionClass->__construct('App\\Http\\Kernel') #1 C:\xampp\htdocs\foobooks\vendor\laravel\framework\src\Illuminate\Container\Container.php(631): Illuminate\Container\Container->build('App\\Http\\Kernel') #2 C:\xampp\htdocs\foobooks\vendor\laravel\framework\src\Illuminate\Container\Container.php(586): Illuminate\Container\Container->resolve('App\\Http\\Kernel', Array) #3 C:\xampp\htdocs\foobooks\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(721): Illuminate\Container\Container->make('App\\Http\\Kernel', Array) #4 C:\xampp\htdocs\foobooks\vendor\laravel\framework\src\Illuminate\Container\Container.php(256): Illuminate\Foundation\Application->make('App\\Http\\Kernel', Array) #5 C:\xampp\htdocs\foobooks\vendor\laravel\fr in C:\xampp\htdocs\foobooks\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 752

I think it is because I didn't do certain configuration. I am new to git; what configuration do I need to do when directly cloning another laravel project to my local drive? 

Thank you!

**Comment by gregorycoleman** [comment]
@EricXDing  Bear with me, what happens when you do a `composer install` ?

**Comment by EricXDing** [comment]
Oh, it worked! 
Thanks so much Greg! I ran composer install and everything worked out!
