### ISSUE TITLE
migrate command error

### ISSUE THREAD

**Issue by asmatmuradi** [susanBuck/dwa15-fall2017#151]
I'm getting the following error while running the migrate command. 

`Asmat$ php artisan migrate

                                                                                                                     
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                                            
  Parse error: syntax error, unexpected '>', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'  
                                                                                                                     `
When I run the localhost in debug mode it shows passed but it fails when I run the migration. Did anyone face this issue?

**Comment by ysrinu** [comment]
@asmatmuradi Did you mean it fails in 'production'?

**Comment by asmatmuradi** [comment]
@ysrinu thanks for asking, I had an extra '>' in one of my migration files. Got it resolved. I was not able to see the full description of the issue initially but the following command helped me to get the full description. 

`php artisan migrate --verbose`
