### ISSUE TITLE
No warning on production when running migrate or seed

### ISSUE THREAD

**Issue by rrtx2000** [susanBuck/dwa15-fall2017#152]
On Digitalocean, I ran `php artisan migrate` and `php artisan db:seed` and neither gave the "Application in Production, are you sure? [y/N]" warning.
It ran fine though. I'm just curious, did anybody else not get the warning?

**Comment by gregorycoleman** [comment]
@rrtx2000 Everyone gets that message if they are running artisan in production environment.  The warning there for your protection. It is to stop you from making a fat fingered error.  Like running a `php artisan migrate:fresh` that would wipe out the database on a production server.

**Comment by ysrinu** [comment]
@rrtx2000 do you have 'production' name in your env file (APP_ENV)? I am not sure if php will depend on this user configurable value in the env file to throw warnings. It might be a good idea to double check though.

**Comment by susanBuck** [comment]
Echo'ing @ysrinu - Confirm the DigitalOcean copy of your project has its environment set to `production`. If it's not, you won't see the warnings. 

To confirm, run the [debug route](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/24_Local_database_config.md#test-your-connection) I provided, as the first bit of data it dumps out is what your environment is set to.

**Comment by rrtx2000** [comment]
"production" fixed it. Thanks.

**Comment by tericson1** [comment]
Hi - I ran into this as well. It looked like everything had worked fine prior to fixing to add "production", i.e. i could see my tables and run queries off of them. after updating - do I need to re-migrate my tables and re-seed?

**Comment by susanBuck** [comment]
@tericson1 No need to re-migrate/re-seed (assuming there have been no changes to migrations/seeds). They run the same regardless of whether env is production or local, it's just whether it displays the warning message that is different.
