### ISSUE TITLE
Atom and Auto Indent

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#153]
Is there a way we check our code to see if we inadvertently used a tab in place of spaces?

When using Atom ```Edit->Lines->Auto Indent``` ....
Will this clear out  inadvertent tabs? 
Will this have any effect on indentions and result in  PSR-1/PSR-2 style divergence?

**Comment by susanBuck** [comment]
*Atom > Preferences > Editor > Show Invisibles*

Then you'll see tabs/spaces like so:
<img width="456" alt="2017-11-17_1250" src="https://user-images.githubusercontent.com/237711/32961267-e84db43e-cb95-11e7-91a3-3708be82f0e9.png">

Auto-indent works according to your indentation settings...

For example, in my Atom preferences I have *Soft Tabs* enabled and my *Tab Length* is set to 4 spaces. 

This allows me to have the convenience of indenting by just hitting the tab key, while the indentation will actually be 4 spaces (PSR-compliant)

**Comment by dukesnuz** [comment]
Got it ! Thank you
