### ISSUE TITLE
Week 12 due date

### ISSUE THREAD

**Issue by gvardany** [susanBuck/dwa15-fall2017#155]
Could you please confirm that for week 12 the early submission (full credit) is until 29 Nov?

**Comment by gregorycoleman** [comment]
![week12 dwe15](https://user-images.githubusercontent.com/10154076/33011342-565054d2-cda3-11e7-8036-058b371704aa.png)

**Comment by susanBuck** [comment]
Confirmed.

+ [As noted on schedule](https://screencast.com/t/jT3tJFKR)
+ [As noted on the Week 12 outline](https://screencast.com/t/vBdvAyAGMx) and discussed in the [Week 12, Part 1 video](https://www.youtube.com/embed/_Cxt7yGVRi0?rel=0&showinfo=0)
+ And, as @gregorycoleman indicated, in Canvas.
