### ISSUE TITLE
How can I safely embed a youtube video

### ISSUE THREAD

**Issue by ruthnphillips** [susanBuck/dwa15-fall2017#158]
My form allows users to embed Youtube videos by providing the link. For instance 
`$video_link = <iframe width="560" height="315" src="https://www.youtube.com/embed/rAlE2EnUP5A" frameborder="0" allowfullscreen></iframe>`

Unfortunately, when i try to display the video using `{{ $video_link' }}` it only displays the code instead of the embedded video. I'm assuming this is because it is escaping the HTML entities. When I use  
`{!! $video['video_link'] !!}`  I am able to see the embedded video. 

Is there a way to safely embed the video, and not leave my application to attacks.

**Comment by susanBuck** [comment]
You want to separate the video link from the embed code.

For example, assuming `$video['video_link']` is set to `https://www.youtube.com/embed/rAlE2EnUP5A` then you could do this:

```php
<iframe width="560" height="315" src="{!! $video['video_link'] !!}" frameborder="0" allowfullscreen></iframe>
```

**Comment by ruthnphillips** [comment]
Thanks!, I believe you meant: 
`<iframe width="560" height="315" src="**{{ $video['video_link'] }}**" frameborder="0" allowfullscreen></iframe>`

**Comment by susanBuck** [comment]
You're right, I did! : )
