### ISSUE TITLE
Table joins

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#159]
I know this will be covered in next lectures. This would help me now though for my database model.

In our foobooks example, let's say instead of books.author column we have author_id that points to authors.id column. (`books.author_id` : `authors.id` is many-to-one)

If I use
```
# Get all rows
$result = Book::all();
```
It will return `author_id`. I, however, want to show author name (from authors table) in place of author_id

I can write [raw query](https://laravel.com/docs/5.5/queries#raw-expressions) to join books and authors tables, but want to avoid that.
I can create database view that does the join and have a `BookView` model created for this (only for select, not update/delete), but don't want to create view on database either (because in most organisations creating views is not allowed for simple joins, and instead should be handled by the application code).

https://laravel.com/docs/5.5/queries#joins
shows how to do table joins and uses DB facade.

Q1. Is there Eloquent way of joining tables?
Or should I wait until the below is covered in our lectures?
https://laravel.com/docs/5.5/eloquent-relationships

Q2. Let's say we figure out join somehow and show the author name when displaying books records. Now, when I want to modify, I should be able to have drop-down for author input field so it displays all possible author names (from authors) in viewable list and with submit value referencing the authors.id.
Is there an easy way in Laravel to return a book record, but also with a list of all possible values for each foreign key referenced columns?

Thanks,
-Sri

**Comment by susanBuck** [comment]
Yes, Eloquent has many methods for working with table relationships. It's one of the things that makes a ORM like Eloquent nice to use. 

Here's some snippets of what's coming up in Week 13:

**Comment by ysrinu** [comment]
Thanks @susanBuck 
I just found out that we can use [pluck](https://laravel.com/docs/5.5/collections#method-pluck) instead of foreach loop since $authors is a collection object
(ignoring first_name for simplicity here):
```
# Get all the authors
$authors = Author::orderBy('last_name', 'ASC')->get();

# Organize the authors into an array where the key = author id and value = author name
$authorsForDropdown = $authors->pluck('last_name','id');
$authorsForDropdown->all();
```
Note, pluck replaces the deprecated lists method. 'lists' was deprecated in Laravel 5.2 and removed in 5.3
https://laravel.com/docs/5.3/upgrade

From pluck documentation
https://laravel.com/docs/5.5/collections#method-pluck

I don't understand why we have to run both these commands in sequence, the output is same for each of these
```
$plucked = $collection->pluck('name', 'product_id');
$plucked->all()
```

On a related  note, I also found by testing myself that if we use a single key, say 'name', it will use self-generated keys starting with 0 (this is not related to any value in the collection):
`$groups = Group::orderBy('description', 'ASC')->get();`
![image](https://user-images.githubusercontent.com/25366909/33304251-b8109c26-d3d5-11e7-9329-d04a0ec6fd66.png)


This can be demonstrated by passing the primary key itself, the left-side is the self-generated value (starting with index 0), the right side is the 'id' value from the collection
`$groupsForDropDown = $groups->pluck('id');`
![image](https://user-images.githubusercontent.com/25366909/33304274-d43f2ea8-d3d5-11e7-99f9-35346373e451.png)

Let's make the 'id' as the index key and 'description' as value
```
$groups = Group::orderBy('description', 'ASC')->get();
$groupsForDropDown = $groups->pluck('description','id');
```
![image](https://user-images.githubusercontent.com/25366909/33304432-c8e620ce-d3d6-11e7-836a-1a83818c566f.png)

It looks like pluck doesn't honor the order in the collection. We have the collection created with ascending order of 'description' but it's ordered different in the pluck output.

Thanks,
-Sri

**Comment by susanBuck** [comment]
Thanks for the extra details posted above, Sri. 
I believe your original question is answered now? Closing this out, but feel free to start a new thread if you still have pending questions.
