### ISSUE TITLE
Primary Keys in a URL

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#160]
Is it safe to have a Primary key in a url? 
or
Should there be a random unique number stored in each column and this used in the url?
or
Should HASH be used on the primary key or another column?
or
Any of the above?

**Comment by susanBuck** [comment]
Assuming you're following good security practices, I don't see it as being problematic.
Presumably a visitor should not be allowed to do anything they're not authorized to do, even if they know the primary key of some entity in your database. 

It's common to see ids in the urls for things like forum posts, blog posts, e-commerce items, etc.

That being said, I __would__ avoid it for things like user ids or other sensitive data. There's no reason to make that obviously public. Better safe than sorry.

Also - when possible - it's better to use a more more "human friendly" (yet still unique) identifier in your URLs. Doing so provides context about the URL and is better for search engine optimization.

We're using ids in Foobooks to avoid the issue of multiple books with the same titles. For comparison, here's how a site like goodreads handles that:
```
https://www.goodreads.com/book/show/43641.Water_for_Elephants
```

It appears to be both a numeric identifier (presumably the primary key?) and the title of the book.

Similar approach at StackOverflow:
```
https://stackoverflow.com/questions/47424632/bootstrap-affix-with-jquery-computed-height
```
That also appears to be a numeric identifier, followed by the post title.

Here's an interesting read on the topic:
<https://stackoverflow.com/questions/566996/using-primary-key-id-field-as-an-identifier-in-a-url>

**Comment by dukesnuz** [comment]
Great. Thanks much, very helpful.
