### ISSUE TITLE
Eloquent: What would be the expected/default table name for a model named Mouse?

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2017#162]
Quick FYI regarding singular/plural word choice for tables and models:

When introducing Eloquent, we talked about the following convention:

+ Table names are lowercase, plural, e.g. `books`
+ Corresponding model names are UpperCamelCase, singular, e.g. `Book`

But what if you have a word that's not easily pluralized by dropping the s?
For example, the plural of `Mouse` is not `mouses`, it's `mice`.

Turns out Eloquent is programmed to handle these kind of edge cases.

You can test this out using the [`str_plural`](https://laravel.com/docs/5.5/helpers#method-str-plural) and [`str_singular`](https://laravel.com/docs/5.5/helpers#method-str-singular) helper methods if you're ever unsure what Eloquent's default expectations are when making this translation.

```
/Applications/MAMP/htdocs/foobooks $ php artisan tinker
Psy Shell v0.8.13 (PHP 7.1.6 — cli) by Justin Hileman
>>> str_plural('mouse');
=> "mice"
>>> str_singular('mice');
=> "mouse"
```

**Comment by ysrinu** [comment]
This is nice. I just checked this works for my case too
```
>>> str_plural('warranty');
=> "warranties"
```

Last week I used the below code (since I didn't knew Eloquent handled plural case) to tell Warranty model to use warranties table, by explicitly mentioning the table name in the class definition
class Warranty extends Model
```
class Warranty extends Model
{
    protected $table = 'warranties';
}
```

**Comment by susanBuck** [comment]
@ysrinu's point is a useful one: pretty much any convention that Laravel/Eloquent enforces can be overridden if necessary. This can be useful in order to accommodate legacy applications, strong preference for existing conventions, integration with other apps/databases, etc.

When starting with new/isolated apps I recommend sticking with conventions for consistency, but it's nice to have the flexibility if needed.

**Comment by SridharSubramaniam** [comment]
Thanks for the tip @ysrinu
