### ISSUE TITLE
record set, display sub list - fetching data from related tables

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#166]
Consider the code:
```
$result = Asset::find($id);

dump($result);
dump($result->assetrepairs);
````
When I look at the output, why can't I find assetrepairs data in the dump($result) output?
I would think that within dump($result) I should be able to navigate and find the assetrepairs data.

I also noticed that the query for assetrepairs table doesn't run for `$result`, but only for `$result->assetrepairs.`

I was assuming that $result will hold all info of Asset including it's joined tables, and we can fetch the joined table data from $result without doing a second trip to the database.

It look like even after that the below statement is executed:
`$result = Asset::find($id);`

if we run the code:
`$result->assetrepairs`

then it goes out and queries the database for the joined table. In other words $result is not a standalone data in our application server memory, but has a pointer still mapped out to the assets table via Asset model. Am I interpretation correct?

It doesn't stop here. I noticed that the $result passed as parameter to the blade view, in the view we call $result->assetrepairs (and not called ahead) then it still goes for the joined table query.
So it sounds like the $result holds the pointer to the database table even passed around between the controller and views. Is the $result parameter passed by reference?

Another observation:
If run dump($result) after dump($result->assetrepairs), then it shows assetrepairs data as part of $result
```
dump($result) # Only asset data, No assetrepairs data
dump($result->assetrepairs # runs a query and only displays assetrepairs data
dump($result) # now has both asset and assetrepairs data
```
Note the 'relations' attribute value in the screenshot below, the 1st and 3rd columns
![image](https://user-images.githubusercontent.com/25366909/33235108-ac297d56-d1ff-11e7-876c-8bcfc24aad89.png)

![image](https://user-images.githubusercontent.com/25366909/33231418-36655374-d1c3-11e7-9a81-f02e09fd5624.png)

![image](https://user-images.githubusercontent.com/25366909/33231421-4248732e-d1c3-11e7-8b48-522d1d82a88a.png)

**Comment by susanBuck** [comment]
```php
$result = Asset::find($id);
dump($result);
dump($result->assetrepairs);
```
>> When I look at the output, why can't I find assetrepairs data in the dump($result) output?

When you do `Asset::find($id)` it will *not* query any table relationships associated with this asset. This is to optimize the query - there's no sense getting the table relations if we don't need them.

>> I was assuming that $result will hold all info of Asset including it's joined tables, and we can fetch the joined table data from $result without doing a second trip to the database.

This assumption is incorrect. If you want it to grab the joined table data, you'll want to use a feature called [eager loading](https://laravel.com/docs/5.5/eloquent-relationships#eager-loading). You do this when you know you're going to need that joined table data.

As for why `dump($result->assetrepairs);` *does* have the data, even without eager loading: It's a dynamic property - meaning it's dynamically loaded when requested. This does result in an extra query, which is why eager loading is helpful.

[From the docs:](https://laravel.com/docs/5.5/eloquent-relationships#relationship-methods-vs-dynamic-properties)

>> Dynamic properties are "lazy loading", meaning they will only load their relationship data when you actually access them. Because of this, developers often use eager loading to pre-load relationships they know will be accessed after loading the model. Eager loading provides a significant reduction in SQL queries that must be executed to load a model's relations.

**Comment by ysrinu** [comment]
Thanks @susanBuck for pointing out the 'eager' and 'lazy' loading. The keywords were enough to get an idea why we have them and what they do. The documents in the links are very helpful.
Lazy loading is good to save resources and quick retrieval where relations are not needed. Each type of loading has it's business use case and should be used wisely.
Thanks again!

**Comment by susanBuck** [comment]
np!
