### ISSUE TITLE
Old Helper 

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#167]
### Scenario
1. Using ```value={{ old('firstName) }}``` in a form,
2. The field contain 2 words ie John Paul

### Issue
Upon page refresh the Paul clears leaving only John in the field.

### Question
Is there a way to also save the other  words that may be in the field?

**Comment by dukesnuz** [comment]
I just figured it out ```value={{ old('firstName) }}``` should be ```value='{{ old('firstName) }}'```

**Comment by ysrinu** [comment]
@dukesnuz you missed the closing single quote around firstName too :-)

**Comment by dukesnuz** [comment]
@ysrinu Good catch, Thank you
