### ISSUE TITLE
Not Sure Where This File Came From  hrsobaepp

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#170]
A few days ago a new file appeared in my p4 folder, not sure where it came from or what it is for.
I believe it may have appeared around the time I installed a package. The code in the file does not  have any reference to the package, as it looks like a blade file.  Just wondering if anyone has more insight into this file. I would like to delete it if not needed.

Here is the code in the file:
 File name ```hrsobaepp```
```
[1mdiff --git a/resources/views/layouts/master-admin.blade.php b/resources/views/layouts/master-admin.blade.php[m
[1mindex 3e3c124..dd3fb98 100644[m
[1m--- a/resources/views/layouts/master-admin.blade.php[m
[1m+++ b/resources/views/layouts/master-admin.blade.php[m
[36m@@ -23,7 +23,6 @@[m
     	<p>{{ session('sessionMessage') }}</p>[m
 	</div>[m
 	@yield('content')[m
[31m-[m
 	@stack('body')[m
 </body>[m
 </html>[m
```

**Comment by susanBuck** [comment]
The contents of that file look like the output of a `git diff`. It's outlining changes made to `master-admin.blade.php`. 

It is possible to save the results of a `git diff` command to a file, e.g.:

```
git diff example.php > differences.txt
```

Any chance that might have happened?

Where in your app did the file appear - at the root?

**Comment by dukesnuz** [comment]
Good to know about ```git diff example.php > differences.txt```

File is next file after ```composer.lock```

> Any chance that might have happened?
I occasionally  use ```git diff```.   As a result,  Extremely likely this was created by the user's typing error. 

Deleting it now.

**Comment by dukesnuz** [comment]
Just tried this ```git diff example.php > differences.txt```
Very cool
