### ISSUE TITLE
Why is DB_HOST set to localhost? (+bonus tip about DB management apps)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2017#172]
A classmate (hat tip Chen Z.) asked an interesting question in their Week 11 progress log, and I wanted to share the answer with everyone.

Question: 
> How come our `DB_HOST` on DigitalOcean is set to `127.0.0.1` and not the actual IP address of the server?

On DigitalOcean, your `DB_HOST` can either be `localhost` (just like it was on your local servers) or `127.0.0.1`.  In computer networking, `localhost` is a hostname that means *this* computer (or server).  `127.0.0.1` is the reserved IP address that `localhost` typically resolves to (which is why either one works).  

Some services, such as MySQL, are only configured to work when they're accessed locally - e.g., from a PHP script on the same server in which MySQL is running.  This is for security purposes - unless configured, you don't want external apps/scripts to be able to connect to your MySQL. 

__By configuring MySQL to only accept localhost addresses (127.0.0.1) and not your server's real IP address, DigitalOcean is reducing the chance of your MySQL database being compromised by some outside server/hacker.__

***

Sometimes, though, you do want to be able to connect to your database from an external server. 

For example, if you're using a database management application on your computer like [SequelPro](http://www.sequelpro.com/) (Mac) or [HeidiSQL](http://www.heidisql.com/) (PC), you'd like to be able to connect and manage your DigitalOcean database from your computer. (These apps were mentioned in passing in the [Database primer notes](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/22_Database_Primer.md#phpmyadmin)).

To accommodate this, you can configure MySQL to accept connections from external servers.

Rather than opening up to any connection, though, it's best to use a "whitelist" of IP addresses that you trust. The downside of this, though, is our internet providers often use dynamic IP addresses, so it's possible to have a different IP address each time you connect to the internet. 
This means whenever you want to use your DB application, you have to update your server's "whitelist" with your new IP address.

Because of this hassle, the better solution is to __connect to your MySQL database via SSH.__

The following screenshot show an example of how you could connect to a DigitalOcean MySQL database using SequelPro:

<img width="1563" alt="sequel-pro" src="https://user-images.githubusercontent.com/237711/33350135-3fae255a-d46b-11e7-8ce0-6b7dc4c0a7dc.png">

Once you're connected, then you can view your database on the server, browse the tables, etc. Essentially, this is an alternative to phpMyAdmin.

<img width="966" alt="sequel-pro2" src="https://user-images.githubusercontent.com/237711/33350178-752525d0-d46b-11e7-98e2-0ce942720e46.png">

Of course, apps like SequelPro and HeidiSQL can also be used to manage your local databases.

**Comment by susanBuck** [comment]
Follow-up: Out of curiosity, I tried to connect with HeidiSQL as well. It was a little more involved, so I wanted to share my notes in case any PC users wanted to try a DB management app.

<img width="1266" alt="heidisql-instructions" src="https://user-images.githubusercontent.com/237711/33353726-36082f34-d47d-11e7-8fc2-d9dc68c1a341.png">

**Comment by ysrinu** [comment]
127.0.0.1 is **loopback** address commonly used for 'localhost'. This prevents the localhost being accessed from non-local request origins.

http://www.tech-faq.com/127-0-0-1.html
