### ISSUE TITLE
TDD, BDD and unit testing - Laravel/PHP

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#174]
Is it possible to cover topics:

- Unit Testing in Laravel/PHP, 
- build Laravel/PHP code using TDD and BDD software development techniques (used in Agile/Scrum projects)? 

Unit testing
PHPUnit is included out of the box with Laravel
https://laravel.com/docs/5.5/testing

BDD
Behat http://behat.org/en/latest/quick_start.html

TDD
https://medium.com/@jsdecena/simple-tdd-in-laravel-with-11-steps-c475f8b1b214
https://code.tutsplus.com/tutorials/test-driven-development-with-laravel-doctrine--cms-25563
https://adamwathan.me/test-driven-laravel/

Thanks,
-Sri

**Comment by susanBuck** [comment]
These are large topics, and not within the designed scope of this course. If one day there were ever a "Dynamic Web Apps Part 2" course, these topics would be covered (amongst many other good stuff we don't have the time to get to!)

Sorry to not have better news about this. You've provided lots of great resources though, and hopefully your experience working with the Laravel docs this semester has given you at least some of the skills necessary to dig into these concepts independently.

**Comment by ysrinu** [comment]
@susanBuck 'Dynamic Web Apps Part II' would be nice :-)

**Comment by HeinrichTremblay** [comment]
Also this book [https://leanpub.com/laravel-testing-decoded](https://leanpub.com/laravel-testing-decoded)

**Comment by susanBuck** [comment]
See #198 for a *tiny* bit of discussion on unit testing.
