### ISSUE TITLE
Source code for Foobooks?

### ISSUE THREAD

**Issue by natethegreat418** [susanBuck/dwa15-fall2017#175]
Hey @susanBuck ,

For those of us that haven't been keeping 100% pace with foobooks development in local environments, it would be really helpful when creating this 'delete' to have access to the latest foobooks source.  I don't see that anywhere on your github.

My concern is that otherwise, adding a simple delete method to the controller will take a lot of templating/UI work to accomplish.  Let me know if I am missing something or if that was the point of the exercise.

-Nate #

**Comment by susanBuck** [comment]
Designing the delete functionality for Foobooks was part of your "to-dos" for the Week 12 progress log, which isn't due until tonight at midnight. Because of this, I have not yet pushed my solution to the Foobooks code base. I will after the due date passes though.

**Comment by ysrinu** [comment]
@susanBuck I didn't use the practice foobooks app, but included 'delete' as part of my p4 and it's working.
Is it okay if I answer week12 with p4 application delete functionality instead?
Thanks

**Comment by susanBuck** [comment]
@ysrinu No, it's expected that you answered the question relevant to Foobooks - the instructions stated this. 

Another student asked a similar question and I explained why I set up the task this way. See: #156.

The point deduction will be minimal, compared to if you didn't answer the task at all, or answered it incorrectly, but there will still be a deduction.

**Comment by ysrinu** [comment]
I missed reading the already provided post and I am glad I asked.
Will follow as per instructed in the progress log.
Thank you

**Comment by stbenjam** [comment]
@natethegreat418 Were you just looking for the Foobooks source without the delete functionality? That's all in https://github.com/susanbuck/foobooks.

**Comment by susanBuck** [comment]
D'oh - Reading @stbenjam's post I realize I may have misinterpreted @natethegreat418's original question. Given this, I'll revert this topic title back to its original title.

I think I assumed that by the end of the semester everyone knew where the foobooks source code was. :-)
