### ISSUE TITLE
One thing I found interesting: Eloquent recognizes irregular plural nouns

### ISSUE THREAD

**Issue by EricXDing** [susanBuck/dwa15-fall2017#176]
Just wish to quickly share with everyone, 

So, I knew that Eloquent automatically look for table with name 'tablename+s' (lower case plural) using the model's name ('Tablename': uppercase singular) in the database. When I was creating a table, I named my table 'persons', hoping that when I create a model named 'Person', Eloquent will be able to find it for me. 

To my surprise, Eloquent was actually looking for a table named 'people'! I just find this fascinating; it looks like Eloquent recognizes irregular plural nouns!

**Comment by ysrinu** [comment]
@EricXDing 
This was covered in
https://github.com/susanBuck/dwa15-fall2017/issues/162

**Comment by susanBuck** [comment]
Oops on the duplicate post. But, still cool that you stumbled on this via trial and error.  : )
