### ISSUE TITLE
Many To Many Join table not seeding

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#177]
When I try to seed the join table, for my many-to-many relation, I get the following exception.

```
[ReflectionException]
  Class PostTagTableSeeder does not exist
```
My models have been updated to include the relation, and I followed the naming convention specified in the lecture. My migrations follow the naming convention specfied in class.

Any idea why I'm getting this error? Everything looks fine to me

**Comment by ysrinu** [comment]
Can you try this:
https://github.com/susanBuck/dwa15-fall2017/issues/150

**Comment by APuente21** [comment]
Yes, this fixed it. Thanks a lot!
