### ISSUE TITLE
CSS Drop Down Menu

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#178]
Here is a simple css [drop down](https://codepen.io/dukesnuz/pen/KyGYgJ) menu.

**Comment by gregorycoleman** [comment]
If you are using Bootstrap, Dropdowns are a component. <https://getbootstrap.com/docs/3.3/components/#dropdowns>

**Comment by ysrinu** [comment]
https://github.com/susanBuck/dwa15-fall2017/issues/179#issuecomment-348711012

**Comment by natethegreat418** [comment]
Howdy, Not sure how much interest folks have in the UX piece of web development, but the Norman Nielsen Group has great research on when and how to employ these design elements in your work: https://www.nngroup.com/articles/drop-down-menus/

**Comment by kunista** [comment]
Thank you David, this is exactly what I was looking for.
