### ISSUE TITLE
Helper for UI pickers/dropdowns/etc

### ISSUE THREAD

**Issue by zeroender** [susanBuck/dwa15-fall2017#179]
For anyone looking for a good/fast solution to add various other input fields, such as datepickers, and other visual effects, I've found that Jquery UI (https://stackoverflow.com/questions/1328025/jquery-ui-datepicker-change-date-format) was very helpful.  I came across this while looking for a reasonably simple way to add a date picker that didn't involve installing another package or framework.

**Comment by ysrinu** [comment]
I am using bootstrap 4 (beta) throughout my application. This gives me a consistent and uniform theme across all my controls.

https://getbootstrap.com/
https://v4-alpha.getbootstrap.com/

**Comment by atanasgizdov** [comment]
Also try https://jsfiddle.net/ for an easy way to test and update isolated elements without having to re-load your application or clear cache

**Comment by davida26** [comment]
I also like to use https://codepen.io/ to test front-end snippets/ideas/designs quickly. 

Once I am happy, I bring it over to my app. You can also search for cool ideas/inspiration there including CSS dropdowns.

**Comment by z14165899** [comment]
I think that date picker can be achieved using HTML date input type. In addition to the previous two replies, there is a [very useful Chrome extension](https://webmakerapp.com/) that you can try, and I really like it.

**Comment by stbenjam** [comment]
`<input type="date">` isn't supported everywhere yet though.  Safari still lacks it, and Firefox only recently got it with Quantum.  For our purposes though it's probably fine though.
