### ISSUE TITLE
Is This Link Correct?

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#180]
@susanBuck 

In [Lecture notes](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/32_Relationships_One_to_Many.md#read-querying-with-relationships)
Is this link correct?   [dynamic properties](https://laravel.com/docs/5.5/eloquent#dynamic-properties)

Update:
This link also? [Eager Loading](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/32_Relationships_One_to_Many.md#eager-loading)
[with() method](http://devdocs.io/laravel/api/4.2/illuminate/database/eloquent/model#method_with)

**Comment by susanBuck** [comment]
Nope, they weren't. Just fixed.
