### ISSUE TITLE
Sending POST through a link? 

### ISSUE THREAD

**Issue by EricXDing** [susanBuck/dwa15-fall2017#181]
Regarding foobooks delete function, in the lecture video, Susan used a form button, passed a POST, and then changed it to DELETE to the route.

However,  instead of using a form button, I want to pass the delete request through a link. 

ie: <a href="/{id}/delete">delete</a>

However, with a link, I don’t know how to pass POST. Currently, I am just using GET method for deleting; I know this is not a secure way to do it; I wonder what can I do? I know there are many solutions on the internet but I hope to hear your thoughts!

**Comment by susanBuck** [comment]
Here's an example of how to do that:
```php
<form method='POST' id='logout' action='/logout'>
    {{ csrf_field() }}
    <a href='#' onClick='document.getElementById("logout").submit();'>Logout</a>
</form>
```
(In the interest of simplicity, this code uses some inline JavaScript to submit the form via a link. Ideally, you should move this inline JavaScript to an external JS file.)

(Borrowed from: [Authentication: Logout](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/34_Authentication_setup.md#log-out))
