### ISSUE TITLE
Default dropdown menu selection

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#182]
In the lecture
https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/99_Foobooks_Lecture_13a.md#custom-model-methods

We see how to add a default option 'choose one ...'
and then validate that this option was submitted (if this is a required field)

I personally think it's not ideal to add an option 'choose one' to the list and then validate it shouldn't be selected. The list should truly only hold the items it relates to.
Also, in the example we are assuming id of '0' for the default. If the collection from model was retrieved without an index, eloquent [indexes ](https://laravel.com/docs/5.5/collections#method-pluck) the collection starting with index=0 (so the first valid item get this 0 and then thrown off as validation error by our validation logic)

The default option 'choose one' should be in the presentation layer only, as below.
I also made this disabled, which means on 'create' form it will show this option but once your pick an item from the list, you can never go back to this 'choose one' option. This forces the user to submit with some valid selection.
Same is true for 'edit' form. The form will show an existing item as selected but the user can never change it to 'choose one ...'

The diasabled option here has value set to null, so it will not match with indexed (key) column of the list and hence no need for additional validation (beyond the basic existing validation that the author_id is required)

```
<select name="author_id">
    <option value="" selected="selected" disabled="disabled">Please choose one</option>
    @if ($authorsForDropdown->count())
        @foreach($authorsForDropdown as $key => $val)
            <option value="{{ $key }}" {{ $book->author_id == $key ? 'selected="selected"' : '' }}>{{ $val }}</option>
            @endforeach
    @endif
</select>

```
![image](https://user-images.githubusercontent.com/25366909/33521630-9a6f3992-d7a5-11e7-8ae6-07633db6de6c.png)

![image](https://user-images.githubusercontent.com/25366909/33521602-fbde0e3e-d7a4-11e7-85a5-a44a929c545f.png)

**Comment by susanBuck** [comment]
I like your approach. Updated foobooks to reflect this:

https://github.com/susanBuck/foobooks/commit/0fdc96f236f7e09ff990eae5db18d82d6d1cd0ed
