### ISSUE TITLE
Why use DB relationships versus SQL joins?

### ISSUE THREAD

**Issue by dmbartles** [susanBuck/dwa15-fall2017#183]
Hey all,

I have a bit of experience with SQL and am wondering if there are any advantages of using Laravel's DB relationships versus coding a SQL query to join to tables. 

Is Laravel more efficient at using relationships? It seems to me that it is doing the same thing as a join...

Thanks, Matt

**Comment by ysrinu** [comment]
@dmbartles Raw sql works for the most part. However, if the raw sql is not ANSI standard, but proprietary (database vendor specific) then it's likely to fail when you point your application to a different database vendor.
Also note that the Laravel/PHP programmers may not be SQL experts so we have to keep in mind who will be maintaining this application. Eloquent programmers may not find a raw sql very readable and can be difficult for them to modify if they don't understand what the current sql statement means, and the may not know what the new sql statement should look like.

raw sql also takes away the encapsulation that eloquent provides. The migration scripts are also vendor neutral. It's best when we code as per Eloquent and then eloquent takes care of translating to database vendor specific calls.

Use raw sql if you must (where it's a complex join condition not easily translated into eloquent expression).

**Comment by gvardany** [comment]
Without doubts, vanilla SQL is more powerful and gives more degrees of freedom. However, as mentioned in one of the lectures, when the number of related tables grows, the join queries might quickly get cumbersome for a non-expert. Eloquent provides somewhat friendlier interface, and I believe in common cases it also produces the most optimal SQL behind.

**Comment by susanBuck** [comment]
I support all the points made in the student answers above.

Everything can be done with SQL, but Eloquent abstracts this process so your code is more expressive and powerful, allowing you to develop the features of your application quicker.

I can't recall if I said this in the lecture video or not, but consider the tag checkbox features and everything that needs to happen:

+ Of the tags selected, if they were not previously stored, add the connection
+ Of the tags selected, if they were previously stored, do nothing
+ Of the existing connections, if they no longer exist in the tags selected, destroy the connection

When we have models and relationships set up, the above tasks come down to a simple, human-friendly line:
```php
$book->tags()->sync($tags);
```

So you can see it's not just about abstracting the actual SQL, it's also taking care of lots of the work to be done when working with data/relationships. 

Also, as @ysrinu noted, the abstraction Eloquent provides also makes it easy to plug into different database types and have your code still work.

Finally, Eloquent is built to automatically protects against [SQL injection attacks](https://en.wikipedia.org/wiki/SQL_injection).  

The idea with all these features is to make the universal things that every app needs to do just work, allowing you to focus on the business end of *your* application.
