### ISSUE TITLE
Using detach() and Soft Delete

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#185]
### Scenario:  
Using [soft deleting](https://laravel.com/docs/4.2/eloquent#soft-deleting)

### Question:
Is [ ```detach()```](https://laravel.com/docs/5.5/eloquent-relationships#updating-many-to-many-relationships)  needed when using soft delete?

**Comment by ysrinu** [comment]
From my comments in https://github.com/susanBuck/dwa15-fall2017/issues/186
I think soft delete and detach are for different purposes.

Is there a soft-detach?
Are you soft deleting records in the parent tables or the pivot tables?

**Comment by dukesnuz** [comment]
@ysrinu I am soft deleting in parent. RE: foobooks I used soft delete to delete a book.
As for a soft detach I found [cacade soft deletes](https://github.com/michaeldyrynda/laravel-cascade-soft-deletes) 
Also found [Laravel/Lumen 5 Soft Cascade Delete & Restore](https://github.com/Askedio/laravel5-soft-cascade)

I briefly read both

**Comment by ysrinu** [comment]
@dukesnuz Nice find! I didn't use any soft deletes yet.
The links you find are great resources. They are however are add-on and are not supported/built-into Laravel/Eloquent core itself. It comes down to how comfortable you are installing 3rd party addons, how well they are supported and used.

**Comment by dukesnuz** [comment]
@ysrinu soft deleting is real easy with Laravel , try it.

**Comment by susanBuck** [comment]
__Technically, `detatch` is not needed if you're using soft-deletes.__

Here's why:
The error we get when attempting to delete a row that is attached to a foreign table is a SQL specific error. E.g.,:
```
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`foobooks`.`book_tag`, CONSTRAINT `book_tag_book_id_foreign` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`)) (SQL: delete from `books` where `id` = 3)
```

Knowing this, if we make it so the book row in question is not actually deleted (which soft-deletes does), then SQL won't throw an error.

We then have "orphaned" rows in the `book_tag` table.

This is okay if we want to make it so `books` can be "undeleted" and have them maintain their old tag relationships when they are restored.

But if we don't plan on making `books` restorable, then it's best to delete the corresponding rows in the `book_tag` table (i.e. detach) before deleting a book, to avoid cluttering the DB.

So yes, technically possible, but whether you do/do not detach depends on how you want your app to work.
