### ISSUE TITLE
Using detach() without first()

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#186]
Just wanted to share my  code to demonstrate the error I received.
### Scenario:
My destroy method in foobooks.

``` public function destroy(Request $request)
    {
        // Line below will cause an error when adding detach() unless also using first()
        $book = Book::where('id', '=', $request->input('id') )->first();
        // This line will not cause the same above error when also using detach()
        // $book = Book::find($request->input('id'));
        $book->tags()->detach();
        $book->delete();
        return redirect('/book')->with('alert', 'Your selected book was deleted.');
    }
```

Here is the error message ```Call to undefined method Illuminate\Database\Query\Builder::tags()```
I believe first()  is needed to verify there are only specific book_id ‘s to detach from tags, **maybe?**

**Comment by ysrinu** [comment]
@dukesnuz  You can detach a particular tag or all tags for a given book. The bottom line, in any case it should always be for a given book and hence find(id) or first() should be used to make sure it's a single book you are operating on.
https://laravel.com/docs/5.5/eloquent-relationships#updating-many-to-many-relationships

Related but slight off-topic:
I got similar error in my p4. Mine was one-to-many and I still expected 'detach' to delete the records from child tables. I was wrong!
Detach is only used to remove records from the intermediate (pivot) table and therefore is applicable for many-to-many relationships only

**Comment by dukesnuz** [comment]
>Detach is only used to remove records from the intermediate (pivot) table and therefore is applicable for many-to-many relationships only

Good to know, Thank you
