### ISSUE TITLE
Creating databses 

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#188]
In class we saw how we can create databases using SQL command, or through phpmyadmin. Is there a way to create a database using some laravel tool, similar to how we use migrations to create tables? For example, I'm creating an application that has several users, when a new user registers to my app, I want a database to be automatically created for them, how would this be done in the context of laravel?

**Comment by ysrinu** [comment]
Creating databases through application is not ideal. Databases creation are one-time thing and are part of DBA tasks.
What you are asking is creating database user accounts. Each user has it's own schema, which you are referring to database here.
What you want to do is add db user, the database engine will create the schema automatically, you shouldn't have to write code for that.
Also note that user schemas are only to support the user id and not to use that schema for CRUD operations. Most DBAs will restrict the user schema from being used for any purpose other than simply being there for the 'user account' reasons.

Bottom line, don't 'create' database schema for users. Only create database users.
Going further, you SHOULD NOT create database accounts for your application users. 
You only create application user ids, the application will then use a generic database userid. A true end user shouldn't never have an account on the database tier. The application can store in the table metadata about the application user who initiated any CRUD, but the CRUD itself will happen with a generic database user account that no end user will have access to.

Think about your gmail application user id. Your userid is for gmail application, not for the gmail databases.

**Comment by susanBuck** [comment]
It is possible to programmatically create a database via your application. Example:

```php
dump(\DB::statement('CREATE database foobar'));
```

However, like @ysrinu, I do not recommend giving each user their own database.

This is kind of a silly metaphor, but it'd be like if your web application was a gym, and any time someone came in to join your gym, you built a whole new gym for just them to use. This approach would be problematic in many ways. : ) 

With each new user, you want to grow in *rows* on existing tables.. You do not want to grow in *databases* or even *tables*.

@APuente21 - Maybe you could speak a bit to what you're building. With that info, we can help strategize alternative approaches to one-database-per-user.

**Comment by natethegreat418** [comment]
Hey @APuente21 , I'm going to make a broad statement here that may get me roasted, but it is a reasonable assumption that most real-world applications have just a single database supporting it*. The database comprises all the models and relationships (the tables) required for that application to operate in a single place where they can easily managed and maintained by a team.  So in the terms of this week's lecture: the database has a one-to-many relationship with the tables. Hope that helps clarify.

* Don't crucify me - there are many exceptions to this rule:
- In the software as a service industry, it may make sense to run multiple databases for a single application as a means of supporting multi-tenancy
- In service-oriented architectures, what appears to be a single application may actually be a cluster of single-role service applications each with their own database
- Reporting/analytics for commercial user-facing applications generally require multiple servers/database to separate application data for reporting/analytics purposes
- Your application has considerable datastorage and/or volume requirements that necessitate other, more complex architecture (sharding, slave databases, master-master replication, yada yada)

**Comment by mfs780** [comment]
Echoing what was said above it is very unlikely that a DB has to be created problematical. A single DB can have multiple Tables. Each Table should be able to support multiple elements of its type. Such as a Book or Author table will be able to support many books and many authors. Typically each application would require just a single DB with multiple tables representing multiple object types.

**Comment by APuente21** [comment]
Thanks for the feedback- that clarifies things. 
@susanBuck, I'm not actually building anything at the moment - I was just curious to see if such a feature was available in laravel, as I didn't see any mention of it in the documentation.

**Comment by susanBuck** [comment]
@APuente21 Gotcha! Never hurts to be curious. : )
