### ISSUE TITLE
Error no such file when running migrations

### ISSUE THREAD

**Issue by samanthi22** [susanBuck/dwa15-fall2017#189]
I'm getting this error when I do php artisan migrate:fresh.

[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000] [2002] No such file or directory (SQL: SHOW FULL TABLES WHE  
  RE table_type = 'BASE TABLE')                                                
                                                                               

                                                    
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by samanthi22** [comment]
My namespace is Foobooks not App

**Comment by samanthi22** [comment]
Solved. Typo in the notes. "{F" remove the F. Fixed.

**Comment by samanthi22** [comment]
New Error: 

[Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Parse error: syntax error, unexpected '{', expecting function (T_FUNCTION)   
  or const (T_CONST)

**Comment by ysrinu** [comment]
@samanthi22 Check the migration file where it failed. The file probably has syntax errors.

**Comment by susanBuck** [comment]
Piggy-backing on @ysrinu's suggestion - open `/storage/logs/laravel.log` to see more details about the error, including the specific file and line number where it's occuring.
