### ISSUE TITLE
Moving Files to a New Folder

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#19]
## The Scenario

I have 3 pages, index, controller/logic and an external stylesheet which are all in the same folder for development reasons-or just bad planning.  I have been pushing these files to github. 

I then created 2 new folders-one for the external stylesheet and one for the controller/logic files. I moved the files into the appropriate folders. I then push the 2 new folders to github. When I do a git status in the Cmdr  it says deleted: <filename>(x2). I do understand why this is happening = The files are no longer in the original location.

## The questions
Is there a way to delete the 2 messages? Also with respect to github, should the original files stay as they are(outside the new folders)? What about the old files on Ditital Ocean? Should they be deleted?

## The reason for asking
Just want to learn proper procedure.

## Wanted to share 2 new commands
I also discovered 2 useful commands ```MOVE```. which moves files/folders 
and
```logout``` which disconnects the connection to DigitalOcean

Thank you

**Comment by gabrielsanna** [comment]
If I understand what you're seeing correctly...

When you move a file, git interprets this as deleting the file from the original location, and adding it to the new location. As you know, to add a new file to the git repository, you use the command `git add <filename>`. To remove the file from the repo as part of your commit, you'll use the command `git rm <filename>`. Then, the next time you commit and push, the files in the original location will be removed from the repo.

So, suppose you want to move a file from `/path/to/gitrepo/oldfolder/filename.php` to `/path/to/gitrepo/newfolder.php`. The steps would be:

1. Change directory to the repo: `cd /path/to/gitrepo`
2. Move the file: `mv ./oldfolder/filename.php ./newfolder/`
3. `git rm` the old file to remove it from the repo: `git rm oldfolder/filename.php`
4. Add the new copy of the file to the repo: `git add newfolder/filename.php`
5. Commit and push normally.

But wait! Git has a `mv` command to combine the delete and add steps:

1. Change directory to the repo: `cd /path/to/gitrepo`
2. Move the file: `mv ./oldfolder/filename.php ./newfolder/`
3. Tell git that you moved the file: `git mv oldfolder/filename.php newfolder`
4. Commit and push normally.

This page has another example of both techniques: https://githowto.com/moving_files

**Comment by zeroender** [comment]
It's worth noting that there can be different results of moving files in git/renaming files in git, with respect to the history of the file:

https://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history

However, that's way beyond what you'd need to worry about in this case!

**Comment by susanBuck** [comment]
Side note: @dukesnuz You need a space after the `#` in your Markdown headings for them to show up as headings. You can edit your original post and see the difference.  It's great how you added the headings to your post to organize it!

**Comment by dukesnuz** [comment]
@gabrielsanna @zeroender @susanBuck  Thank you for your input.
So if I am understanding correctly, when the files are moved into another folder, most likely the history is lost and Blame cannot be used? Moving/renaming old files in git is not very efficient. 

Unless you delete the old files from github, you will continue to get a message  _deleted: <filename>_ when ```git status``` is run.

**Comment by zeroender** [comment]
Hi @dukesnuz,

If you move the files with git's mv, the file history should remain.  I believe it will still show you a delete/create in git status, but after the fact you should be able to view git changes done to the files prior to the move.  Once you commit everything and push, the git status should return to no changes.

**Comment by susanBuck** [comment]
To summarize, all three of the following techniques should allow you to relocate a file in your repository, while maintaining a history of where that file previously was. In the examples I move a file called `ex.js` from the root of the project to `js/ex.js`

__Option 1)__ Move the file, then have git stage the deletion of the old file's location and the addition of the new file's location. 
```
$ mv ex.js js/ex.js
$ git add ex.js
$ git add js/ex.js
```

__Option 3)__ Same as above, except `git rm` is used to stage the deletion of the old file's location.
```
mv ex.js js/ex.js
git rm ex.js
git add js/ex.js
```

__Option 2)__ Simplifies everything by doing the moving and staging all in one step.
```
$ git mv ex.js js/ex.js
```

After doing a git commit and git push of any of the above options you should have a clean working directory, and a history of the move in your git history ([example commit](https://github.com/susanBuck/foobooks0/commit/cc03c3bb928996e6c3eca9b6a2d8ac1001ca3b9c).

@dukesnuz Does this and the above student posts answer your question? Let us know if it's still not working how you expect or anything is still unclear.

**Comment by dukesnuz** [comment]
Yes. Great. Many thanks.
