### ISSUE TITLE
Seeders fail: Parse error: syntax error, unexpected 'return' 

### ISSUE THREAD

**Issue by samanthi22** [susanBuck/dwa15-fall2017#190]
When I try to seed I get this error:

[Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Parse error: syntax error, unexpected 'return' (T_RETURN), expecting functi  
  on (T_FUNCTION) or const (T_CONST)

**Comment by peggyo** [comment]
It sounds like a syntax error since it's throwing off the parser. See, for instance, this on stackoverflow:
[https://stackoverflow.com/questions/3667556/syntax-error-unexpected-t-return-expecting-t-function-oop-php](url)

The cause may be slightly different - semicolon, etc., but check through your code.

**Comment by samanthi22** [comment]
Syntax error fixed. Now I'm getting this error:
Still not able to seed.

[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000]: General error: 1364 Field 'author' doesn't have a default   
  value (SQL: insert into `books` (`created_at`, `updated_at`, `title`, `auth  
  or_id`, `published`, `cover`, `purchase_link`) values (2017-11-28 19:04:32,  
   2017-11-28 19:04:32, The Great Gatsby, 1, 1925, http://img2.imagesbn.com/p  
  /9780743273565_p0_v4_s114x166.JPG, http://www.barnesandnoble.com/w/the-grea  
  t-gatsby-francis-scott-fitzgerald/1116668135?ean=9780743273565))             
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000]: General error: 1364 Field 'author' doesn't have a default   
  value

**Comment by samanthi22** [comment]
In my BooksTableSeeder I have this as author. 

'author_id' => $author_id,

**Comment by samanthi22** [comment]
Ok I forgot to comment out #$table->string('author') in create books table. New problem. Author_id cannot be nullable.

[Illuminate\Database\QueryException]                                         
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'author_id' ca  
  nnot be null (SQL: insert into `books` (`created_at`, `updated_at`, `title`  
  , `author_id`, `published`, `cover`, `purchase_link`) values (2017-12-01 19  
  :20:37, 2017-12-01 19:20:37, Belonging: a culture of place., , 1969, https:  
  //prodimage.images-bn.com/pimages/9780415968164_p0_v1_s550x406.jpg, https:/  
  /www.barnesandnoble.com/w/belonging-bell-hooks/1101537136))                  
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'author_id' ca  
  nnot be null

**Comment by susanBuck** [comment]
The error is telling you what the problem is: *Column 'author_id' can not be null*

Look closely at the SQL statement and notice how after the title and before the published date there's an empty value...
```
Belonging: a culture of place., , 1969
```

You need to figure out why `author_id` is null.

**Comment by samanthi22** [comment]
Ok it works. It's because I didn't have bell hooks or dr. seuss in my AuthorsTableSeeder.
