### ISSUE TITLE
Making a browser automatically reload css and js files when they change

### ISSUE THREAD

**Issue by rrtx2000** [susanBuck/dwa15-fall2017#193]
A few weeks back there was a discussion about css and js files not being automatically reloaded when changes are made to the files.
Some of the solutions were:

1. Reload the page
2. Clear the cache
3. When you make a change to the css or js file, put a ?v=number after the filename to make it look different to the browser. An example of this would be css/main.css?v=1, css/main.css?v=2...

I have a great solution but I didn't respond back then because I had to figure out the Laravel directory structure first.

My solution is similar to the main.css?v= idea except rather than manually changing the number each time the file changes, I use the php function filemtime to generate the number.
As you probably guessed, filemtime gets file modification time.
This way when the css or js file changes, the modified time changes and makes it look different to the browser and thus automatically reloads the file.

**Here's how I do it.**
My css file is here: p4/public/css/main.css
In my master.blade.php file I have this:

```
<?php $cssFilemtime = filemtime($_SERVER['DOCUMENT_ROOT'] . '\\css\\main.css');?>
<link href="css/main.css?v={{$cssFilemtime}}" type='text/css' rel='stylesheet'>
@stack('head')
```

Looking at the source code for the page gives the following:
`<link href="css/main.css?v=1512528340" type='text/css' rel='stylesheet'>`

Before implementing this solution at my job, we had these issues a lot were we had to instruct the user to reload the page or clear their cache. I implemented this about a year ago and it works like a champ. We haven't had to tell a user to reload the page or clear their cache since.

**Comment by dukesnuz** [comment]
@rrtx2000 Good find. I usually use ```/css/main.css?t=<?php echo rand(); ?>```
I believe in production these should not be used as we may want the users to cache css and js files. I guess it depends your situation.

**Comment by susanBuck** [comment]
Useful tip, @rrtx2000! I think we've all been "bitten" by the dreaded CSS cache effect. : )

I'd riff on this by making it dynamic so it only uses unique version numbers when working locally. 
As @dukesnuz pointed out, we do want to take advantage of the caching on production.

## Instructions
In `app/Providers/AppServiceProvider.php` in the `register` method, add the following code. This method is invoked every time your app runs, ensuring that the variable you're creating is always available to all views.

```php
# Use statements that need to be added to the top:
use App;
use Carbon\Carbon;
use View;

public function register()
{
    # If running on local, set the asset version to a unique timestamp
    if (App::environment('local')) {
        $assetVersion = Carbon::now();
    # Otherwise, set it to whatever is in the config (or if not set, blank)
    } else {
        $assetVersion = config('app.assetVersion') or '';
    }

    # Make asset version available to all views
    View::share('assetVersion', $assetVersion);
}
```

Then in your views:

```html
<link href="/css/foobooks.css?v={{ $assetVersion }}" type='text/css' rel='stylesheet'>
```

Note how the above code gives you the option to set an assetVersion in your config for use on production. This is handy when you push a lot of of changes to your css/js and want to make sure users are getting the latest version. 

On this whole topic of client side assets, something to have on our radars: [Compiling Assets (Laravel Mix).](https://laravel.com/docs/5.5/mix)

**Comment by rrtx2000** [comment]
Actually, with my method caching still happens until the file changes.
As long as the css file stays the same, the modified timestamp (1512528340 in this case) doesn't change so the cached version is used indefinitely.
The browser only reloads the file if the modified timestamp changes. 
The modified timestamp only changes if the file was changed.
If the file changed I don't want to use the cached version in development or in production.

That's an interesting Laravel idea.

**Comment by susanBuck** [comment]
@rrtx2000 You're totally right. I think I was blending together your solution and @dukesnuz's in my head when I said we'd lose caching on production. : )

It'd be interesting to benchmark both approaches to see which is faster. They both have a "tax" in regards to extra processing.
In your case, you have to check the modification timestamp on each asset.
In my case, there's work to get the config, check the environment, etc.
