### ISSUE TITLE
Shared methods for all controllers

### ISSUE THREAD

**Issue by nekoCC01** [susanBuck/dwa15-fall2017#196]
I just wanted to share a solution for the case of using the **same function in different controllers**.
I found myself repeating a lot of code and found this approach in a [stackoverflow-post](https://stackoverflow.com/questions/36842225/share-method-between-controllers-laravel-5-2):

- creating a "trait" (a class with functions that can be shared) in the App-folder
- using these trait-functions within the controllers

More information can be found here: https://www.conetix.com.au/blog/simple-guide-using-traits-laravel-5

It helped me a lot to make my code cleaner.
Perhaps someone has found a different solution?

**Comment by susanBuck** [comment]
Great tip! 

@nekoCC01 I think it'd be useful if you could share an example of how you're implementing traits in your application (if you've got the time to compile the details into a post : )

Also, in thinking about traits, the question often comes up of how it's different from just having some external class with your shared methods. The answer to that:

>> A Trait is similar to a class, but only intended to group functionality in a fine-grained and consistent way. It is not possible to instantiate a Trait on its own. 

Ref: <http://php.net/manual/en/language.oop5.traits.php>

**Comment by nekoCC01** [comment]
Yes, of course I can share the details of implementation:

My app is a quote collection, which allows to create quotes, concepts and arguments and connect them with each other. 
I have **three controllers** (Quote-/Concept-/ArgumentController) that all have a store- and update-method, working with form data. In these forms you can **add a philosopher and a work**.
This functionality is them **same throughout the Controllers**, so I put that code into a newly created Trait-file:
`app/Traits/CustomFormActions.php `([Github-Link](https://github.com/nekoCC01/DWA-Project04/blob/master/app/Traits/CustomFormActions.php))

 It has the following structure:
```php
<?php
namespace App\Traits;
trait CustomFormActions
{
    public function store_new_philosopher_work($request, $philosopher, $work, $entry)
    { //code follows here
```
_(In my case, the code handles the request and adds a new philosopher/work, and also a reference in the table of the current entry (quote, concept or argument))_

Within the controllers, the trait has to be **made available**, like so:
```php
use App\Traits\CustomFormActions;
class QuoteController extends Controller
{
    use CustomFormActions;
```
Then the shared **function can be called** anywhere within the controller:
```php
    public function store(Request $request)
    {
        $quote       = new Quote();
        [...]
        $work        = new Work();
        $philosopher = new Philosopher();
        $this->store_new_philosopher_work($request, $philosopher, $work, $quote);
```
([Github-Link of the QuoteConroller](https://github.com/nekoCC01/DWA-Project04/blob/master/app/Http/Controllers/QuoteController.php))

**Comment by susanBuck** [comment]
Thanks for sharing @nekoCC01 !
