### ISSUE TITLE
'PUT' and 'DELETE' Routes

### ISSUE THREAD

**Issue by mconstanti** [susanBuck/dwa15-fall2017#197]
I'm still a bit confused about when to use `PUT` instead of `POST`, and why `DELETE` should be used, in our Routes' web.php file. I could not find anything that goes into this in the Laravel Documentation on Routes.

**Comment by ALiborio** [comment]
I believe idea is to go follow the RESTful model as explained here:
https://www.tutorialspoint.com/restful/restful_introduction.htm 

As shown there the HTTP methods support PUT and DELETE. 
If you want to format your routes along those lines then you'd have a way to differentiate the actions without needing a different url.
For example, in my project I have the following routes:
```
Route::get('/character/{id}', "CharacterController@show")
Route::put('/character/{id}', "CharacterController@update");
Route::delete('/character/{id}', "CharacterController@destroy");
```
These all act on the same URL but the methods differ which lets us know which action to take.

**Comment by stbenjam** [comment]
One of the main benefits of REST is being able to use it in an API -- for example you can interact with GitHub in a program you write by sending DELETE/PUT/POST/GET requests with various content, it's not just for web pages in a browser. 

https://developer.github.com/v3/

**Comment by mfs780** [comment]
@ALiborio the url you mentioned states that PUT is typically used to create a new resource and POST is used to update/create a resource. However, your example and the REST API used in FooBooks point to PUT being used as an update method and POST used as a create method.

That is the way I am utilizing it as well in my project.

**Comment by HeinrichTremblay** [comment]
You want to use `PUT` for updating an already existing resource and `POST` to create a new resource. `DELETE` should be kept for deleting a resource.

 The confusion is perhaps why bother being so verbose, one could simply use `POST` and `GET` for everything. The main reason to follow these rules is to help you stay organized as a developer. It will make your API much more understandable and useable by anybody you eventually want to open parts of your API to. It clears the clutter out of your routes.

Source: [https://coursework.vschool.io/rest-api-design/](https://coursework.vschool.io/rest-api-design/)

**Comment by susanBuck** [comment]
For reference, here's the patterns I'm loosely following in Foobooks:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/237711/33850142-e72d1bc8-de80-11e7-8176-24b0ee32ecd4.png">

(From <https://laravel.com/docs/5.5/controllers#resource-controllers>)

I say loosely, because there is some divergence - for example, I used singular `book` vs. their plural `photos`. In hindsight, I shouldn't have done this, and in future semesters will use `books`.
