### ISSUE TITLE
Transform the array of authors into an associative array

### ISSUE THREAD

**Issue by HeinrichTremblay** [susanBuck/dwa15-fall2017#199]
In the author dropdown [lecture](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/99_Foobooks_Lecture_13a.md), the way to transform the array of authors into an associative array where the key is the author id and the value is the author name is the following:

``` php
  $authorsForDropdown = [];
    foreach ($authors as $author) {
        $authorsForDropdown[$author->id] = $author->last_name.', '.$author->first_name;
    }
```

I think we can get the same result with the [array_reduce](https://www.w3schools.com/php/func_array_reduce.asp) function:

``` php
    $authorsForDropdown = array_reduce($authors, function ($result, $item) {
        $result[$author->id] = $author->last_name.', '.$author->first_name;
    });
```

What would be the recommended approach, is there any trade-off by using the `array_reduce` function instead?

**Comment by TheLivingNick** [comment]
I'm not sure you get the same result. Since array_reduce returns a sting, wouldn't $authorsForDropdown be a string in the second example instead of an array like in the first?

**Comment by HeinrichTremblay** [comment]
@TheLivingNick according to this Stackoverflow [question/answer](https://stackoverflow.com/questions/11563119/how-to-convert-an-array-of-arrays-or-objects-to-an-associative-array) it can return an associative array as well.

**Comment by susanBuck** [comment]
I'm not aware of any trade-off, just two different approaches to the same outcome. To me the foreach approach is more "friendly" than the higher order function approach, but go with what makes the most sense to you.
