### ISSUE TITLE
New ssh key on separate computer not working with DigitalOcean

### ISSUE THREAD

**Issue by TheLivingNick** [susanBuck/dwa15-fall2017#20]
I started do do some work on a different computer than I originally set up the ssh to Digital Ocean on and tried to recreate the setup for Github and DigitalOcean ssh. The setup for Github worked fine and I can ssh in, but the key will not work for the DO droplet. Every time I try I just get "Permission denied (publickey)".

I tried to run the fix listed in the notes and used "cat id_rsa.pub | ssh root@[your.ip.address.here] "cat >> ~/.ssh/authorized_keys" " in the ssh directory, but that just returned the same "Permission denied (publickey)" error.

The key for the original computer still works, but it would be nice to work with the multi-monitor setup the new computer has.

I am on a Windows PC running Cmder for CL.

**Comment by zeroender** [comment]
I think with a second computer you may need to generate a second key on the new computer in this step (https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/07_Deploy_to_DigitalOcean.md).  It sounds like the GitHub integration worked on the 2nd computer?

Alternatly, you can copy the private key to the 2nd machine, and then the same public key should work (referencing https://unix.stackexchange.com/questions/208495/ssh-key-authentication-with-multiple-computers)

**Comment by TheLivingNick** [comment]
I did create a new ssh key for the new computer ($ ssh-keygen -t rsa -C "your_email@example.com" from https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/04_Github_setup.md) and the new key worked for Github; it is just DO that is an issue.

**Comment by gnodar01** [comment]
Did you add the newly generated public key on Digital Ocean as [shown in the notes](https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/07_Deploy_to_DigitalOcean.md)?

**Comment by zeguy** [comment]
Hi Nick, had the same issue. Suggested command fix didn't seem to work so -after making sure both keys were saved in the digital ocean security settings -so I just created a new droplet and made sure to check both keys in the initial setup options.

**Comment by TheLivingNick** [comment]
Double-check the key entered on DO against local key, they match up.

For now I'm doing most of the work on the new setup, and using the original laptop for ssh'ing into DO.

**Comment by susanBuck** [comment]
`Permission denied (publickey)` means there's a mismatch between the keys. 

To double-check your double-check, can you confirm you did the following:

1. Opened `id_rsa.pub` locally on your non-working machine to view your public key.
2. SSH'd into your server from your working machine.
3. On the server, viewed the contents of `~/.ssh/authorized_keys` and confirmed you find a public key that is the exact match to the one you saw in step 1. 

FYI: The command to add a key to a server...
```
cat id_rsa.pub | ssh root@[your.ip.address.here] "cat >> ~/.ssh/authorized_keys
```
...only works if you can connect to the server, which is typically done via password if you don't have SSH key access. DigitalOcean appears to disable password authentication by default though. (Perhaps it does this if you add a SSH key when you create the Droplet?) As a result, if you don't have a SSH key, or you have a failed SSH key connection, you're effectively locked out.

Fortunately, for you - you do have access from another machine.

If anyone else finds themselves in this same boat with no access from another machine, I found a post from a previous semester where I wrote up instructions on how to resolve the issue:

[Permission denied (publickey) when SSH'ing into DigitalOcean server](https://gist.github.com/susanBuck/14a9cb6abb7d4464b62457fccefa74b8)

**Comment by susanBuck** [comment]
Bumping this post to see if this issue can be closed or if it's still pending.

**Comment by TheLivingNick** [comment]
Yes! Went through the steps in the link you posted and it worked! Thank you very much :)
