### ISSUE TITLE
How to know if a model was updated

### ISSUE THREAD

**Issue by asmatmuradi** [susanBuck/dwa15-fall2017#200]
I've a logic in my controller file where I update some details about a product (very similar to the Foobook's edit). I'm trying to find out if the form was submitted with changes or with the same existing data. I'm using `->save()` method so it doesn't run the update SQL if there are no changes. How can I find if there was any change or not? 

I tried to use `$product->isDirty()` but it always returns false regardless of the change. Now, I accomplished creating two copies of a model and then compare them after `save()` but I know its not the best way to do it. Below is my current code: 

```php
          $product = Product::find($id);
          $existingProduct = Product::find($id);

          $product->name = $request->input('name');
          ....
          $product->image = $request->input('image');
          $product->save();
          ##check if there were any changes
          if ($product != $existingProduct)
          {
            .....
              'Alert' => 'The product below was updated successfully:'
            ]);
          }
          else
          {
           ......
              'Alert' => 'There were no changes to update this product. Please make the required changes and click Save.'
            ]);
          }

```

**Comment by ysrinu** [comment]
@asmatmuradi  Usually it's not a good idea to check if any of the input fields have changed.
Even if the user hasn't changed any, you may still want to run a true update so that the update timestamp is renewed. This is to indicate that the user has submitted an update at that time (and is responsible for data as of that time).

**Comment by susanBuck** [comment]
Here's an example of how you can check for differences:

```php
# Mock data representing the kind of data you'd get from the request
$newBookData = collect([
    "title" => "The Great Gatsby!", # <-- Note the difference
    "published" => 1925,
    "cover" => "http://img2.imagesbn.com/p/9780743273565_p0_v4_s114x166.JPG",
    "purchase_link" => "http://www.barnesandnoble.com/w/the-great-gatsby-francis-scott-fitzgerald/1116668135?ean=9780743273565",
    "author_id" => 1,
    "user_id" => 1,
]);

# Get a book to compare the above data with
$book = Book::find(1);

# Look for differences
$differences = $newBookData->diffAssoc($book);

if (count($differences) == 0) {
    dump('No differences');
} else {
    # Output the differences
    dump($differences->all());
}
```

Ref: <https://laravel.com/docs/5.5/collections#method-diffassoc>

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
