### ISSUE TITLE
Any hints for finding all books not tagged as 'classic'  and perhaps not tagged at all using pivot table?

### ISSUE THREAD

**Issue by peggyo** [susanBuck/dwa15-fall2017#202]
If my app were foobooks, I would like to provide the following page to add / remove book to a tags:
(Click the arrows to represent links to move a book to/from category.)

### Not tagged Classic   |   Tagged Classic
       Book 1     -->       <--  Book 2
       Book 3     -->       <--  Book 4

I have no problem finding the list of books tagged as Classic. I am having trouble getting the list not tagged classic. I thought I had it working until I noticed a duplicate book. Also, I believe any books in my books table that were not yet tagged at all (Book5, Book6?) were not being found. Just looking for hints at the general steps, which are currently eluding me. Am I right in thinking I should go at it from both the Book and the Tag model?  Has anyone implemented something similar?  Thanks in advance.

**Comment by peggyo** [comment]
I got it working for now. Probably not the optimal way, and it does not yet take the possibility of a duplicate book title into account, but I can move forward. I did use both the Book and Tag model, and did a diff on the arrays of ids. I get the books associated with the tag on the first retrieve, but then go to the Book model to get all of the books, then use arrays to compare/diff. Because in my case not all Books are tagged, I wasn't sure how else to do it. Also, what I thought was a dupe row in my tables initially turned out to be a display problem with my unfinished css, so that was a red herring.

Note, I am not actually coding Books and Tags, but it makes it easier to explain the problem using Foobooks terms.

**Comment by susanBuck** [comment]
Below are two approaches I came up with. I think my Approach B is probably similar in style to what you came up with.

## Approach A. 
Get all the books and their tags, then filter out books with the tag `classic`
```php
# Get all the books and their tags, then filter out books with the tag classic
$allBooks = Book::with('tags')->get();

$books = $allBooks->reject(function ($book, $key) {
    # Returns True if any of the tags are classic
    # When True is returned, the book is "rejected", i.e. filtered out
    return $book->tags->contains('name', 'classic');
});
```

## Approach B. 
Get the ids of all the books we want to exclude (books with the tag `classic`), then query for books not in those results.
```php
$idsOfBooksToExclude = Book::whereHas('tags', function ($query) {
    $query->where('name', 'like', 'classic');
})->pluck('id')->toArray();

# Now that we know this info, get all the books *except* the ones we found in the previous step
$books = Book::whereNotIn('id', $idsOfBooksToExclude)->get();
```
