### ISSUE TITLE
Tags on All Books View 

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#205]
We saw how to show tags on Edit and Add Book Views. I am wondering how to show tags for each book on the All Books View. We don't want to show checkboxes, of course, but let's say we want to show actual tags names for each book. Like for "Harry Potter and the Chamber of Secrets" By By J.K. Rowling, show **novel, classic and etc.**  Because we need to get it using pivot table, I am confused how to pull it to the all books view.

**Comment by susanBuck** [comment]
In the "Edit" a book page, we saw [code to get all the tags for a given book](https://github.com/susanBuck/foobooks/blob/master/app/Http/Controllers/BookController.php#L128):

```php
$book = Book::with('tags')->find($id);

$tagsForThisBook = [];
foreach ($book->tags as $tag) {
    $tagsForThisBook[] = $tag->name;
}
```

From this, we can see all the tags for a given book is available to us via `$book->tags`.  Knowing this, assuming your $book is available in the view, you could print out all the tags like so:

```php
@foreach($book->tags as $tag) 
    {{ $tag->name }}
@endforeach
```

For other examples, refer to [PracticeController@practice25](https://github.com/susanBuck/foobooks/blob/master/app/Http/Controllers/PracticeController.php#L117) and [PracticeController@practice26](https://github.com/susanBuck/foobooks/blob/master/app/Http/Controllers/PracticeController.php#L100)

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
