### ISSUE TITLE
eager load, number of queries growing exponentially 

### ISSUE THREAD

**Issue by ruthnphillips** [susanBuck/dwa15-fall2017#206]
I have 3 tables: `athletes, videos, sports`;  with relationship where each athlete may have many videos, each video has only 1 sport.

```
athletes{id, name}
sports{id, name}
videos{id, athlete_id, sport_id, url}.
```

For a particular athlete page, i want to show the following:
**athlete.name, video.url, sport.name**

In my controller, I have this
```
    public function showAthlete($id)
    {
        $athlete = Athlete::with('videos')->find($id);
        return view('athlete.user.show')->with([
            'athlete'=>$athlete
        ]);
    }
```
In my view file, i have this
```
<p> {{ $athlete->name }} <p>
@foreach($athlete->videos as $video)
    <p>URL: {{ $video['url'] }}</p>
    <p>SPORT: {{ $video['sport']['name'] }}</p>
 @endforeach
```
Unfortunately, the number of queries grows exponentially due to this statement `$video['sport']['name'] ` based on how many videos the user has. How can I modify my controller to eliminate this ?

**Comment by susanBuck** [comment]
Good catch on noticing the extraneous queries.

I believe you're looking for something called **nested eager loading**:

```php
$athlete = Athlete::with('videos.sport')->first();
```

Ref: <https://laravel.com/docs/5.5/eloquent-relationships#eager-loading>
