### ISSUE TITLE
How to make data available to all views (for example, user data)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2017#207]
Sometimes you'll find yourself using the same data in all or many views.

Rather than having to explicitly attach the data to each individual view return, you can use a [**view composer**](https://laravel.com/docs/5.5/views#view-composers) to attach data to all or many views.

A specific use-case for this is if you're working with logged in users and you want some or all of the user data available in each view. 

For example, right now you're logged into Github, and on every page you visit you see your user icon on the top right. 

I just expanded the [Authentication Usage notes with instructions on how to do this](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/35_Authentication_usage.md#making-the-user-data-available-to-all-views).

Even if you haven't dug into the Auth notes (since they're optional), the same principles of view composers can be applied to other data.

**Comment by natethegreat418** [comment]
Hey @susanBuck , thanks for this! What are your thoughts on putting some of this "persistent" data into long-held session? I did this in a few cases on my final project and it seemed to work smoothly.

**Comment by susanBuck** [comment]
@natethegreat418 - I think that approach makes sense in a lot of cases. Can save a trip to the database. 👍
