### ISSUE TITLE
Validate only if not null

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#208]
This is an extension of https://github.com/susanBuck/dwa15-fall2017/issues/182

Let's say I want the dropdown menu to be optional. I am removing the 'disabled' here, so the user can always leave the menu with 'Please choose one' as _no-selection_

```php
<select name="author_id">
    <option value="" selected="selected">Please choose one</option>
    @if ($authorsForDropdown->count())
        @foreach($authorsForDropdown as $key => $val)
            <option value="{{ $key }}" {{ $book->author_id == $key ? 'selected="selected"' : '' }}>{{ $val }}</option>
            @endforeach
    @endif
</select>
```
Let's say in the controller we have validation rule on the `author_id` as numeric. We have this validation so that it's always checked whether the values are entered by a dropdown menu or text box input.
```
$this->validate($request, [
    'owner' => 'numeric',
]);
```
When the form is submitted with menu at the "Please choose one", the value of author_id is "" or empty (not the same as null) and hence throws this error by laravel validation rule
`The author id must be a number.`

'Sometimes' didn't help either, because the id is present in the request data
`'author_id' => 'sometimes|numeric',`

I tried to modify the request as below before the validation rule, but I still get the same error

```php
if (empty($request['author_id']) || $request['author_id'] == '') {
    $request['author_id'] = null;
}
```

I remove the `author_id` validation from the group validation and isolated as:

```php
if (empty($request['author_id']) || $request['author_id'] == '') {
    $request['author_id'] = null;
} else {
    $this->validate($request, [
        'author_id' => 'numeric',
    ]);
}
```
The above works except that author_id is validated in isolation with other fields, so if the other fields fail validation it will show the form with those errors only. If the author_id field is first validated then it will immediately return to the form with just this validation error without validating the other fields.

I am looking for a cleaner/leaner way of validating if the input request is not empty, better, to modify request so that empty strings are converted to null values where desired

https://laravel.com/docs/5.5/validation#conditionally-adding-rules

**Comment by susanBuck** [comment]
Following the section under **Complex Conditional Validation** in the docs you linked to, I came up with this:
```php
public function practice30b(Request $request)
{
    # Instantiate the validator
    $v = Validator::make($request->all(), []);

    # If the author_id is not null, then apply `numeric` validation rule
    # https://laravel.com/docs/5.5/validation#conditionally-adding-rules "Complex Conditional Validation"
    $v->sometimes('author_id', 'numeric', function ($input) {
        return !is_null($input->author_id);
    });

    $v->validate();

    echo "If you see this, validation passed. <a href='".url()->previous()."'>Back</a>";
}
```

Demo here: <http://foobooks.dwa15.me/practice/30>

Another approach would be to create a custom validation rule - [some tips on how to do this can be found here.](https://github.com/susanBuck/dwa15-fall2017/issues/104)

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
