### ISSUE TITLE
Routes do not work on production

### ISSUE THREAD

**Issue by erictracy11492** [susanBuck/dwa15-fall2017#209]
Hello,

Everything works fine when working locally. On production, my welcome route works, but everything else seems to return the error: "Whoops, looks like something went wrong."

Any idea what might be causing this? My repository link is below. Any help is appreciated.

https://github.com/erictracy11492/p4 

Thank You

**Comment by ysrinu** [comment]
@erictracy11492 Can you check the laravel log files? You can delete the log file, access the page from url and then check the log file.
(Usually we archive log files in production and not delete. You can delete for now so that you are only looking at the latest logging info)

**Comment by erictracy11492** [comment]
I checked the laravel log. Could this be creating an issue?

<img width="717" alt="screen shot 2017-12-08 at 9 30 02 pm" src="https://user-images.githubusercontent.com/31494476/33791759-2d10f3fe-dc5f-11e7-8ac0-b7f03c2ed0f5.png">

**Comment by ysrinu** [comment]
You got ReflectionException error

Run `composer dump-autoload`

https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/30_Production_database_setup.md#troubleshooting

Many To Many Join table not seeding
https://github.com/susanBuck/dwa15-fall2017/issues/177

running db seed in production, ReflectionException
https://github.com/susanBuck/dwa15-fall2017/issues/150

Production Pivot Table Seeder Error
https://github.com/susanBuck/dwa15-fall2017/issues/204

**Comment by erictracy11492** [comment]
@ysrinu 
Awesome got it to work, thank you!
