### ISSUE TITLE
SubDomain change does not reflect

### ISSUE THREAD

**Issue by asmatmuradi** [susanBuck/dwa15-fall2017#21]
I changed the subdomain name to [hello-world](hello-world.asmatmuradi.info) but the redirection to the hello-world sub-directory does not work. It works fine when I try asmatmuradi.info/hello-world.
The hello-world.asmatmuradi.info takes to the root directory which means the subdomain is working. 
I changed the /etc/apache2/sites-enabled/000-default.conf file to the following: 
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/
        <Directory /var/www/html/>
        	Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>
		
		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined
		<IfModule mod_dir.c>
			DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
		</IfModule>
</VirtualHost>

<VirtualHost *:80>
        ServerAdmin hello-world.asmatmuradi.info
        DocumentRoot /var/www/html/hello-world/

        <Directory /var/www/html/hello-world/>
            AllowOverride All
        </Directory>

</VirtualHost>
```

Restarted the apache2 service successfully but still no luck. 
Any suggestions?

**Comment by ysrinu** [comment]
Server**Admin** hello-world.asmatmuradi.info

Double check the above in bold !!!

**Comment by peggyo** [comment]
Compare against the steps and example code in 08_Production_domain.md

**Comment by milliezhou** [comment]
Did you set up a subdomain on your hosting site (e.g., namecheap.com)?

**Comment by asmatmuradi** [comment]
@ysrinu what is the ServerAdmin? 

@milliezhou Yes, I did set up a subdomain. It works when i used hello-world.asmatmuradi.info/hello-world.

**Comment by ysrinu** [comment]
@asmatmuradi , it should be ServerName and not ServerAdmin

**Comment by asmatmuradi** [comment]
@ysrinu Thanks a lot. This was the issue.
