### ISSUE TITLE
Created and Updated "by" user columns

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#210]
@susanBuck 
During the mid semester when you explained laravel takes care of 'created_at' and 'updated_at' timestamp columns, I immediately thought of 'created_by' and 'updated_by' columns.
It's not uncommon to have these two fields per table for auditing purpose.
It's upto the application to determine what values to pass for these columns. We shouldn't use database userid for these columns values since the application might be using a generic db userid but the action performed by the end application user is not.

Laravel supports Authentication and Users (and we can add User Roles too). Can laravel create and update the created/updated_by columns with the current logged in user id? I would think this is a useful and highly requested feature

Thanks,
-Sri

**Comment by davida26** [comment]
Found this - untested but looks useful.

https://github.com/fico7489/laravel-revisionable-upgrade

**Comment by susanBuck** [comment]
There's not a specific feature in Laravel (out of the box) for automatically updating a `created_by` or `updated_by` field. 

But all the tools you need to make it a convenient process are available - for example, [Model events](https://laravel.com/docs/5.5/eloquent#events).
