### ISSUE TITLE
Getting Data From A Pivot Table

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#212]
#### Stumbled upon how to get data from a pivot table.
Wanted to pass this on as it came in very handy for me.
[Getting data from a pivot table](https://stackoverflow.com/questions/27434338/laravel-get-pivot-data-for-specific-many-to-many-relation)

**Comment by ysrinu** [comment]
From Laravel doc https://laravel.com/docs/5.5/eloquent-relationships#many-to-many
check the below topics:

Retrieving Intermediate Table Columns
Customizing The pivot Attribute Name
Filtering Relationships Via Intermediate Table Columns
Defining Custom Intermediate Table Models

![image](https://user-images.githubusercontent.com/25366909/33792634-24a8ff9a-dc73-11e7-8a5f-8ba7d29f270e.png)

**Comment by dukesnuz** [comment]
@ysrinu  Thank you for the useful information

**Comment by stbenjam** [comment]
Wow thanks, I should've read the Laravel documentation closer.  I ended up doing something a lot more complicated.
