### ISSUE TITLE
View [modules.error-field] not found

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#213]
I am setting up authentication from notes
https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/34_Authentication_setup.md

After editing the login blade, on accessing `/login` page I get the below error:
`View [modules.error-field] not found. (View: C:\xampp\htdocs\p4\resources\views\auth\login.blade.php)`

I don't see a folder 'modules' under the 'views' folder. Neither do I see it created when ran `php artisan make:auth` command

**Comment by sheetaldalvi** [comment]
This was set for validation errors for input fields earlier in foobooks project.

**Comment by ysrinu** [comment]
@sheetaldalvi  Thank you!
@susanBuck Is it possible to add a note next to the line
`Display errors using our modules.error-field view.`
that 'modules' is a custom view already built in previous lectures ?

**Comment by susanBuck** [comment]
@ysrinu No, I think it's okay as is. It's expected students will stumble on certain things as they move forward in the material, forgetting about concepts/tricks shown previously. Learning to debug these issues is useful and makes for good review. 

I encourage you to add it to your own personal notes on the subject. :-)
