### ISSUE TITLE
Authentication, Login twice

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#214]
@susanBuck 
In the bonus [material](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/35_Authentication_usage.md#authcheck) we see how to hide the 'Log In' link if already authenticated.

Nevertheless, in the notes https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/34_Authentication_setup.md#routes

Can we add the below change
Edit file `app/Http/Middleware/RedirectIfAuthenticated.php`
Change `return redirect('/home'); ` to `return redirect('/');`

The above change ensures that if Log In route is visited while already logged in, it will redirect the user to `/` and not `/home`

**Comment by susanBuck** [comment]
I'm confused - isn't that already covered in the notes? 

Ref:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/237711/33852160-69d83994-de87-11e7-947f-2b250647c503.png">

**Comment by ysrinu** [comment]
@susanBuck  My mistake. I was too eager to having authentication setup that I read the notes too quickly. I made the edits as in the top section, and assumed the lower section was pointing to the changes done (missed that it's a new file)
