### ISSUE TITLE
Using Eloquent Method all( ), Retrieving One Column of Data

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#215]
I am not sure if this is mentioned in our notes. If it is I must have missed it.
Wanted to pass this on.

### Scenario:
Say you want to get all the ids from a table. 
If you use all( ), then all the columns will be returned.
### Answer:
If you use all('id') returned data will be an array of all the ids only. 

Not sure on the performance aspect as my tables are not very large.

**Comment by ysrinu** [comment]
`all('id')` is sql equivalent of `"select id from table A"`
Use if only need 'id' column value only

For more columns (rather than all columns), see 'select' in
https://laravel.com/docs/5.5/queries#selects

**Comment by dukesnuz** [comment]
@ysrinu Thank you for the info. I have used the select before. Not sure if select will work with all( ) method.

**Comment by ysrinu** [comment]
@dukesnuz 
all() is to retrieve all records for that model, you cannot use 'where' clause. You can however specify which columns to choose though (select).
In short, all() is to say "all records" from that model table, and independent of which columns are selected.
