### ISSUE TITLE
Authentication logout not working

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#216]
### Scenario
I am setting up the authentication. Register and login are working. 

### Issue
Not able to get logout working. I am stumped. Not sure where to trouble shoot. Any ideas would be greatly  appreciated.

I did set up authentication on foobooks. No issues there.

**Comment by ysrinu** [comment]
@dukesnuz any error message, screenshot, log files, ...?

**Comment by dukesnuz** [comment]
@ysrinu no error in log file,
when I click logout, ```#``` is inserted into url. then when I use the temp route to verify, shows still logged in.

**Comment by dukesnuz** [comment]
@ysrinu Problem solved. Took logout form out of nav menu. Logout now works as expected. Must be some css or something conflicting with the form. Thank you.

**Comment by ysrinu** [comment]
@dukesnuz Glad it's working.
Use W3 validator for HTML5 and CSS3 errors. Checking and fixing these errors can resolve issues such as that you have seen, or help debug.
You can put a stub for these in your website footer (and remove later) https://github.com/susanBuck/dwa15-fall2017/issues/211

**Comment by dukesnuz** [comment]
@ysrinu Thank you
