### ISSUE TITLE
W3C validation for protected pages

### ISSUE THREAD

**Issue by gvardany** [susanBuck/dwa15-fall2017#217]
I have few pages (create/edit) that are accessible only to logged in users. Is there a way to pass these through the w3c validator as well? Simply passing the link does not work, since it is redirected to the login page, and it's login page that gets validated.

**Comment by dukesnuz** [comment]
@gvardany  Open page in browser->right click and select->view source page->copy code->open validator->select validate by direct input->paste into validator.  
If doing in development do not paste debug code.

**Comment by gvardany** [comment]
Thanks, thats one way to do it 👍
