### ISSUE TITLE
Toggle checkbox by clicking on it's label

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#218]
This issue is only about UI experience, not about business logic of tags.

From the lecture
https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/99_Foobooks_Lecture_13b.md#using-tagsmany-to-many

```php
@foreach ($tagsForCheckboxes as $id => $name)
    <input
        type='checkbox'
        value='{{ $id }}'
        name='tags[]'
        {{ (isset($tagsForThisBook) and in_array($name, $tagsForThisBook)) ? 'CHECKED' : '' }}
    >
    {{ $name }} <br>
@endforeach
```

Once the checkboxes are displayed, the user has to click on the checkbox to toggle it. **Clicking on the name next to the checkbox doesn't work**. This is because the name is not associated as label for that checkbox.

Assigning id attribute (html element, not php/laravel) for each checkbox and creating a label with 'for' attribute on that html id element will allow the user to click on the label to toggle the corresponding checkbox.
Below code works:

```php
@foreach ($tagsForCheckboxes as $id => $name)
    <input
        type='checkbox'
        value='{{ $id }}'
        name='tags[]'
        id='{{ "tagscheckbox_".$id }}'
        {{ (isset($tagsForThisBook) and in_array($name, $tagsForThisBook)) ? 'CHECKED' : '' }}
    >
    <label for='{{ "tagscheckbox_".$id }}'> {{ $name }} </label><br>
@endforeach
```

Note that I prefixed the html element id value with 'tagscheckbox'. This is to make sure that this id attribute value is not used anywhere else in the html page ([must be unique](https://www.w3schools.com/tags/att_global_id.asp))

**Comment by susanBuck** [comment]
Very important UI consideration. Thanks for the reminder.

Updated foobooks to reflect:
https://github.com/susanBuck/foobooks/commit/1932f5028340c46a62bf33e39f7542aecd7da561
