### ISSUE TITLE
Many to Many, tags example, few optimizations

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#219]
From Week 13 Foobooks progress, Part B
https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/99_Foobooks_Lecture_13b.md

I can think of following optimization

$tagsForCheckboxes is already a list of all tag id and name pairs. This list displays tag names for selection

Therefore, $tagsForThisBook can be list of Ids alone (no names). The query on id column is faster. 
I renamed this to $tagIdsForThisBook

Also, note that I can fetch list by using [pluck ](https://laravel.com/docs/5.5/collections#method-pluck)method (terser than foreach loop)
BookController@edit :
```
public function edit($id)
{
    $book = Book::with('tags')->find($id);

    if (!$book) {
        return redirect('/book')->with('alert', 'Book not found');
    }

    $tagIdsForThisBook = $book->tags->pluck('id')->all();

    return view('book.edit')->with([
        'book' => $book,
        'authorsForDropdown' => Author::getForDropdown(),
        'tagsForCheckboxes' => Tag::getForCheckboxes(),
        'tagIdsForThisBook' => $tagIdsForThisBook
    ]);
}
```

tagsCheckboxes.blade.php:
Note that in_array is only comparing tag id values existing on this book with those from all available tags.
I also included changes from https://github.com/susanBuck/dwa15-fall2017/issues/218 
```
<div class='tags'>
    @foreach ($tagsForCheckboxes as $id => $name)
        <input
            type='checkbox'
            id='{{ "checkbox_".$id }}'
            value='{{ $id }}'
            name='tags[]'
            {{ (isset($tagIdsForThisBook) and in_array($id, $tagIdsForThisBook)) ? 'CHECKED' : '' }}
        >
        <label for='{{ "checkbox_".$id }}'> {{ $name }} </label> <br>
    @endforeach
</div>
```

Finally, in the Show blade, we can show the list of tag names as comma separated by this simple command. The controller doesn't have to pass any additional objects to the show view (just $book is enough)

BookController.php (No change):
```
public function show($id)
{
    $book = Book::find($id);

    if (!$book) {
        return redirect('/book')->with('alert', 'Book not found');
    }

    return view('book.show')->with([
        'book' => $book
    ]);
}
```

portion of show.blade.php:
Note, how pluck command here eliminates the need to manually loop through the list
`<p> {{ implode(', ', $book->tags->pluck('name')->all()) }} </p>`

![image](https://user-images.githubusercontent.com/25366909/33806922-200052ba-dd9d-11e7-8fd1-f18f7d59f5aa.png)

**Comment by davida26** [comment]
Good find, took a look at the codebase itself - I was curious to see the internals.

https://github.com/laravel/framework/blob/f7581cdc66bf2c301c0131984f1ca168be4facde/src/Illuminate/Support/Arr.php#L377  - similar to the code provided. Certainly more compact 👍 

and the builder usage (Eloquent/Query):

https://github.com/laravel/framework/blob/a570041875fa4b114909da53bcb8b5133b1730fa/src/Illuminate/Database/Eloquent/Builder.php#L673

https://github.com/laravel/framework/blob/8ea42bae95b094133aae92adca926c9fa1180ef3/src/Illuminate/Database/Query/Builder.php#L1888

**Comment by susanBuck** [comment]
Interesting alternative approaches to consider. There's something really satisfying about refactoring code into terser expressions.

(Note that I purposefully avoid some of this terser syntax for pedagogical reasons, not because one way is better/worse.)
