### ISSUE TITLE
Checkboxes Label Error 

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#221]
I created a label and checkboxes for my project, the same as tags checkboxes were implemented in lectures (we put checkboxes in the separate blade.php file), but during w3 validation I am getting this error. It does not give an error in Foobooks, but it does in my code. It bothers me... Any ideas?
Also, for attribute usually refer to the id of the element, but we don't have id for checkboxes in tags at all. What does it refer to (for = "tags")?

![image](https://user-images.githubusercontent.com/31451809/33813707-38614fa0-ddeb-11e7-95d1-0e55cba80507.png)

**Comment by ysrinu** [comment]
@dianakleban do you have an html element with id="courses"? Can you paste the generated html code for that label and related element?

**Comment by gvardany** [comment]
Correct, `for` attribute of the label has to refer to the `id` of your `input` element.

**Comment by dukesnuz** [comment]
@dianakleban  I found this on [stackoverflow.](https://stackoverflow.com/questions/6293588/how-to-create-an-html-checkbox-with-a-clickable-label)

**Comment by ysrinu** [comment]
@dianakleban  This is a very fundamental and basic html syntax.

If you haven't taken any HTML5/CSS3 course, I would strongly suggest taking this course [CSCI E-12 Fundamentals of Website Development](https://www.extension.harvard.edu/academics/courses/fundamentals-website-development/21144)
and also [CSCI E-3 Introduction to Web Programming Using JavaScript](https://www.extension.harvard.edu/academics/courses/fundamentals-website-development/21144)
I did the above 2 courses in my first semester at HES !

**After** the above 2 courses, if you want to do web programming using frameworks like Flask, Django, and Bootstrap, then course [CSCI E-33A Web Programming with Python and JavaScript](https://www.extension.harvard.edu/academics/courses/web-programming-python-javascript/25184)

**Comment by dianakleban** [comment]
I definetely know the syntax for the checkboxes being a developer for more than 15 years. I took all these courses too. What I am saying is that in the lecture, foobooks code, I don't see id(s) for the checkboxes (I see type, name, value, but no id, unless I miss it somewhere), but the label references for="tags", how does it work for foobooks?
![image](https://user-images.githubusercontent.com/31451809/33841636-50ef3782-de66-11e7-85db-ee8a29440f05.png)
![image](https://user-images.githubusercontent.com/31451809/33841618-46c66172-de66-11e7-89dd-563e80c62efc.png)

**Comment by ysrinu** [comment]
@dianakleban sounds great. I guess our lecture notes are more focused towards the functional part of PHP app, so can understand if not accurate with html5.
For group checkboxes, please see if this helps https://github.com/susanBuck/dwa15-fall2017/issues/218

**Comment by susanBuck** [comment]
@ysrinu It's a little harsh to tell a classmate they need to take more classes when they ask a question. Let's be kind to one another - we're all here to learn and we all come with different experience levels/backgrounds; we should aim to help each other in a way that doesn't make anyone feel like their questions are silly. 

To the question at hand:

```php
<label for='tags'>Tags</label>
@include('book.tagsCheckboxes')
```

This is a consequence of copy/pasting. All the other form fields on the page had `<label for='x_link'>* x </label>` so when I created tags, I copy/pasted that format and failed to go back and correct it. 

The labels should apply to each checkbox item, as @ysrinu pointed out in #218 and I have [fixed in foobooks](https://github.com/susanBuck/foobooks/commit/1932f5028340c46a62bf33e39f7542aecd7da561).

The appropriate HTML element for the *Tags* heading that comes before the checkboxes would be a `legend`.

```html
<legend>Tags</legend>
```

Apologies for any confusion my faulty code might have caused.

**Comment by dianakleban** [comment]
Thank you for your kind explanation. I appreciate it!
Even though I am not using it, I am also wondering about validation. Because of the group checkboxes here, how do you reference it for validation if you want to make it a required field? And how do you connect the error result to the legend?

**Comment by susanBuck** [comment]
You can use the same error module we used for the other fields, setting the `fieldName` to `tags`:

```php
@include('modules.error-field', ['fieldName' => 'tags'])
```
(Note it's just `tags` even though the name on the checkboxes is technically `tags[]` to group them together).

The error can be included right below the legend, or right below the checkbox options, up to you.

Then add a `required` rule to your validation for the `tags`, e.g.,:

```php
$this->validate($request, [
            'title' => 'required|min:3',
            'author' => 'required',
            'published' => 'required|min:4|numeric',
            'purchase_link' => 'required|url',
            'cover' => 'required|url',
            'tags' => 'required', # <-- NEW
        ]);
```

When testing the above procedure, it looked like this when no tags were selected:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/237711/33856801-4da99eec-de97-11e7-8783-4cd5277dcfc8.png">
