### ISSUE TITLE
The page has expired due to inactivity.   Please refresh and try again.

### ISSUE THREAD

**Issue by tericson1** [susanBuck/dwa15-fall2017#222]
My forms had been working fine - I made some updates then all of a sudden I keep getting the error 
The page has expired due to inactivity. 

Please refresh and try again.

or "woops looks like something went wrong" 

 I tried changing around the way I am using the crsf tokens but no luck, cleared cache, cleared artisan cache etc. 

Here is an example form: 
    <form method='POST' action='/balval'>
      {{ method_field('put') }}
      {{ csrf_field() }}
      <div>
        <br>
        <label for="amount">Today's Balance <strong>REQUIRED</strong></label>
        
        <input type="text" id="amount" name="amount" >
      </div>
      <br>
      <div>
        <label for="date">Today's Date <strong>REQUIRED</strong> </label>
        
        <input type="text" id="date" name="date" value ='2017-12-10'>
      </div>
      <br>
      <input type = 'submit' class = 'btn btn-primary btn-small' value = 'Post'>
      <br>
      <br>
    </form>

Route: Route::post('/balval', 'MoneyController@balanceval');

Controller: 
  public function balanceval(Request $request)
  {
    $this->validate($request, [
      'amount' => 'required|min:1|numeric',
      'date' => 'required|date',
    ]);
    $balance = new Balance();
    $balance->amount = $request->input('amount');
    $balance->date = $request->input('date');
    $balance->save();

    return view('balance');
  }

No errors are being written to the lavarel logs

**Comment by dukesnuz** [comment]
Do you have an opening ```form``` element?

**Comment by tericson1** [comment]
I do - must have mis copied and pasted .should show: 

    <h2> Today's Balance </h2>
    <form method='POST' action='/balval'>
      {{ method_field('put') }}
      {{ csrf_field() }}
      <div>
        <br>
        <label for="amount">Today's Balance <strong>REQUIRED</strong></label>

        <input type="text" id="amount" name="amount" >
      </div>
      <br>
      <div>
        <label for="date">Today's Date <strong>REQUIRED</strong> </label>

        <input type="text" id="date" name="date" value ='2017-12-10'>
      </div>
      <br>
      <input type = 'submit' class = 'btn btn-primary btn-small' value = 'Post'>
      <br>
      <br>
    </form>

**Comment by dianakleban** [comment]
Maybe your page is cached. Try to use Ctr-F5 to refresh it.

**Comment by tericson1** [comment]
Unfortunately no luck with that ether

**Comment by ysrinu** [comment]
@tericson1 It most likely means the csrf token is not working. Check for html5, css3 errors, an incorrectly formed html might not run the csrf code.

**Comment by tericson1** [comment]
yea that's what online forms seemed to indicate, and I've toyed around with that but can't seem to pinpoint. I checked the html just now as well, some issues to correct but didn't seem to be anything related. thanks for the suggestions. 

Here is my latest release if anyone wants to take a peak http://p4.tracyerxn.me/

**Comment by ysrinu** [comment]
@tericson1 
http://p4.tracyerxn.me/1/edit
shows `Page Not Found`. Is this the error you are trying to debug? If not, can you provide a link that we should submit to debug your issue?

**Comment by davida26** [comment]
Can you post your routes. How does that look for put?

**Comment by tericson1** [comment]
@ysrinu Click the buttons to fill out any of the forms (Today's balance, Bills, or Incomes) and they should validate, but instead will take you to either a method not found or a page expiration error 

@davida26 I think something could be off about the routes, but I didn't change them and it had been working 

This is what I have for the first form (Today's Balance), I have routes for the other forms that follow the same logic to other methods

Route: Route::get('/balval', 'MoneyController@index');
Route: Route::post('/balval', 'MoneyController@balanceval');

**Comment by davida26** [comment]
@tericson1  - I think your issue is here:

```php
Route: Route::post('/balval', 'MoneyController@balanceval');
```
but your form is saying PUT

```php
<form method='POST' action='/balval'>
  {{ method_field('put') }}
```

Remember the method_field overrides the POST

So you can either add a new route or modify that. Let me know if that solves your issue,

**Comment by tericson1** [comment]
thank you @ysrinu @davida26!! i figured it out. it was a combo of the method issue @davida26  pointed out and I somehow had overwritten printing out form errors so I added that back in, fixed the method, and it resolved the issue.
