### ISSUE TITLE
Authentication - password reset error

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#223]
On submitting /password/reset for password reset, I get error for the file \vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php
```
$this->throwException(
    new Swift_TransportException(
        'Expected response code '.implode('/', $wanted).' but got code '.
        '"'.$code.'", with message "'.$response.'"',
        $code)
    );
```

error message:
`Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required\r\n`

I cleared [cache](https://laracasts.com/discuss/channels/laravel/swift-transportexception-in-abstractsmtptransportphp-line-162-cannot-send-message-without-a-sender-address)
`php artisan config:cache`

but issue is not resolved. I did not modify /config/mail.php

**Comment by davida26** [comment]
How does your mail.php file look like? Don't share the sensitive info but I would check there first.

Check your .env file as well to make sure the username, password, etc is correct.

I use [mailtrap.io](https://mailtrap.io/) to test locally.

**Comment by ysrinu** [comment]
@davida26 Many thanks for the https://mailtrap.io/ 
I simply had to set the username and password in the .env file
Now, for an actual mail to be sent out, should we configure the smtp to our email service provider (and update username/password)?

@susanBuck If we had authentication, is it okay if the reset password functionality doesn't work?

**Comment by davida26** [comment]
@ysrinu yea you can configure to any smtp service. Can even make a separate gmail account and use those settings.

[Here ](https://www.digitalocean.com/community/tutorials/how-to-use-google-s-smtp-server)is an article with the configs.

**Comment by susanBuck** [comment]
@ysrinu Yup, its okay if password resets are not functioning.

If you do want them to function, I suggest using <https://www.mailgun.com> as they offer free sandbox plans you can play around with.

Like @davida26, I also recommend <http://mailtrap.io> when working locally. For those unfamiliar with it - it takes all outgoing email (no matter to what address) and pipes it into a mock/development inbox. This lets you test all of your features that send emails without fear of accidentally blasting your real audience's email addresses.

If anyone needs help setting up mailgun and/or mailtrap, let me know. Happy to put together some notes.

**Comment by susanBuck** [comment]
Another quick/dirty way to get emails working while in development -

In `config/mail.php` change the driver to `log`. Then it will just pipe any outgoing emails to a log file instead of sending them. It's not as nice as [mailtrap.io](http://maitrap.io), but convenient if you don't feel like registering with a new web service.

**Comment by susanBuck** [comment]
Closing this thread as I believe the original question has been answered, but feel free to keep the discussion going if needed.
