### ISSUE TITLE
Date time picker with javascript

### ISSUE THREAD

**Issue by gvardany** [susanBuck/dwa15-fall2017#224]
I need to store date and time for the items in my application. (not the creation/update time)
The goal is to have a graphical date time picker in the form.

HTML5 offers input type data, time and datetime-local, but these are not supported by all the browsers. It seems only Chrome and Edge do. So this is not a solid solution.

The other option is to have a javascript-powered picker. jQuery has a UI plugin for date picker but not for time picker.

So I was wondering if someone could recommend some other js plugin that has also a time picker, or better, date time picker all in one.

The criteria of course, it should be plug-n-play, and cross-browser.

I have encountered some custom plugins, but I'm unsure if they are cross-browser.

**Comment by SridharSubramaniam** [comment]
Few options: if you use bootstrap for your app, there are multiple options like bootstrap-datepicker,

Otherwise, i have used this jquery plugin in the past successfully. http://amsul.ca/pickadate.js/

**Comment by stbenjam** [comment]
The simplest solution would probably be just a text input, with a placeholder of HH:MM:SS and then use a Laravel validation on it (simple regex would do).

**Comment by zeroender** [comment]
It looks like a custom add-on for Jquery UI exists that has a datetimepicker http://trentrichardson.com/examples/timepicker/

There is also at least one on packagist 
https://packalyst.com/packages/package/anomaly/datetime-field_type

However I'd suggest either the bootstrap or html solution - simplest = best.

**Comment by ysrinu** [comment]
I used boostrap 4 for my project. DateTime was easy by setting the textual input
https://v4-alpha.getbootstrap.com/components/forms/#textual-inputs

```
<div class="form-group row">
  <label for="example-datetime-local-input" class="col-2 col-form-label">Date and time</label>
  <div class="col-10">
    <input class="form-control" type="datetime-local" value="2011-08-19T13:45:00" id="example-datetime-local-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-date-input" class="col-2 col-form-label">Date</label>
  <div class="col-10">
    <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
  </div>
</div>
```

**Comment by gvardany** [comment]
Thanks all for the suggestions. I ended up using [this](https://xdsoft.net/jqplugins/datetimepicker/), since it is very nice and powerful and easy to integrate.
