### ISSUE TITLE
Adding a favicon asset in Laravel?

### ISSUE THREAD

**Issue by peggyo** [susanBuck/dwa15-fall2017#225]
My favicon is working locally, but I am having trouble on production. First, my ico file was not included when I pulled from github. I found similar reports online, but most were not helpful. I found this <http://blog.stickyrice.net/archives/2014/how-to-change-your-laravel-site-favicon> so tried it in my master layout. It worked locally, too, but the code `< link rel="shortcut icon" href="{{ asset('favicon.ico') }}" >` actually appears at the top of the rendered page. I decided to put it on production to see if it would pull the icon file to the project, and then I could remove the code and redeploy my master layout. That did work to move the file to production, and it still seems to work on the page when I use Chrome, but it does not work with Firefox on production. I have even restarted the apache server to clear everything out, but no luck. The file is in my public folder.

**Comment by peggyo** [comment]
Sorry, I forgot about browser caching. During development I've had less problems with browser caching using firefox over chrome, but that was my problem.

I think there must be a better way to add an asset to the project than my workaround of adding and then removing an explicit reference, so will leave open in case of suggestions. I looked through Laravel docs on assets, and the answer must be there, but I failed to find it.

**Comment by susanBuck** [comment]
For reference, here are the the notes/procedures I use when working with favicons.

## Creating favicon files
Using your preferred graphics program, create a 16px x 16px icon and save it as a typical image format - .png or .jpg.

Convert this file to a `.ico` file using some online tool like [favicongenerator.com](http://www.favicongenerator.com)

## Where to put favicon files
Favicon files (`.ico`)  are a client asset (i.e. a file the browser needs access to) and thus they should be placed in `public/`.  

Traditionally, favicons are placed in the "root" of your web accessible directory (for Laravel, that's `public/`. 

It's less typical to see favicons placed in some subdirectory like `/public/images/favicons/`. (I think this has to do with where certain browsers look for favicons by default?)

## Code to use the Favicon
The code to use icon files should go in the `<head></head>` of your master layout.

You can use Laravel's [`asset`](https://laravel.com/docs/5.5/helpers#method-asset) helper for this (as noted in the blog you linked to):
```php
<link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
```

This is effectively the same as:
```php
<link rel="shortcut icon" href="/favicon.ico">
```

## Troubleshooting
I've found Icon files sometimes cache a little differently than typical assets on a page. I've had the experiencing of changing a icon file, refreshing the browser cache, but still seeing the old icon. Things to try when this happens:

+ Close and restart the browser
+ Test it in a different browser

I've never had the experience of Git not recognizing an .ico file so I can't speak to that.

**Comment by peggyo** [comment]
Thanks! I double checked the change to my master layout, and it appears that the method you outline is what I had followed, but it resulted in the text of the link showing up at the top of my pages. If time permits I will experiment, but it seems to be working for now.

**Comment by susanBuck** [comment]
Ah, I see what you mean now - I just copied the code from the blog you linked to, added it to foobooks, and it does show at the top of the page.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/237711/33853433-eed199e8-de8b-11e7-8785-81bea58ba313.png">

I also noticed the syntax highlighting appeared off:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/237711/33853455-05d67e4c-de8c-11e7-95cd-38b466cf6dbd.png">

It's not happy about the spaces at the start and end.

This:
```php
< link rel="shortcut icon" href="{{ asset('favicon.ico') }}" >
```

Should be:
```
<link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
```

**Comment by HeinrichTremblay** [comment]
Quick tip for the Favicon! Sometimes it doesn't update due to browser cache, if this happen you can force a refresh by adding a query string to it.

```php
<link rel="shortcut icon" href="{{ asset('favicon.ico') }}?v=2">
```

BUT!

It seems that MAMP override the favicon, you have to either be in production to see your own or do a trick into MAMP's configuration. I tried from this [tutorial](http://timneill.net/2012/02/reclaiming-your-favicons-using-mamp/) and it work like a charm! The steps for mac are:

1. Stop MAMP Apache server.
2. In finder `Go to Folder` and type `/Applications/MAMP/conf/apache/httpd.conf`.
3. Open it up in your text editor (Atom).
4. Find this line and comment it with a `#` then save: `Alias /favicon.ico "/Applications/MAMP/bin/favicon.ico"`.
5. Clear your browser cache.
6. Start MAMP Apache server.

Hope it helps!
