### ISSUE TITLE
Production URL

### ISSUE THREAD

**Issue by peggyo** [susanBuck/dwa15-fall2017#226]
With the link to our production URL now included in the readme of our github repository, is it still your preference that we use `p4.domainname.com` ?  Or is something like `foobooks.domain.com` acceptable if the link is easily accessible in our github repository?

**Comment by susanBuck** [comment]
I'd prefer if you stick to the convention (`p4.domain.com`).

If there's a particular reason you need to/want to diverge from this convention, email me and I can make a case-by-case exception.

**Comment by ysrinu** [comment]
@peggyo @susanBuck 
We can create alias. Create new A type records in your DNS (namecheap).
In your /etc/apache2/sites-enabled/000-default.conf file, have both p4 and foobooks (for example) to point to the same DocumentRoot and Directory. 
After the changes to the config file, restart apache server

**Comment by peggyo** [comment]
@ysrinu 
Thanks - I already did that. I am just not sure whether it matters as far as my repository, and the path, given that @susanBuck will be cloning the repos to a local machine for testing. If it's only the production URL, it's no problem for me.
