### ISSUE TITLE
Adding a A Column to The Users Table

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#227]
@susanBuck 
### Scenario
I added a column to the users table. This error was produced ```SQLSTATE[HY000]: General error: 1364 Field 'last_name' doesn't have a default value```.  
### Answer
What fixed this was found in [Eloquent create says column has no default value](https://laravel.io/forum/08-08-2015-eloquent-create-says-column-has-no-default-value)
If you scroll to the bottom see this post
>I had the same problem in Laravel 5.3 . In my case I changed the config/database.php file updating the value of 'strict' to false and it worked properly.

### Question
What exactly does changing ```strict``` to ```false``` do?  Would this cause and security issues?

**Comment by ysrinu** [comment]
Please check these docs

Strict SQL Mode
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict

Comparison of the IGNORE Keyword and Strict SQL Mode
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#ignore-strict-comparison

5.1.8 Server SQL Modes
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html

**Comment by ALiborio** [comment]
Did changing it from `strict` to `false` fix your problem?
I don't know exactly what that does, so I'm not sure if it's the answer to your problems.

However, the error you're receiving is basically saying there is no default value for `last_name` and it's not getting set. If the field was set to `nullable`, then you would not need to set it as the default value would be `null`

Can you post your migration for the users table or link to your repo if it's committed.
Also can you post your seeder or the code which is generating the error when trying to add the last_name.

**Comment by dukesnuz** [comment]
@ysrinu Great information
@ALiborio 
Yes changing strict to false fixed the issue.

Here is my[ migration for users](https://github.com/dukesnuz/p4/blob/master/database/migrations/2014_10_12_000000_create_users_table.php).

The error happens when I register at ```http://p4.loc/register```

No errors with migrations nor seeders.

**Comment by dukesnuz** [comment]
I went back and changed strict to true and now it is working. Strange.  Was definitely not working earlier. Must be as a result of opening this thread. Happened to me before. Get errors and cannot figure solution. Post issue here. Go back and work on issue. **Bam**  issue is resolved. :+1:
