### ISSUE TITLE
Privacy Error in Chrome on local pages

### ISSUE THREAD

**Issue by ALiborio** [susanBuck/dwa15-fall2017#228]
This may have been triggered by a recent Chrome update (I recall being prompted a couple days ago that it needed to be updated) but suddenly all my projects locally (`p1.dev`,`p2,.dev`,`p3.dev`, and `p4.dev`) are giving me a Privacy error in Chrome [Version 63.0.3239.84 (Official Build) (64-bit)].

> Your connection is not private
Attackers might be trying to steal your information from p4.dev (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

Firefox and Edge show a warning if I click the info button in the address bar but allow me to go on.  Production [p4.adamliborio.com](http://p4.adamliborio.com/) works just fine. `localhost` itself works (just a hello world page).

I don't think it's laravel related since p1 and p2 also are having this problem. It must be my local web server.

Anyone else run into this?

**Comment by susanBuck** [comment]
I just read an article about this: Latest Chrome forces HTTPS connections for .dev extensions.

<https://laravel-news.com/chrome-63-now-forces-dev-domains-https>

Quickest solution is to switch to an alternative extension for your local/development sites.

**Comment by ALiborio** [comment]
Thanks for sharing that. That definitely explains it.
I will change my extension and/or switch over to Firefox.

**Comment by susanBuck** [comment]
I've recently made the switch to Firefox myself. Their most recent release (Quantum) is completely overhauled and [performs well in speed tests vs. Chrome](https://www.laptopmag.com/articles/firefox-quantum-vs-chrome).

I figure Google already has enough outlets to collect data on me, don't need them to have my browsing data as well. : )
