### ISSUE TITLE
Integrating tags in index.php using PHP

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#23]
I'm having a really hard time integrating html tags, into my index.php file, using php. 
I have two files:
- index.php - contains my form
- helper.php - contains a variable $split, which is iniatlized inside an if statement, if _GET is initialized
```
$info = $_GET;
if(isset($info[0])) {
    $split = $info["Total_Price"];
    $ini = true;
    #var_dump($split);
} 
```

I'm trying to print under the form a <p> tag with the value of one of the items in the form.  I've tried, various methods and nothing seems to work

```
<?php
        echo '<p>$split</p>';
?>
```
Returns $split

********
```
<?php
        echo '<p><? echo $split ?></p>';
 ?>
```
Doesn't return anything, even when I submit information into the form

**Comment by stbenjam** [comment]
Use double quotes not single quotes, because they have different meanings.  If you put something in single quotes, it's treated literally - no additional processing happens.   If you use double quotes then PHP will look and replace $split with a variable.

```php
<?php
    echo "<p>$split</p>";
?>
```

FWIW, I prefer not to include HTML in PHP if I can  avoid it.  I think this looks better

```php
<p><?= $split ?></p>
```

**Comment by stbenjam** [comment]
There's a long discussion of the different ways you can write strings in PHP in the manual http://php.net/manual/en/language.types.string.php

**Comment by APuente21** [comment]
Thanks, but it still doesn't work. When I first load the page, it says the variable is undefined, which I get because I haven't submitted anything to the form. But, once I fill out the form and submit it, I would expect to get the value, which I don't, why is that?

**Comment by stbenjam** [comment]
You get the same error about it being undefined? Sounds like your if block may not be working.  The isset on a numeric index of `$info` seems odd, why not access it with the key Total_Price?

**Comment by susanBuck** [comment]
I would recommend doing a `var dump` of `$_GET` and making sure there's actually a `Total_Price` index in there.

I also echo @stbenjam's question: Why `isset($info[0])` and not `isset($info['Total_Price'])` ? 

Regarding string output, @stbenjam's suggestion of the following is the preferred way when outputting in HTML:
```php
<p><?= $split ?></p>
```

Single quotes can be used, but you have to concatenate (with the period symbol) the strings and variables.
```php
<?php echo '<p>'.$split.'</p>';?>
```

Or double quotes where no concatenation is necessary and you can mix strings and variables:
```php
<?php echo "<p>$split</p>";?>
```

**Comment by APuente21** [comment]
Thanks!
