### ISSUE TITLE
Subquery - In Clause with Filter - Any further optimization here?

### ISSUE THREAD

**Issue by SridharSubramaniam** [susanBuck/dwa15-fall2017#230]
Hi Peeps,

Do you see an opportunity to optimize this in a single query? Current it does 2.

1. Lookup Taxonomy for id with api_name = 'category'
2. Find all terms with that taxonomy. 

Typical one-to-many, additional filter on parent instead of an actual object. Appreciate any pointers. Thanks!

```php
$taxonomy_id = Taxonomy::where('api_name', '=', 'category')->pluck('id')->first();

// Query All terms with taxonomy = 'category'
$terms = TaxonomyTerm::with('taxonomy')->where('taxonomy_id', '=', $taxonomy_id)->get();
```

**Comment by SridharSubramaniam** [comment]
Further simplified with this, but still runs two queries. 

 $terms = Taxonomy::with('taxonomy_terms')->where('api_name', '=', 'category')->get();

Queries:
select * from `taxonomies` where `api_name` = 'category'
select * from `taxonomy_terms` where `taxonomy_terms`.`taxonomy_id` in ('1')

**Comment by ysrinu** [comment]
From the 2nd post, I would think that eloquent would run an inner join statement instead of 2 statements. For example:
SELECT * from taxonomies x, taxonomy_terms r
INNER JOIN x.id = r.taxonomy_id
WHERE x.api_name='category'

When the data set or the carnality of the tables is large, the inner join is much efficient (provided the join is on indexed columns)

**Comment by susanBuck** [comment]
@SridharSubramaniam - I'm not aware of any ways to further optimize your Eloquent query/statement.

You could streamline it to 1 query by using the DB query builder and doing a join, as @ysrinu suggests. 

When we look at cases like this - comparing Eloquent's approach to a more SQL-y approach, there are pros and cons to both.

Eloquent might not always do things as efficient as you can do in raw SQL.
That's not to say Eloquent is always inefficient, it just might not always be *as* efficient.
The inverse might also be true - sometimes it is actually more efficient to do 2 queries if you're working with complex joins. 

If you're working with a large site (lots of data, many users), benchmark tests can be run to help compare different approaches.

The question may still remain, though, of why use Eloquent when we can construct SQL queries in ways we know are optimal? Reason: it makes development more convenient:
+ readability/maintainability
+ security (e.g. parameter binding behind the scene to prevent against SQL injection attacks)
+ portability (can quickly change DB drivers, using the same code)

**Comment by SridharSubramaniam** [comment]
Thank you. It make sense!
