### ISSUE TITLE
Preferred state for data on production at time of project submission?

### ISSUE THREAD

**Issue by peggyo** [susanBuck/dwa15-fall2017#231]
Should we run `php artisan migrate:fresh --seed` to have our production site in that state when we submit our projects, or is it okay to leave more (or less) data we've been using while testing the site?

**Comment by susanBuck** [comment]
You should leave the site in what you think is its "optimal state" for presenting. This probably entails running fresh migrations/seeds before submitting. Whether you add/remove data beyond that is up to you.
