### ISSUE TITLE
Validation rule for image URL 

### ISSUE THREAD

**Issue by sheetaldalvi** [susanBuck/dwa15-fall2017#232]
In foobooks example, we accept cover image as url in the "add a book" form and validate that input against "required|url" rule.

 Is there any way to check if the input url is actually an image file and not a malicious script? I tried to use it along with "mime:jpeg" and "image" validation rules, but did not succeed. 

Can we use regular expression in this case?

**Comment by susanBuck** [comment]
The mime related validation rules should be what you're looking for.
Can you elaborate on how it didn't succeed - error messages? it let non-images pass?
Can you share the code you used?

Not sure regexp is the answer here - that could be used to verify the name of the image is image-like, but a malicious script could be disguised as a legit image path.

**Comment by sheetaldalvi** [comment]
The code for input acccepting image files is 
<div class='form-group row'>
        <label for='image' class='col-sm-2 col-form-label'>Image location</label>
        <div class='col-sm-10'>
          <input type='file' class='form-control' name='image' id='image' accept='image/*'>
          @include('partials.error', ['elementName' => 'image'])
        </div>
      </div>

Validation rule  is 
'image' => 'required|url|mimes:jpeg'

Error : The image format is invalid. 

I'm not sure if we can use url validation rule along with mime type. Earlier I had used different validation rule : 'image' => 'required|url|image' that gave me same error "The image format is invalid. "

**Comment by sheetaldalvi** [comment]
The form input accepting image files is,
  \<div class='form-group row'>
        \<label for='image' class='col-sm-2 col-form-label'>Image location</label>
        \<div class='col-sm-10'>
          \<input type='file' class='form-control' name='image' id='image' accept='image/*'>
          @include('partials.error', ['elementName' => 'image'])
        \</div>
      \</div>

Validation code in controller is : 'image' => 'required|url|mimes:jpeg',

I had selected .jpg file for testing 
Error : The image format is invalid.

earlier I had tried with validation rule :  'image' => 'required|url|image',
but received the same validation error message

**Comment by susanBuck** [comment]
The `mime` validation rule can be used for validating **images (files) that are uploaded**, not checking URLs. 

(In my first read of your post, I jumped to the conclusion that you were uploading images; sorry about that!).

Perhaps the best option here is a custom validation rule that:
1. Uses a regexp rule to validate the path looks like a valid image - i.e. it ends in .jpg, .png, .gif, .jpeg, etc. 
2. Uses PHP to check if the path is to a valid image (e.g.: http://www.binarytides.com/php-check-if-file-is-an-image/)

I'm going to write up a quick test of this. Will post again with some sample code.

**Comment by susanBuck** [comment]
## Instructions
Create a new [custom validation rule](https://laravel.com/docs/5.5/validation#custom-validation-rules): `php artisan make:rule ValidImage`

In the resulting file `app/Rules/ValidImage.php` update the `passes` method to the following (comments included to explain what it's doing).

```php
public function passes($attribute, $value)
{
    # First do a regexp test to make sure the path includes a valid image extension.
    # Could probably skip this step since the second test will also validate for this
    # But it's arguably more "economical" to not check the image if the path is not valid
    $pattern = '/[\w\-]+\.(jpg|png|gif|jpeg)/';
    $patternMatches = preg_match($pattern, $value);

    if (!$patternMatches) {
        return false;
    } else {
        # Next try and get details about the image using PHP's getimagesize function
        # If it can't load the image, this will throw an exception. We use a try/catch
        # to return false if that exception is thrown.
        try {
            $a = getimagesize($value);
            $imageType = $a[2];
            $imageTypes = [IMAGETYPE_GIF, IMAGETYPE_JPEG, IMAGETYPE_PNG, IMAGETYPE_BMP];
            $validImage = in_array($imageType, $imageTypes);
        } catch (\Exception $e) {
            return false;
        }
    }

    # If we made it this far, we know the image is valid, so return true
    return true;
}
```

To use this custom validation rule:
```php
use App\Rules\ValidImage;

# [...]

$request->validate([
    'name' => ['required', new ValidImage],
]);
```

I wanted to test it without having to set up a sample form, so I ran the following code in the PracticeController to "manually" test it:

```php
/**
* https://github.com/susanBuck/dwa15-fall2017/issues/232
*/
public function practice32()
{
    # Instantiate our custom validation rule to test
    $validImage = new ValidImage();

    # The paths we'll test
    # The boolean value for each path indicates whether the validator should pass/fail
    $tests = [
        'http://foobooks.dwa15.me/images/laravel-foobooks-logo@2x.png' => true, # Valid image
        'http://foobooks.dwa15.me/images/laravel-foobooks-logo@2x.text' => false, # Invalid image
        'http://foobooks.dwa15.me/images/foobar.png' => false, # Invalid image
        'foobar.png' => false,
    ];

    # Run each test
    foreach ($tests as $path => $expected) {
        # Invoke the validator for this path
        $results = $validImage->passes('image', $path);

        # Compare the results
        if ($results == $expected) {
            $isOrIsNot = ($expected) ? ' is' : ' is NOT';
            dump('✓ Test passed; detected that '.$path.$isOrIsNot.' a valid image URL.');
        }
    }
}
```

Results when run:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/237711/33964118-660c8b4a-e025-11e7-97b0-1fd837e63441.png">



## References
+ <https://stackoverflow.com/questions/19168307/preg-match-and-images-url>
+ <http://www.binarytides.com/php-check-if-file-is-an-image/>

***

Is this accomplishing what you were looking for? If not, let me know and we can adapt it. Also let me know if it's unclear what any of the above code is doing.

**Comment by sheetaldalvi** [comment]
Thanks Susan. This is exactly what I wanted to accomplish. 

Tested it for all my test cases and works great!

Adding one more ref : http://php.net/manual/en/function.getimagesize.php
