### ISSUE TITLE
Error with Many to Many seeder

### ISSUE THREAD

**Issue by drumph33** [susanBuck/dwa15-fall2017#233]
So I went back through to add a many to many relationship and was using tags like in foobooks.   Its giving me an error

```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::save() must be an i
  nstance of Illuminate\Database\Eloquent\Model, null given, called in C:\xampp\htdocs\p4\database\seeds\Sco
  reTagTableSeeder.php on line 39
```

Which seems to suggest that I am not passing in a model object...but I am not sure what would be causing it.  I have models for both Score and Tag.  The manytomany relationship has been defined in both.

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Score extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function tags()
    {
        return $this->belongsToMany('App\Tag')->withTimeStamps();
    }
}
```
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function scores()
    {
        return $this->belongsToMany('App\Score')->withTimestamps();
    }
}
```
```
<?php

use Illuminate\Database\Seeder;
use App\Score;
use App\Tag;

class ScoreTagTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $scores =[
            2 => ['diet, family'],
            3 => ['weekend', 'exercise', 'weather'],
            4 => ['finances', 'alcohol'],
            5 => ['family', 'exercise'],
            6 => ['job', 'alcohol', 'weather'],
            7 => ['relationship', 'finances', 'family'],
            8 => ['relationship', 'family', 'finances', 'holiday'],
            9 => ['diet', 'weekend', 'weather'],
            10 => ['alcohol', 'job']
        ];

        foreach ($scores as $id => $tags) {

     
        $score = Score::where('id', 'LIKE', $id)->first();

        
            foreach ($tags as $tagName) {
                $tag = Tag::where('name', 'LIKE', $tagName)->first();

          
                $score->tags()->save($tag);
            }
        }
    }
}
```

**Comment by EricXDing** [comment]
Um, just taking a guess: did you seed in the right order?

**Comment by rrtx2000** [comment]
When you figure this out please let us know. EricXDings possibility is the only thing I can think of also.

**Comment by ALiborio** [comment]
The error seems to be that you are passing null in to the save method.
Try dumping `$tag` and ensuring it is truly an instance of the Tag model.

It could be like @EricXDing mentioned and they were not seeded in the right order, so `$tag = Tag::where('name', 'LIKE', $tagName)->first();` is not returning anything.

If the order of the seeders is correct, just make sure all the tag names in your array are being seeded in the Tags seeder.

**Comment by drumph33** [comment]
Both the tags and scores tables were already seeded.  The score_tag_table works just fine when data is added to it via the app so its probably not a big deal.  Its just that seeder wouldn't populate it with data.   The Tag facade seems to work elsewhere in the app.  But yeah a dump of $tag probably returns a null.  Ill go check that, but why is it returning a null?

**Comment by ALiborio** [comment]
I see your problem now.

`2 => ['diet, family'],`

should be 
`2 => ['diet', 'family'],`
It's looking for a tag called `diet, family` instead of treating them as separate pieces of the array.

**Comment by drumph33** [comment]
ugh ok haha thanks

**Comment by drumph33** [comment]
Well now its giving this error

```
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function tags() on null
```

**Comment by ALiborio** [comment]
Is $score also null?
I think `$score = Score::where('id', 'LIKE', $id)->first();` should work but you can try this instead since you are searching on the id
`$score = Score::find($id);`

**Comment by drumph33** [comment]
I did a die dump of $score and it returned some data of type App\Score

**Comment by peggyo** [comment]
What if you try with just one row, see if that works, then gradually add more data. Maybe it would help narrow down where the problem happens?

**Comment by drumph33** [comment]
After the first change it was partially working which caused it to do some weird things, maybe because I ran it more than once..but when I edited the method the tags wouldnt update.  I just migrated fresh and left the pivot table unseeded for now since it works fine otherwise.

**Comment by susanBuck** [comment]
@drumph33 I just downloaded a copy of your repository and re-activated the `ScoreTagTableSeeder` seeder and it ran w/o issue. Going to assume you worked out the kinks and close this thread out. Looks like your seeders are all set for grading purposes. 👍

```php
$scores =[
            2 => ['diet', 'family'],
            3 => ['weekend', 'exercise', 'weather'],
            4 => ['finances', 'alcohol'],
            5 => ['family', 'exercise'],
            6 => ['job', 'alcohol', 'weather'],
            7 => ['relationship', 'finances', 'family'],
            8 => ['relationship', 'family', 'finances', 'holiday'],
            9 => ['diet', 'weekend', 'weather'],
            10 => ['alcohol', 'job']
        ];

        foreach ($scores as $id => $tags) {
            # First get the book
            $score = Score::where('id', 'LIKE', $id)->first();

            # Now loop through each tag for this book, adding the pivot
            foreach ($tags as $tagName) {
                $tag = Tag::where('name', 'LIKE', $tagName)->first();
                
                # Connect this tag to this book
                $score->tags()->save($tag);
            }
        }
```

```
~/Sites/_shortcuts/dwa-bash/students/dylan/p4 $ php artisan migrate:fresh --seedDropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2017_11_08_134813_create_scores_table
Migrated:  2017_11_08_134813_create_scores_table
Migrating: 2017_12_13_023012_create_tags_table
Migrated:  2017_12_13_023012_create_tags_table
Migrating: 2017_12_13_030437_connect_users_and_scores
Migrated:  2017_12_13_030437_connect_users_and_scores
Migrating: 2017_12_13_033442_create_score_tag_table
Migrated:  2017_12_13_033442_create_score_tag_table
Seeding: UsersTableSeeder
Seeding: ScoresTableSeeder
Seeding: TagsTableSeeder
Seeding: ScoreTagTableSeeder
```

**Comment by drumph33** [comment]
Hmm thats strange, it never ended up working for me.  Oh well.
