### ISSUE TITLE
Chrome Canvas Issue

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#236]
@susanBuck I attached the last progress log for Week14 today and thought I am all set. I decided to  double check it in the evening. When I tried to download it. I got this error in Chrome. I did not see it in the past. I was able to see and download progress log file in Firefox and IE, but not in Chrome for some reason. In Chrome you can only get it only by right clicking and saving the link. @susanBuck Hope you will be able to see and get the file since it is the most important one for Project 4...
Not sure if this is the problem with my Chrome or canvas issue! 
![image](https://user-images.githubusercontent.com/31451809/33975640-5ac9aab2-e055-11e7-8426-f600d79e788c.png)

**Comment by gregorycoleman** [comment]
I  long as you submitted your PDF on time, you should be OK.

**Comment by susanBuck** [comment]
@dianakleban  Confirming I can see your Week 13 Progress log in Canvas.

**Comment by dianakleban** [comment]
@susanBuck I was talking about the last one, Week 14 Progress Log.

**Comment by susanBuck** [comment]
I meant to say Week 14. I can see both.
