### ISSUE TITLE
(Optional) Share your Project 4...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2017#237]
In the interest of seeing what your classmates came up with, I wanted to start a thread for students interested in sharing their Project 4 URLs. 

Include your production URL for easy access to check out your site.
And the Github repo URL so we can learn from each other's code.

This is completely optional. No pressure.

**Comment by ysrinu** [comment]
Inventory Tracking System

http://p4.srinivasyelamanchili.me/


Use either of the below userids to logon with password 'helloworld' (minus the quotes)
Jill Harvard (jill@harvard.edu)
Jamal Harvard (jamal@harvard.edu)

You can also register as a new user. (Forget password doesn't work though)

**Comment by SridharSubramaniam** [comment]
Live URL: http://p4.sri-hes.me

Repo URL: https://github.com/sriworks/dwa-p4-expense-log
