### ISSUE TITLE
autocomplete-php Error 

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#24]
## Autocomplete-php Plugin Error

Running windows 7
Atom version 1.20.0

I installed autocomplete-php. Did not work and the error message said  ```c:\xampp\php\``` could not be spawned.

Found this [link](https://github.com/Peekmo/atom-autocomplete-php/issues/16) .

Changed path to ```c:\xampp\php\php.exe``` or ```c:\xampp\php\php```  Plugin now works.

## To Install and Manage Packages ##
PC: Click ```Packages``` > ```Settings View```
or
PC: Click ```File``` > ```Settings``` > ```Install```

I do not see a ``` File``` >```Preferences``` path

## Installing linter-php
I used the following path in ```config.cson```
```
"linter-php":
  executablePath: "c:\\xampp\\php\\php.exe"
```

**Comment by peggyo** [comment]
Thank you - I ran into this as well. The solution seems to be working for me.

**Comment by susanBuck** [comment]
Thanks for these tips - I'll amend the notes.

**Comment by dlabelle101** [comment]
avoid simply cutting and pasting the configuration to config.cson. I found it best to type in the commands as the linter config was not being read properly when I used cut n paste to enter the values.
