### ISSUE TITLE
PHP Debugger

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#27]
Is there a tool in the IDE or on the web browser that would allow us to run through our code in debug mode? Eclipse for example has a debugger option that allows you to run through the code, one line at a time, so you can see what value is being passed to each variable - is there an IDE or tool for php that would give us similar functionality?

**Comment by gregorycoleman** [comment]
I would look a XDebug with php-dubug addon for the Atom editor.

**Comment by susanBuck** [comment]
PHP Storm also has this feature: 
<https://www.jetbrains.com/help/phpstorm/php-debugging-session.html>
