### ISSUE TITLE
I can't looad files into DigitalOceal

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#28]
Hello,
I've created a droplet into my Digital Ocean acount (LAMP 16.04).  I have also created a repository in Github, and pushed all my files there. 
Now, in my command line editor I'm entering the following commands

` cd /var/www/html`
` git clone git@github.com:APuente21/TipCalculator.git`

When I do this, I get the following error message

> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

I have my SSH set up on my Digital Ocean account and Github, so I'm not sure why this is not working. Any idea on how I can resolve this?

**Comment by gregorycoleman** [comment]
Seems like you do not have your ssh keys from your D.O. server on GitHub

Take a look at this [SSH Key: DigitalOcean <-> Github.com](https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/07_Deploy_to_DigitalOcean.md#ssh-key-digitalocean---githubcom)

**Comment by gnodar01** [comment]
There's [another issue thread](https://github.com/susanBuck/dwa15-fall2017/issues/20) where someone is having similar trouble. There may be some hints there as well. Hard to tell in your case unless you provide all the steps you've already taken.

**Comment by APuente21** [comment]
I checked Github and I have the SSH set up. I was able to load files last week, without any issues. But, for some reason, it's not working this week. I'm using the same computer as before.

**Comment by APuente21** [comment]
I was able to fix it- I had to remove the SSH that I had set up last week and regenerate a new one. I guess that for every droplet that we create we will need to create a new SSH to GitHub

**Comment by SridharSubramaniam** [comment]
@APuente21 Curious, Why did you have to create a new droplet?
