### ISSUE TITLE
How to tell Apache to ignore files/directories

### ISSUE THREAD

**Issue by gnodar01** [susanBuck/dwa15-fall2017#29]
I realized that since there's a `.git` directory in the Document Root, it might be accessible via url. I tried `p1.mydomain.me/.git` and indeed it showed the contents of the `.git` directory. It's not really concerning, since it's all available on a public Github repo anyway, but out of curiosity, how do we tell Apache to not serve the `.git` directory and other hidden directories and files?

**Comment by gabrielsanna** [comment]
There are a lot of ways you can achieve this in Apache. The easiest is probably to add a `<FilesMatch>` directive to your virtualhost.

If you look in /etc/apache2/apache2.conf, you can see an example of omitting `.htaccess` files from web access:

```
#
# The following lines prevent .htaccess and .htpasswd files from being
# viewed by Web clients.
#
<FilesMatch "^\.ht">
        Require all denied
</FilesMatch>
```

You can copy this by adding the following code to your 000-default.conf file, before the `</VirtualHost>` tag at the end of your site's virtual host entry:

```
<FilesMatch "^\.git">
        Require all denied
</FilesMatch>
```
And restart Apache. You should now get a 403 Forbidden message when navigating to any folder or file called .git.

You can read more here about the FilesMatch directive: https://httpd.apache.org/docs/2.4/mod/core.html#filesmatch
You can also achieve this with .htaccess files, though I generally prefer not to use these: https://stackoverflow.com/questions/19118482/deny-access-to-one-specific-folder-in-htaccess/19118529

**Comment by gregorycoleman** [comment]
I would say usually we don't. Often the ````.git```` repo is one directory **up** from the place where we server files. In the example below, the ````/public```` directory would be your WebRoot and the directories above that would not be accessible.

````
/.git
/public /index.php   <-- server files from the public sub dir
/models
/views
````

**Comment by gabrielsanna** [comment]
But, assuming that .git is in your web root directory...

There are a lot of ways you can achieve this in Apache. The easiest is probably to add a `<Directorymatch>` directive to your virtualhost.

You can do this by adding the following code to your 000-default.conf file, before the `</VirtualHost>` tag at the end of your site's virtual host entry:

```
<Directorymatch "^/.*/\.git/">
Order deny,allow
Deny from all
</Directorymatch>
```
And restart Apache. You should now get a 403 Forbidden message when navigating to any folder or file inside .git.

You can read more here about the FilesMatch directive: https://httpd.apache.org/docs/2.4/mod/core.html#directorymatch
And here's the Q&A where I found the answer: https://serverfault.com/questions/128069/how-do-i-prevent-apache-from-serving-the-git-directory
