### ISSUE TITLE
Possible missing file in dwa15-fall2017/00_Command_Line

### ISSUE THREAD

**Issue by gnodar01** [susanBuck/dwa15-fall2017#3]
The file prefixes in *dwa15-fall2017/00_Command_Line/* go from *00_* to *02_* - *06_*, but there is no *01_*. Should there be a file prefixed with *_01*, or is this intentional?

**Comment by susanBuck** [comment]
Nope, no missing files.

The number prefixes were used for an internal system that displayed the notes, and throughout the semesters as notes have been added/removed/shifted around, some gaps in the numbers were created.

I'll make a note to correct it in future semesters, but don't want to update them now to avoid breaking links. Will keep an eye out for gaps as I publish the rest of the notes this semester.

Thanks for the heads up.
