### ISSUE TITLE
Sanitize data in the logic code

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#30]
In the foobooks0 example, on form submission, sanitize function was used when displaying form field values. However, the logic php code itself doesn't seem to do any sanitization. This means the logic can still work with 'bad' input data while showing 'cleaned' valued in the front end on submission.

On first submission of the form, if a user enters 'malicious' input field values (either using the form itself or as the url string parameters), I would think the logic php code would sanitize before consuming (using) it.

In this example, the value for 'keyword' should be sanitized in the getAllBooks.php
Thanks

**Comment by zeroender** [comment]
My guess is that this week we're focusing on learning how to create the forms and have them send data which PHP can use, and next week we'll look at sanitizing (that was the impression I got from the progress log).  But you are totally correct, the value in keyword was not current sanitized in the lecture videos.

**Comment by susanBuck** [comment]
@zeroender Is correct. In week 4's material we'll validate the data in PHP.
