### ISSUE TITLE
Strings understanding

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#31]
I would like to have further clarity about strings in PHP. 
I noticed that we can use double and single quotes, but I read somewhere that there is some kind of difference. I cannot find this info in our documentation. Which are better to use? Are there particular cases where only one kind of quotes is used? Also, I tried to create a new line for some strings with "\n", "\r\n" and "<br>" and it did not work for me. I tried single and double quotes, it is still not working. Any ideas?

**Comment by ysrinu** [comment]
Scripting languages, in general, surrounding with single quotes will not attempt to evaluate the contents, while double quote will evaluate any variables or escape characters within.
For example,
$x=30
echo '$x' --> output $x
echo "$x" --> output 30

@dianakleban , use <br/> for line breaks.

**Comment by dianakleban** [comment]
I tried ```<br/>``` too with single and double quotes...does not work...
```php
$myStr = 'Hello friends' . '<br/>'
```

**Comment by zeroender** [comment]
In your code file is there a closing semicolon?  I've found (depending on debugger level) if you have one string as the last line of your php and omit the semicolon it may not throw and error but not work.  You could also add several breaks to be sure that page formatting/css isn't hiding the line breaks - eg:

`$myStr = 'Hello friends '.'<br><br><br>';`

Then echo this out a few times and see if you see breaks.

**Comment by dianakleban** [comment]
I just gave an example. My code has semicolon. Also, 3 ```<br>``` does not work either. I tried single and double quote and it is still getting printed on the page, instead of being recognized as HTML tag. The code is located in the logic php file. It should be very simple, but it does not work for some reason...

**Comment by dukesnuz** [comment]
Can you change your code so that the ```<br>``` tags are used in the index=view page and not in the logic script.

I read that PHP works more efficiently when using single quotes in a string because with double quotes PHP also has to look for a variable.  When I use a only variables ,  \n or  \r in a string I use double quotes as I feel is is easier to read than single quotes and dots.   Here is a [link](https://able2know.org/topic/71607-1).

**Comment by dianakleban** [comment]
I am doing all the string concatenation in the logic part. I am combining multiple string in one. But now when I am thinking about it, logic part, if I understand it correctly, does not have any html tags, so <br> may not be a right choice. Can the logic part have any html tags at all? If not, is there a way if you want to concatenate it in the logic file, but see results on different lines. Is there something else that we can use in the logic file as a carriage return/new line?

**Comment by peggyo** [comment]
I believe that @susanBuck generally recommended that html tags not be in the PHP code, but it can be a judgement call in some cases. However, for an example of including tags in a PHP file, you can look at the helpers.php `dump` function. It may not solve your specific problem, but it may help.

**Comment by dianakleban** [comment]
Guys, I realized why I don't see the results with ```<br>``` correctly, It is because I am using **sanitize($results).** When sanitize is happening, breaks show up as html tag and does work the way it should...
