### ISSUE TITLE
VirtualHost template for a new Project

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#32]
I would like to clarify that we need to repeat this VirtualHost template in the configuration file multiple times for each project, so eventually there will be 4 of those temples for each project (using p1, p2, p3 and p4 instead of hello-world).

```php
<VirtualHost *:80>
  ServerName hello-world.dwa15.me
  DocumentRoot "/var/www/html/hello-world"
  <Directory "/var/www/html/hello-world">
    AllowOverride All
  </Directory>
</VirtualHost>
```

**Comment by ysrinu** [comment]
Yes, this was covered in the lecture notes
https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/08_Production_domain.md#recap

**Comment by gregorycoleman** [comment]
I went ahead and created p1 through p4 on my server in the conf file as well as in NameCheap when I set up my first subdomain.  If you are setting it up for p2, you might as well do it for p3 & p4 at the same time. Just a thought.

**Comment by SridharSubramaniam** [comment]
@gregorycoleman good tip!

@dianakleban yes - we would need one virtual host entry per named server configuration.

**Comment by peggyo** [comment]
I do think @gregorycoleman 's tip is a good one. For myself, though, I think the requirement to do it 'fresh' for each project will reinforce the learning for me. A trade-off, as it also leaves me future pitfalls.

**Comment by susanBuck** [comment]
Confirming all the student answers above.

Yes you need a unique virtualhost block for every project, because every project has its own subdomain.

**Comment by luke777gu** [comment]
I sucked on server not refreshing for half an hour until I saw this post. Thank you guys.
