### ISSUE TITLE
Screenshots for Progress Log Week3

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#33]
@susanBuck I am confused about the screenshots that we need to include in the Progress Log this week. Our html, php and css code is still 'under construction' and won't be ready till 9/27, how can we include the screen prints? 
Also, on the other hand, some of us may already included css and made it php and then we cannot reverse it to the minimum amount of HTML, php and css? What am I missing here?

**Comment by zeroender** [comment]
If I understand the progress log correctly, we are supposed to start development on project 2 as part of the log this week, and creating the site while going through the log.  So we create the repo, clone it over to the production machine, create the subdomain, then create the basic html forms (prior to writing any php).  That's what the screenshot will be of, then we add some PHP.  It looks like next week we'll add validation to the forms and refactor the PHP code to use objects (so the code behavior will ultimately be the same, but better organized).

**Comment by peggyo** [comment]
I took it to mean screen shots of the initial page development prior to adding PHP logic, but I would guess that if you are already past that point just show what you have at this point. You can change it based on @susanBuck 's recommendation. I also had started my PHP before reading to that point in the progress log, but my HTML had only my PHP include statement so it was easy to remove/replace.

**Comment by susanBuck** [comment]
Both student answers above are correct.

And if you get ahead - say you had added PHP - no need to remove that before taking screenshots. 

The idea is to build the projects incrementally, and the progress logs capture that progression.
