### ISSUE TITLE
HTML screenshot

### ISSUE THREAD

**Issue by gnodar01** [susanBuck/dwa15-fall2017#35]
In the progress log it states

>In the following box include a screenshot of the relevant HTML code from the above step (I don't >need to see your CSS code).

What's a good way of taking a screenshot of code? I'm at 128 lines for the html code, so it doesn't fit to screen. My logic code is up to 184 lines.

One way I came up with is to load the code on Github, and take a full screen screenshot using chrome dev tools. But the text in the resulting screenshot is tiny, and it was mentioned in lecture to make the screenshots legible.

Also a lot of the lines go off page. I can force line-wrapping at 80 columns, but that makes the end result even longer, and harder to fit into the progress log format.

Another way is print to image/pdf. My code editor doesn't have a print to pdf feature. I can paste the code into some regular text editor, but the syntax highlighting is removed.

Either way the end result is almost impossible to read. Any tips?

**Comment by gnodar01** [comment]
Also, should we include a screenshot of the HTML code before or after we develop the backend logic handling. My html is larger after developing the logic code (in a separate file) because I use the outputs of it in the display code where my HTML is. The progress log seems to be written as though we should take the screenshot before working on the logic code.

**Comment by susanBuck** [comment]
You can screenshot the relevant part of the code - the form. The idea is to give me a quick look at the essential parts - I can always go to your repo to get the full picture.

If your HTML undergoes a lot of changes after you add the logic, you can include a second screenshot and make note.
