### ISSUE TITLE
Error When Deployed to Digital Ocean

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#39]
project works in dev
 deployed live getting error 500 =page isn't working
 when I comment out helpers.php in my logic script, all is fine = page loads
here is a screen shot of the error log on Digital Ocean

![live_error_log_092017](https://user-images.githubusercontent.com/3799157/30664893-37bf0776-9e1d-11e7-8e08-dc259b84498f.png)

**Comment by squish3993** [comment]
Have you checked your /var/www/html/p2 folder on digital ocean to make sure the helpers.php file was cloned there?

**Comment by dukesnuz** [comment]
yes. helpers.php is also on DO

**Comment by dukesnuz** [comment]
@squish3993  Thank you, made me think about the path.
Issue solved, simply had wrong path for ''`require('helper.php')''`

**Comment by squish3993** [comment]
Ah, that makes sense. Well, glad I could help somehow! I'm happy you figured it out
