### ISSUE TITLE
Apache/mySQL initiation in Xampp

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#4]
Does it matter in what order Apache and mySQL start up? Do they run independent from each other?

**Comment by ricardoa-harvard** [comment]
At this point as long as they are both starting I don't think order should matter. When we begin creating applications that communicate with a database we will want the database (mySQL) to be running before the application begins making requests to it.

**Comment by HeinrichTremblay** [comment]
As for the other part of the question, Apache (server) and Mysql (database) run independently from each other, they have simply been bundled in MAMP/XAMPP and are started automatically in MAMP/XMAPP when you start the server.

As you can see on this [stackoverflow answer](https://stackoverflow.com/questions/17570010/how-start-stop-mamp-pro-using-command-line/19801925#19801925), you can manually start and stop Apache and mysql independently with the `CLI` command line. Although, you better stick with the `GUI` (graphical interface) of MAMP/XAMPP unless you are doing some troubleshooting.

**Comment by craterd** [comment]
Yes they run independently of each other.
