### ISSUE TITLE
How to access variable in index.php

### ISSUE THREAD

**Issue by asmatmuradi** [susanBuck/dwa15-fall2017#40]
I've built two php files ( my logic php file and index.php). 

 When I want to access the form values in my logic file I use `_GET['variableName'] ` but how do I access the variables from my index.php file? 
Assume I do all the calculation in my logic file final result i want to echo out from my index.php. 
I get this issue when trying to access the variable directly: 

`Notice: Undefined variable: form in /Applications/MAMP/htdocs/p2/index.php on line 60`

**Comment by ALiborio** [comment]
Are you including or requiring the logic php file in your index.php?

At the top of your index.php file you should have something like 
```<?php require('logic.php'); ?>```

Then later on within the index.php file you should be able to reference the variables set up in the logic.php file.

If you've done all that and you're still getting the error, check your logic.php file to make sure the variable ```form``` is always getting set up, no matter what the output is.

**Comment by SridharSubramaniam** [comment]
@asmatmuradi You can directly access a variable(like $var) from PHP file that you defined in your logic file as long as it is accessible (i.e. not a local function variable).

**Comment by rrtx2000** [comment]
Are you setting up a variable called form (EX: $form=123;) or are you talking about the form element (EX: \<form\>)? If it's a variable you can also try this and troubleshoot based on the results:
```
if (isset($form)){
    echo("form exists");
}
else {
    echo("form doesn't exist");
}
```
If you're trying to echo the \<form\> element, you don't do that.

**Comment by dukesnuz** [comment]
Not sure if you have a typo in your message, you have ``_GET['variableName']`` should be ``$_GET['variableName']``
Are you getting error on initial page load(is variable set to an empty value) or after you click submit?

**Comment by peggyo** [comment]
Viewing the source in the browser and/or running the page through validation may also be helpful, particularly in cases where the error message may mislead due to a simple typo.

**Comment by susanBuck** [comment]
Bumping this post to see if this issue can be closed or if it's still pending.
