### ISSUE TITLE
Get to know your classmates via P1

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2017#42]
Hi all,

At the start of the semester, a student asked in chat if there was a way you all could introduce yourselves so you could get to know your classmates. Because P1 has you introduce yourselves, we concluded that sharing all the p1 links would be one way to accomplish introductions.

http://p1.ricardoa.me
http://p1.diegometro1.me/Project1
https://p1.createlaunch.com
http://p1.kodiakjetpack.club
http://p1.bitbin.de
http://p1.gregorycoleman.me
http://p1.dwa-dc.me
http://p1.csci15.me
http://p1.ericding.me
http://p1.jessedugas.me
http://p1.elhaggaz.me
http://p1.mildredfakoya.me
http://project1.agizdov.me
http://p1.nodar.me
http://p1.luke77gu.me/
http://Project1.ajh83.me
http://p1.samanthi22.com
http://p1.danielkasai.net
http://p1.dwa-ykim.me
http://p1.ilearndk.me
http://p1.integritasinfosec.com
http://p1.mconstanti.me
http://p1.squish3993.me
http://p1.marcustechnologies.tech
http://p1.pranaymarella.me
http://p1.killer-bot.com
http://p1.zeguy.me
http://asmatmuradi.info
http://p1.kunista.me
http://p1.dwa15peg.me
http://p1.rektpwn.club
http://p1.dukesnuz.com
http://p1.tracyerxn.me
http://p1.ruthp.me
http://p1.andrespuente.us
http://p1.oscarrangel.me
http://p1.gabrielsanna.com
http://p1.sri-hes.me
http://p1.rameztarazi.me
http://p1.et11492.me
http://p1.richpanda.me
http://p1.beyondthepage.org
http://p1.fahadsheikh.me
http://p1.drgg.me
http://p1.extensionworth.me
http://p1.srinivasyelamanchili.me
http://p1.chenzhao88.me
http://p1.milliezhou.me
http://p1.lingshan03.me
http://p1.adamliborio.com

**Comment by ALiborio** [comment]
@susanBuck it looks like my p1 is not linked here. I'm not sure if any others are missing.

http://p1.adamliborio.com

**Comment by susanBuck** [comment]
Thanks @ALiborio! This list was manually compiled so I'll chock it up to my human error. With yours added that makes 50. There are 53 students enrolled in the course so that means we're missing 3 others. Speak up if your project isn't on the list. : )

**Comment by dianakleban** [comment]
Great introduction projects, everyone! I feel proud to study with such smart and talented people!
Very nice to meet everyone here!

**Comment by SridharSubramaniam** [comment]
Awesome work by everyone! So good to meet you all here!

**Comment by davida26** [comment]
Great to meet everyone! Thanks @susanBuck for posting these.

**Comment by HeinrichTremblay** [comment]
I edited the list to put name for each link :)

[Ricardo Alcantar](http://p1.ricardoa.me)
[Diego Acosta](http://p1.diegometro1.me/Project1)
[David Aviles](https://p1.createlaunch.com)
[Matt Bartles](http://p1.kodiakjetpack.club)
[Stephen Benjamin](http://p1.bitbin.de)
[Gregory Coleman](http://p1.gregorycoleman.me)
[Dave Crater](http://p1.dwa-dc.me)
[Sheetal Dalvi](http://p1.csci15.me)
[Eric Ding](http://p1.ericding.me)
[Jesse Dugas](http://p1.jessedugas.me)
[Hisham Elhaggaz](http://p1.elhaggaz.me)
[Mildred Ayeesha Fakoya](http://p1.mildredfakoya.me)
[Atanas Gizdov](http://project1.agizdov.me)
[Nodari Gogoberidze](http://p1.nodar.me)
[Luke Muwei Gu](http://p1.luke77gu.me/)
[Aaron Howard](http://Project1.ajh83.me)
[Samanthi Jinadasa](http://p1.samanthi22.com)
[Daniel Kasai](http://p1.danielkasai.net)
[Youjin Kim](http://p1.dwa-ykim.me)
[Diana Kleban](http://p1.ilearndk.me)
[Daniel Labelle](http://p1.integritasinfosec.com)
[Matt Constanti](http://p1.mconstanti.me)
[Jacob Lewis](http://p1.squish3993.me)
[Nathan Marcus](http://p1.marcustechnologies.tech)
[Pranay Marella](http://p1.pranaymarella.me)
[Alan Martinson](http://p1.killer-bot.com)
[Sean Patrick](http://p1.zeguy.me)
[Asmat Muradi](http://asmatmuradi.info)
[Roman Orlov](http://p1.kunista.me)
[Peggy Ostlund](http://p1.dwa15peg.me)
[Dylan Rumph](http://p1.rektpwn.club)
[David Petringa](http://p1.dukesnuz.com)
[Tracy Ericson](http://p1.tracyerxn.me)
[Ruth Phillips](http://p1.ruthp.me)
[Andres Puente](http://p1.andrespuente.us)
[Oscar Rangel](http://p1.oscarrangel.me)
[Gabriel Sanna](http://p1.gabrielsanna.com)
[Sridhar Subramaniam](http://p1.sri-hes.me)
[Ramez Tarazi](http://p1.rameztarazi.me)
[Eric Tracy](http://p1.et11492.me)
[Heinrich Tremblay](http://p1.richpanda.me)
[Nicholas Troy](http://p1.beyondthepage.org)
[Mohammad Fahad Sheikh](http://p1.fahadsheikh.me)
[Gagik Vardanyan](http://p1.drgg.me)
[Brian Worthington](http://p1.extensionworth.me)
[Srinivas Yelamanchili](http://p1.srinivasyelamanchili.me)
[Chen Zhao](http://p1.chenzhao88.me)
[Millie Zhou](http://p1.milliezhou.me)
[Hanamichi Sakuragi](http://p1.lingshan03.me)
[Adam Liborio](http://p1.adamliborio.com)

**Comment by susanBuck** [comment]
Thanks @HeinrichTremblay !
