### ISSUE TITLE
Calling a method with a string

### ISSUE THREAD

**Issue by gnodar01** [susanBuck/dwa15-fall2017#43]
I'm reading through [Cipher.php](https://github.com/susanBuck/dwa15-php-practice/blob/master/cipher/Cipher.php) and noticed the following on line [66](https://github.com/susanBuck/dwa15-php-practice/blob/master/cipher/Cipher.php#L66):

```
            if (ctype_alnum($character)) {
                $algorithm = $this->algorithm.$encodeOrDecode;
                $character = $this->$algorithm($character);
            }
```

`$this->$algorithm` is declared as a property on line [11](https://github.com/susanBuck/dwa15-php-practice/blob/master/cipher/Cipher.php#L11) and gets a string value of either `"vowels"` or `"shift"`. So the local `$algorithm` variable is concatenated with the string  `$encodeOrDecode` and gets a string such as `"vowelsencode"`.

What confuses me is the function call `$this->$algorithm(...)`. If I'm understanding it correctly that is using the **string** held by the local `$algorithm` variable, e.g. as `"vowelsencode"`, and calling it as a **method** within the class `Cipher`.  So if set to the **string** `"vowelsencode"`, it would call the **class method** `vowelsEncode` on line [127](https://github.com/susanBuck/dwa15-php-practice/blob/master/cipher/Cipher.php#L127).

Is that right, and if so is that normal practice in PHP? I tried searching `"call function by string php"` in Google, and found [this StackOverflow post](https://stackoverflow.com/questions/1005857/how-to-call-php-function-from-string-stored-in-a-variable) but no one seems to be citing an example such as the one above as valid, even though it clearly works...

**Comment by ALiborio** [comment]
There is documentation on php.net about this: [Variable Functions](http://php.net/manual/en/functions.variable-functions.php)

There are several examples on that page that show how this can be used.

**Comment by gnodar01** [comment]
Nice, thanks!
