### ISSUE TITLE
Project 2 Modifications

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#44]
@susanBuck I would like to clarify something. This week we will add a class and validation to Project 2, but it means that we are going make changes to the existing display and logic files. We may shuffle code around by extracting and modifying existing code. So if we release week's 4 code, it will overlay existing github and production code from week3 which was not graded yet. While you are grading week 3, week's 4 code maybe in the construction stage, not equal to week's 3 and at the same time not finalized yet. Are we supposed to wait until you grade week 3 before releasing to github and production server weeks 4 code? Am I missing something in understanding?

**Comment by susanBuck** [comment]
Do not wait - make commits to your project(s) as you progress. I can always look at your git history to see your project in week 3 vs. week 4.
