### ISSUE TITLE
Cipher - initializing inside the constructor

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#45]
Properties 'alphabet' and 'vowels' are initialized to the same value inside the constructor no matter how the class is instantiated. In other words these values are not dependent on the class initialization parameter values.
```
        $this->alphabet = str_split('abcdefghijklmnopqrstuvwxyz');
        $this->vowels = str_split('aeiou');
```
So, we might as well have initialized these at the declaration itself without needing to do the same in the constuctor. **Right**?

```
    /**
    * Properties
    */
    private $algorithm; # What cipher algorithm to use (e.g. vowels, shift)
    private $algorithms = ['vowels', 'shift']; # Array of available algorithms
    private $alphabet = str_split('abcdefghijklmnopqrstuvwxyz'); # Array of letters a-z
    private $vowels = str_split('aeiou'); # Array of vowels
```

To be more precise, these two properties should be declared as CONSTANTS since their value need (should) not change during the lifecycle of the class object.

Going further, you can have a static function that checks if a given algorithm belongs to this constant algorithms (array). And since a static function can be called without initializing a class object (i..e., without having to instantiate), it saves the overhead of creating the class object unnecessarily where the algorithm chosen by the user is not supported by the class.

Thanks
-Sri

**Comment by susanBuck** [comment]
> So, we might as well have initialized these at the declaration itself without needing to do the same in the constuctor. Right?

You can't use function calls when declaring properties.

Thus, this would not work:

```php
private $alphabet = str_split('abcdefghijklmnopqrstuvwxyz'); # Array of letters a-z
```

> Going further, you can have a static function that checks if a given algorithm belongs to this constant algorithms (array). And since a static function can be called without initializing a class object (i..e., without having to instantiate), it saves the overhead of creating the class object unnecessarily where the algorithm chosen by the user is not supported by the class.

So you're saying... statically check that the algorithm exists before instantiating for performance reasons? I think the difference would be negligible.

**Comment by susanBuck** [comment]
Forgot to note in my last comment - 
Sure - class [constants](http://php.net/manual/en/language.oop5.constants.php) might be more appropriate for these values since they don't change.

**Comment by ysrinu** [comment]
Thanks @susanBuck 
From http://php.net/manual/en/language.oop5.properties.php

> This declaration may include an initialization, but this initialization must be a constant value--that is, it must be able to be evaluated at compile time and must not depend on run-time information in order to be evaluated.

An alternative way to initialize at class property declaration is to hardcode the alphabets
`private  $alphabets =  ['a','b','c']; #hardcode all alphabets`

I agree, for our assignments purpose the overhead of class instantiation is very small. On servers where 100s of 1000s of objects are created every few secs or minutes, the overhead of class construction (instantiation) and destruction (garbage collection) can make a noticeable difference.

@HeinrichTremblay  the big O(n) might be big compared to the class instantiation. But this can be a motivation to avoid using str_split inside the constructor, but initialize $alphabet as constant at class property declaration itself.
Again, this doesn't make much difference for our work here but is a good thing to remember as paying attention to these details makes a big difference in performance tuning in a real production environment.
