### ISSUE TITLE
Books Example Question

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#46]
In the Foobook Example, https://github.com/susanBuck/foobooks0/blob/master/getAllBooks.php, I can see that we require Form.php, helpers.php and Book.php. Is there a reason why we need to include helpers.php file? I thought sanitation() is included in Form.php, so we should be covered with just 2 files: Form.php and Book.php, unless I am missing something?

**Comment by gnodar01** [comment]
I believe she kept `helpers.php` in there so she could utilize the `dump` function. But you're right that you can remove it before pushing to production.

**Comment by susanBuck** [comment]
@gnodar01 is correct. You can, but aren't required to, remove it before pushing to production.
