### ISSUE TITLE
Query on form validation

### ISSUE THREAD

**Issue by sheetaldalvi** [susanBuck/dwa15-fall2017#47]
As I understand, a good web application should have both client side (JS) and server side validation (php) in place. This is to ensure the correctness of user input in case the JavaScript functionality is turned off or manipulated at browser level.
I had used JQuery validations for my form in Project 1. JQuery validations provide extensive support for the user inputs with ability to customize error messages if required. In this case , if I implement the php validations on the same form inputs. I might see two error messages (one from JQuery  and another from Php validations) which is not desirable. 
My question is how to identify this thin line between validations to avoid over killing and duplicate validations for same form element?

**Comment by susanBuck** [comment]
When the form is submitted, the page will refresh and any jQuery (JavaScript) validation methods that might have been there should no longer be there. When the page loads, you should then only see any applicable messages detected on the server.

So while it is true there is overlap in the validation, the user shouldn't notice.

Other considerations tangential to this is error message styling. Ideally, the error messages should look the same regardless of whether the server or client is generating them. To solve this, it's common to have your server trigger errors with JavaScript to use the same styling that your JavaScript validation might be using. To be clear, I don't require/expect you to do this in projects - it's more an ideal to remember in real-world applications.

**Comment by sheetaldalvi** [comment]
Thanks for the clarification.

**Comment by ysrinu** [comment]
@susanBuck I am not adding any JS validation to my code but included validation as part of form input tags (HTML5 code). Now, the way the validation errors shows up (on submit) is dependent on the browser type and it's not easy to output php validation messages in the same UI format.

Having said that, is it okay to have validation at html5 code (irrespective of JS)?
Thanks,
-Sri

**Comment by susanBuck** [comment]
@ysrinu Yes, it's okay to have HTML5 validation code. No, it does not have to match the styling of your server-generated validation messages.
