### ISSUE TITLE
Atom Issues Windows 10

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#48]
I don't know if anyone experienced Atom issues in Windows 10. It is the second or third time when I uninstalled and reinstalled it.  It is opening fine after installation, but then when you try to open it on a second day and it is not opening at all. You click on it and it is not opening. I am not sure if this is because of Windows 10 and its updates or something else. I was wondering if anyone came across this issue .

**Comment by gvardany** [comment]
Have you tried to open it from the command line? I am not a windows user, but have a look into  [this post](https://discuss.atom.io/t/atom-wont-start/23551), it might be helpful.

**Comment by susanBuck** [comment]
Tips for debugging Atom:
<https://flight-manual.atom.io/hacking-atom/sections/debugging>

[Sublime](https://www.sublimetext.com) text is another editor that's very similar to Atom. Sublime is free to use, but they do ask you eventually purchase it if you like it. Throwing that out there as a quick fix in the interim while fixing Atom.

**Comment by gregorycoleman** [comment]
I use Atom with Windows 10. I haven't had any problems except sometime Atom becomes a resource hog.

**Comment by dlabelle101** [comment]
try opening the windows task manager and see if the process is running...it could be a display issue of some sort

**Comment by helhaggaz** [comment]
I am using Windows 10 and Atom version 1.20.1 is working fine on it.

**Comment by rrtx2000** [comment]
I'm also using windows 10 so another option you might want to consider is Komodo Edit from Activestate. It's free and it launches much faster than Eclipse but a little slower than Notepad++. One of the features I use all the time is the "Ctrl-Shift-F" find. This is the command to search all the files in a directory.

**Comment by zeroender** [comment]
If you are farmilar with using an IDE you could use PHPStorm (linked under the course's software section).  After a little setup, it's pretty user friendly and can integrate with Git.  Takes slightly longer to get started than a text editor however.

**Comment by pranaymarella** [comment]
I use Atom on Windows 10, when atom doesn't open for me it is usually because I normally use multiple monitors. When I switch back to single display, atom opens off screen and I can't see it. The fix for this can be found here: [https://github.com/atom/atom/issues/6939](url)

**Comment by peggyo** [comment]
I use Windows 10. I am using Atom, but it is exceedingly slow to load. I often end up with multiple instances because I thought it didn't work so I tried to start it again. 
I run into small problems now and then related to display or shortcuts or something because Atom is a new editor for me.

**Comment by dianakleban** [comment]
Thank you, guys, I will try out all your suggestions.

**Comment by mfs780** [comment]
Should not really make too much of a difference but try to open it as an administrator.

**Comment by susanBuck** [comment]
Going to close out this thread as it sounds like an isolated problem, and there's lots of tips above to try out. But feel free to post a follow-up or open a new Issue if this continues to be a problem for you, @dianakleban.
