### ISSUE TITLE
sending email:  display or logic

### ISSUE THREAD

**Issue by ruthnphillips** [susanBuck/dwa15-fall2017#49]
If an application sends email with the results info to a user, is that display or logic? your thoughts..

**Comment by gabrielsanna** [comment]
I'd say the functionality to send an email should be in the logic file(s). Display refers to what's showing up on the web page that's being viewed. The action of sending an email as the result of a button press isn't actually something the user sees on that web page.

**Comment by zeroender** [comment]
Agreed, that seems like it doesn't fit with a display file, since it is not directly outputting to a website.  Maybe in a seperate logic file or class to be utilized by the main logic file.

**Comment by stbenjam** [comment]
I think there's multiple layers here.  Maybe it's over thinking it but...

There's a logic layer that sends the e-mail, there's a logic layer for the content of the e-mail if there's things you need to do to render it, and a display layer that is used to render the e-mail content itself.

**Comment by SridharSubramaniam** [comment]
+1. 

Composing + Sending email is part of business/service logic. But the actual compose could have two elements - content of the email & template. The template would be a display portion here.

**Comment by luke777gu** [comment]
I agree with the above that it should both contain logic and display layers.

**Comment by susanBuck** [comment]
Sounds everyone is in agreement. : ) Sending the email is a form of logic, but the email itself may have a display file that dictates the contents/structure of the email.

In fact, this is exactly how Laravel - which we're starting with this week - handles emails.
