### ISSUE TITLE
Share your P2 (optional)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2017#52]
I wanted to start a thread where you all can share your Project 2's with your classmates. It can fun to see all the different ideas and approaches students took.

Because this project was more indepth than Project 1, I didn't want to assume everyone was okay with having their worked shared - so I'm leaving it up to you...

If you want to share, simply reply to this issue with your P2 URLs. I encourage you to include your Github repository URL in addition to your production URL so classmates can not only view your work, but look at your code.

No pressure if you don't want to share your work - this is optional.

Pro-tip: If you do reply, you may want to "unsubscribe" for notifications to this thread (link in sidebar on right), otherwise your inbox will blow up with all the replies. : )

**Comment by mfs780** [comment]
Here is my P2 (WIP)
http://p2.fahadsheikh.me

**Comment by SridharSubramaniam** [comment]
@mfs780 looks great Fahad

My P2 here: http://p2.sri-hes.me/ . A simple expense logger

**Comment by stbenjam** [comment]
http://p2.bitbin.de/ - Scrabble score calculator

Repo is here https://github.com/stbenjam/dwa-project-2

**Comment by squish3993** [comment]
http://p2.squish3993.me/ - Simple musical interval calculator 

Looking forward to seeing all of these!

**Comment by gregorycoleman** [comment]
Here is my p2 [Excuse Generator](http://p2.gregorycoleman.me/)

**Comment by rrtx2000** [comment]
Mine is a trip time calculator. You enter how far you want to drive, the estimated average speed and if you want to round up to the nearest 15 minutes. It will then calculate the time it will take you. Be sure to try 15 mph or less and 100 mph or more. 
Live site: http://p2.killer-bot.com/
git: https://github.com/rrtx2000/p2

**Comment by drumph33** [comment]
[Pasta Cooking Quide](p2.rektpwn.club)  nam non

**Comment by TheLivingNick** [comment]
I basically did the Scrabble Calculator wireframe with a few twists:
http://p2.beyondthepage.org

**Comment by EricXDing** [comment]
I created a CAPS/noncaps tool - sharing with everyone here!
http://p2.ericding.me

**Comment by gnodar01** [comment]
[A hashing tool](http://p2.nodar.me) to create message digests and hash-based message authentication codes.

**Comment by pranaymarella** [comment]
My project is here: http://p2.pranaymarella.me/

**Comment by nekoCC01** [comment]
Hi everyone, here´s the link to my Project 2: http://p2.danielkasai.net/

**Comment by HeinrichTremblay** [comment]
A target income calculator based on the book 4 hours workweek: 
[p2.richpanda.me](http://p2.richpanda.me) and [github](https://github.com/HeinrichTremblay/dwa15-p2)

**Comment by HeinrichTremblay** [comment]
@gregorycoleman Your P2 is epic! 🥇 

> This is incredible. I cannot believe it happend to me.
> 
> I know my homework is 1 day late, and I have a satisfactory in quality reason for that. It has to do with my hamster and what happened at the pet store. my hamster ate a lot of sushi until they ate all of them. That is the reason why I am so late with p2
> 
> As Forrest Gump would always say to me "I say no to alcohol, it just doesn't listen."

**Comment by dukesnuz** [comment]
What's for [dinner](http://p2.dukesnuz.com).
Github [repo](https://github.com/dukesnuz/p2).

**Comment by ALiborio** [comment]
[Name Generator](http://p2.adamliborio.com/)

https://github.com/ALiborio/dwa15-project2
Check out the README for details on how it functions.

**Comment by gvardany** [comment]
Here's my [p2](http://p2.drgg.me/) if you thought to go green. And here is the [repo](https://github.com/gvardany/p2).

**Comment by zeguy** [comment]
Nice job everyone. Mine is [p2.zeguy.me](url)

@gregorycoleman Ghost Dog is indeed awesome.

**Comment by ysrinu** [comment]
My project is here. 
http://p2.srinivasyelamanchili.me/

**Comment by ruthnphillips** [comment]
My Shelter finder here: [](http://p2.ruthp.me)

**Comment by helhaggaz** [comment]
My 2nd Project:
p2.elhaggaz.me

**Comment by dianakleban** [comment]
Very nice projects, everyone.
Here is mine: http://p2.ilearndk.me

**Comment by milliezhou** [comment]
Nice work, everyone!
My p2: [p2.milliezhou.me](http://p2.milliezhou.me/)

**Comment by zeroender** [comment]
Very cool everyone!

My p2: work schedule application: http://p2.extensionworth.me/

**Comment by davida26** [comment]
great job everyone - Here is [my P2](https://p2.createlaunch.com/) for those that like beer.

**Comment by dlabelle101** [comment]
My P2 - [simple bill splitting app](http://p2.integritasinfosec.com)

**Comment by mconstanti** [comment]
A [different take](http://p2.mconstanti.me) on the bill splitting app.

**Comment by susanBuck** [comment]
Closing this but feel free to continue to contribute your links if you haven't already.
