### ISSUE TITLE
validate rule - business friendly name

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#53]
In my php code I used property names that are bit cryptic from a business user point of view. For example customer name is 'custName'.

Now, in the Form.php validate function, the (error) output message prints the property name, for example 'custName is required field'. In the html display I labeled the input field as 'Customer Name'.
The error message therefore can be confusing to the end user.

The validate rule takes property name and validation rule (list delimited by pipeline) pairs. I can throw in business friendly name as the first string in the validation rule list (and omit this part from actual validation) so the error message output has the user friendly name rather than the property name.
An alternative way is to use a multi-dimensional array to provide the display name in the new dimension.

Now, is it okay for this project if the error message output on the web page has property names that might be cryptic? I can change the property name but that will be a short-term solution since we cannot name all properties to align with the display friendly ones. The long-term solution would be do enhance the validate rule to take friendly name as parameter too for the output, and I don't have enough time to implement this.

Thanks,
-Sri

**Comment by mfs780** [comment]
I agree with utilizing business friendly names. What about using a array with key value pairs matching the variable to a business friendly name.

**Comment by ysrinu** [comment]
@mfs780  , good idea.  That would require setting two arrays and a 2nd loop up in the validate rule. The idea case would be to use a single object (array) that carries the original property name, friendly name and the list of validations to perform.

**Comment by TheLivingNick** [comment]
You could probably just create a single array with key => value as $fieldName => $friendlyName, then replace $fieldName in the error message the array entry for that $fieldName.

**Comment by ysrinu** [comment]
@TheLivingNick  Thanks for the suggestions. This is a good one to keep it simple.
If it's a coding I would do at work (professional) I would tend to use a single array for all parameters. Using 2 separate arrays (one for friendly name, the other for validation) can most likely will result one being used and the other not.
This happens very often when developers look for an existing apis and they don't realize there's "accessory" apis. A single api that does a business logic unit of work completely is more valuable.

**Comment by ysrinu** [comment]
Instead of multiple arrays or mult-dimensional arrays, I would use a json object to encapsulate information necessary for the From.php validation function. This json object would be passed to the validation function as an argument.The json data would like like:

```
[
  {
    "name":"custName",
    "business_name":"Customer name",
    "val_rules":[ "alpha","required" ]
  },
  {
    "name":"fromZipCode",
    "business_name":"Origin zip code",
    "val_rules":[ "numeric", "required" ]
  },
  {
    "name":"shipType",
    "business_name":"Shipping Type",
    "val_rules":["required" ]
  }
]
```

**Comment by susanBuck** [comment]
> Now, is it okay for this project if the error message output on the web page has property names that might be cryptic?

Yes, this is fine.

`Form.php` is a bare bones validator used to "get our feet wet" when it comes to exploring classes and validation. It offers just a taste of the features/approach we'll get into w/ Laravel's validation functionality, which as you'll see, has the [ability to customize your validation method](https://laravel.com/docs/5.5/validation#customizing-the-error-messages).
