### ISSUE TITLE
ssh issue digital ocean

### ISSUE THREAD

**Issue by asmatmuradi** [susanBuck/dwa15-fall2017#54]
My digital ocean account was connecting just fine and i was able to pull the code from github.com. But it suddenly stopped working. 
following is the error:
```
MacBook-Pro:practice Asmat$ ssh root@138.197.87.15
Permission denied (publickey).
MacBook-Pro:practice Asmat$ 
```
My .ssh directory looks like this: 

```
MacBook-Pro:.ssh Asmat$ ls 
authorized_keys		config			id_rsa			id_rsa.pub		id_rsa_github		id_rsa_github.pub	known_hosts
MacBook-Pro:.ssh Asmat$ 
```
could this be because I've two ssh's in different files?

**Comment by nekoCC01** [comment]
I had a similar issue when using a new SSH-key, not named "id_rsa".
But as you use the standard-named pair of "id_rsa" (private) and "id_rsa.pub" (public), 
there shouldn´t be a problem with the files.

With the following command you can see each step in the connection process to detect where it stops:

`ssh -vT root@138.197.87.15`

You might also want to check the file permissions of the ssh-files

`ls -l ~/.ssh`

**Comment by jgcastillop** [comment]
I had the exact same issue with mine, turns out I had omitted the email address at the end of the ssh key I created. I just deleted it and made a new key and it worked perfectly.

**Comment by APuente21** [comment]
Can you confirm that your Github account includes a SSH key for your DigitalOcean account? If not, you will get a permission denied error when you try to clone a repository into your DigitalOceal server.

**Comment by susanBuck** [comment]
Bumping this post to see if this issue can be closed or if it's still pending.

**Comment by asmatmuradi** [comment]
Thanks everyone for helping me on this issue. I had to create a new SSH key and add it to ~/.ssh/authorized_keys file in my server. This resolved my issue.
