### ISSUE TITLE
Permission problem on os x

### ISSUE THREAD

**Issue by gvardany** [susanBuck/dwa15-fall2017#55]
I am trying to setup a laravel application on Mac OS X.

After creating the application, and pointing MAMP to it's public directory, I got the following error when trying to access the localhost with browser:
```
UnexpectedValueException
The stream or file "/Applications/MAMP/htdocs/foobooks/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
```
It's clear, the server does not have a permission to edit the logs and cache. But when following the notes I tried e.g. to run
```
sudo chown -R www-data storage
```
I got:
```
chown: www-data: illegal user name
```
So I wonder what is the mac equivalent of `www-data`. It seems this is only for linux.
Any help is appreciated.

**Comment by susanBuck** [comment]
The notes on changing permissions are specific to the DigitalOcean servers where Apache runs as `www-data`.

On your Mac, open the program *Activity Monitor* and search for `mamp` to see what User MAMP is running under. Example:

<img width="946" alt="2017-09-30_0807" src="https://user-images.githubusercontent.com/237711/31045652-896ce7a0-a5b6-11e7-9fe1-2b99bdc6661c.png">

Also, navigate into your new Laravel project's storage directory and use the `ls -la` command to see the permissions on the logs folder. Example:

```
/Applications/MAMP/htdocs/foobooks/storage $ ls -la
total 0
drwxr-xr-x   5 Susan  admin  170 Aug 30 05:55 .
drwxr-xr-x  25 Susan  admin  850 Sep 27 17:11 ..
drwxr-xr-x   4 Susan  admin  136 Aug 30 05:55 app
drwxr-xr-x   7 Susan  admin  238 Aug 30 05:55 framework
drwxr-xr-x   4 Susan  admin  136 Sep 27 18:10 logs
/Applications/MAMP/htdocs/foobooks/storage $ 
```

Note how in mine the owner of `logs` is `Susan` which matches up with the user that's running MAMP.

Alternatively, a quick fix is to open up the permissions on the directories to `777` which is not something I'd recommend on your production server but is okay locally:

From within your Laravel project dir:
```bash
sudo chmod -R 777 storage
sudo chmod -R 777 bootstrap/cache
```

**Comment by gvardany** [comment]
Thanks for the help. Actually it turned out that I was running into this because I have created the blank application with sudo (which at first I had to do, because of issue #56 ). But finally if I do not do this with sudo, then `sudo chown -R www-data storage` this step does not seem be necessary at all.

**Comment by susanBuck** [comment]
Gotcha. That makes sense. When creating the project with `sudo` it'll be owned by `root`, and because MAMP does not run as `root`, it would not have the appropriate access.

For reference if others face this same problem, if the project is created with `sudo` as `root`, you can change the ownership to your computer's main user after it's been created with the following command:

```bash
sudo chown -R $USER foobooks
```

(`$USER` is a dynamic variable which will be whatever your computer's user is)
