### ISSUE TITLE
Unable to initialize a blank laravel application

### ISSUE THREAD

**Issue by gvardany** [susanBuck/dwa15-fall2017#56]
I am trying to run:
```
composer create-project laravel/laravel foobooks "5.5.*" --prefer-dist
``` 
And I get connection time out:
```
The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Operation timed out
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```

This is gone when running with sudo however, which is not recommended.
I am using MAMP on OS X.
Any idea what is going wrong when trying to connect to internet?

**Comment by susanBuck** [comment]
I found several results on google when searching for your error. Have you tried any of the troubleshooting techniques people are suggesting? Let us know so we can narrow down what has/has not been tried yet.

One suggestion that seemed to come up frequently regarding this issue:
<https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues->

The fact that it works when you run `sudo` suggests it could be permissions related, which may be related to your other thread #55.

**Comment by susanBuck** [comment]
In #55 you said:
> But finally if I do not do this with sudo, then sudo chown -R www-data storage this step does not seem to be necessary at all.

Does that mean you were able to do get this working w/o sudo?

**Comment by ysrinu** [comment]
'sudo' should be used if you need superuser privileges. But the side effect is that the files/folders created/touched will be owned by the super user (as our professor has pointed out). This will make it difficult to work on these files as regular user. Here, you can quickly update to revert the permissions due to the simplicity of the change. In a real IT env fixing permissions (revert) may not be easy.

If you can give permissions (not global) at the file structure for the regular user to work, go for it.
Again, 'sudo' should be used to avoid running as 'root' but not as means to get around the "inconvenience" of a regular user

**Comment by gvardany** [comment]
@susanBuck Eventually I run without sudo and after the connection timeout message, it started to copy the dependencies from some cache. I think that when the first time I run with sudo, it stored all the downloaded libraries somewhere. So this is not a roadblocker for the moment. I should probably check also my proxy settings, since now I remember having downloads from command-line fail in some other occasions as well.

**Comment by HeinrichTremblay** [comment]
Have you tried the alternative way to create a Laravel application [via Laravel Installer](https://laravel.com/docs/5.5)? 

### Via Laravel Installer
First, download the Laravel installer using Composer:

```
composer global require "laravel/installer"
```

Make sure to place the `$HOME/.composer/vendor/bin` directory (or the equivalent directory for your OS) in your $PATH so the `laravel` executable can be located by your system.

Once installed, the laravel new command will create a fresh Laravel installation in the directory you specify. For instance, laravel `new blog` will create a directory named `blog` containing a fresh Laravel installation with all of Laravel's dependencies already installed:

```
laravel new blog
```

**Comment by susanBuck** [comment]
FYI: The Laravel installer uses Composer under the hood, so I'm not sure it'd circumvent the problem - but, you never know. Also, you have to use Composer to even download the Laravel installer which could face roadblocks similar to the initial problem.

It sounds like @gvardany has found a resolution, so I'll close this out - but feel free to post follow-ups or open a new thread if anyone else faces similar issues.
