### ISSUE TITLE
no more memory swap space error

### ISSUE THREAD

**Issue by samanthi22** [susanBuck/dwa15-fall2017#57]
When using a Mac and enabling swap space for more memory I get the following error.
mkfile: (/swapfile removed) Write Error: No space left on device.
What should I do?

**Comment by susanBuck** [comment]
The instructions for enabling swap space were specific to your DigitalOcean servers. You do not need to do this on your Mac.

<https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/06_Getting_DigitalOcean_Laravel_Ready.md>

**Comment by samanthi22** [comment]
Oh ok. Thank you.
