### ISSUE TITLE
$ sudo swapon /swapfile error

### ISSUE THREAD

**Issue by samanthi22** [susanBuck/dwa15-fall2017#59]
$ sudo swapon /swapfile

Getting an error: this is the error:
$: command not found

**Comment by susanBuck** [comment]
Glad you sorted out Samanthi! 
Going to close this now, but FYI you can close your own Issue if they're resolved. : )

**Comment by squish3993** [comment]
I just wanted to add to this in case anyone else has the same problem. I simply removed the "sudo" part of the command and everything worked fine. Hope that works for other people!
