### ISSUE TITLE
Firewall error message

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#6]
During my Xampp installation, I got the popup saying something about the **firewall** and **mysqld.exe.** This popup disappeared and MySQL (and apache) start up fine. Php file runs fine as well. I also checked the error logs, but did not find anything related to the firewall or other errors. Everything looks and runs fine. However, I am still concerned about the popup that happened, so it will not impact work that we need to do in the future. Did anyone experience this or similar problem?

**Comment by zeroender** [comment]
Hello dianakleban,

It sounds like you got a suggested message from windows about allowing these ports through the firewall - does that sound right?  Windows will try to detect and suggest ports to be opened during some program installation but if you have windows firewall running and no issues starting apache/mysql, I think you can safely ignore it.  If you run into issues, try turning off firewall - if that works, you would need to make sure ports 80 and 3306 are open in your firewall (see https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-windows-firewall-for-database-engine-access)

**Comment by susanBuck** [comment]
Piggy-backing on @zeroender's comments - I'm not concerned it will be a problem moving forward given mysql started fine.
