### ISSUE TITLE
Laravel Set up for Week 5

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#61]
I just want to double check that my understanding is correct for this week. We are supposed to go through the same process 2 times. One is to set up our own Foobooks and then set up Project 3?

**Comment by ruthnphillips** [comment]
That is also my understanding, hopefully Susan will concur.

**Comment by gvardany** [comment]
Yes I think that's what we should do for this week. And then next week, we will be developing the project 3 further.

**Comment by dukesnuz** [comment]
Sounds correct.

**Comment by susanBuck** [comment]
Correct.

Tip: Each week, I recommend reading through the progress log template before starting other work. The progress log lays out everything you need to do for the given week, so "loading" this information (specifically the *To dos* section) into your mind before digging into the material will give you a big picture idea of what your goals are for the week.
