### ISSUE TITLE
# BRAINSTORM :  Difference between composer Install and update

### ISSUE THREAD

**Issue by Diegometro1** [susanBuck/dwa15-fall2017#62]
```
** composer install**
** composer update** 
```

These are two similar commands; they are similar , but not the same.
When you specify your dependencies in the **composer.json** file, you can use install to install them. If you already installed them but you want to *update your dependencies to a newer version, use update.*

In order to know what must and must not be updated, Composer uses the composer.lock file, which you can see in the root of your project. Actually , you will never have to work with it, but is important to know that Composer uses it as a log of what it does.

[stackoverflow](https://stackoverflow.com/questions/33052195/what-are-the-differences-between-composer-update-and-composer-install)

**Comment by ruthnphillips** [comment]
Question, if you had already used the install command, and subsequently, you used it again, will it just update?

**Comment by susanBuck** [comment]
Adding to this, a quick rule of thumb:
+ Use `composer update` locally
+ Use `composer install` on production

(FYI: )We'll discuss this in Week 7 when we introduce Packages.)
