### ISSUE TITLE
Composer Install moving forward

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#63]
I would like to understand something about # composer install command. Let's say we set up our foobooks for the first time on production using all of the steps including composer install. When we make additional changes to the code in the future, do we need to run composer install command again or only if any dependencies changed?

**Comment by dukesnuz** [comment]
I do not believe running install composer would be need. Although I am thinking just add in this extra step all the time no matter what the changes are when deploying simply to stay consist.

**Note sure this is totally  correct, just my thoughts.**

**Comment by susanBuck** [comment]
Correct:`composer install` is only necessary on production if there was some change to composer-related things when developing locally.

Most often, this change is related to dependencies, but it could be some other change in `composer.json` as well.

(FYI: We'll discuss this in more detail in Week 7 when we introduce Packages.)
