### ISSUE TITLE
p3 and foobooks

### ISSUE THREAD

**Issue by luke777gu** [susanBuck/dwa15-fall2017#65]
The progress log requires us to upload our project3 and foobooks to the server, so the main pages of both addresses would both show laravel on the top. Does this mean that we have to do the same thing twice or do we have to add something more to project 3 right now so that it will function exactly the same as our project 2?

**Comment by zeroender** [comment]
"Following the steps we covered today, create the start of your Project 3 application. The project should exist locally, on Github.com, and it should be accessible on your production server."

I'm pretty sure this means p3 at this stage is the same as foobooks.  There wasn't any extra p3 setup/work in the progress log.

**Comment by rrtx2000** [comment]
I agree with zeroender. The week 5 progress log also says "Describe what you think you'd like to build for Project 3. I will ask you this same question next week, in case you change your mind." This sounds like we should just be thinking about what we want to do for P3.

**Comment by ysrinu** [comment]
@susanBuck 
In the progress log, from section 'Start Project 3', does that mean our p3 digital ocean link should point to project 3 and not 'foobooks'?
Should we upload foobooks practice application to a different sub-domain?

**Comment by ysrinu** [comment]
@susanBuck , can you please confirm? Thanks

**Comment by susanBuck** [comment]
Confirming @zeroender + @rrtx2000 's response.

Key points from the progress log template (emphasis added):
>> **Following the steps we covered today**, create your own Foobooks project which you will practice with and build upon in upcoming lectures. 

>> **Following the steps we covered today**, create the start of your Project 3 application. 

Week 5 was all about bootstrapping Laravel apps. This sets us up for Week 6 when we'll start programming in Laravel apps.

**Comment by ysrinu** [comment]
@susanBuck , hi @zeroender said p3 and foobooks are same for now.
(My apologies if I didn't understand this clearly yet)
So does that mean if we already setup foobooks github and digital ocean (p3 subdomain pointing to this), then there's no need to create a new github and larvael setup for new project (say xyz meant for p3) for now?

In other words, the 'urls for github and application' in section "To-dos" and be a duplicate in "Start Project 3" in week5 progress log?

**Comment by milliezhou** [comment]
@ysrinu , I think @zeroender 's comment that 

> p3 at this stage is the same as foobooks

means that they look the same, but not necessarily that they share the same repository. So, there needs to be a separate github and digital ocean repo for foobooks and p3. For the week 6 (next week), we wouldn't need to create/set up a new p3 since we've done that this week.

**Comment by peggyo** [comment]
@milliezhou I'm sure is right because the week 5 progress log asks for links to our two different github repositories.

**Comment by ysrinu** [comment]
Thanks @milliezhou  and @peggyo
