### ISSUE TITLE
Laravel - php package URL

### ISSUE THREAD

**Issue by rrtx2000** [susanBuck/dwa15-fall2017#66]
This is just a FYI: The Laravel installation page has a link to a video tutorial (https://laracasts.com/series/laravel-from-scratch-2017). I started watching it and it talked about a source for some packages. I went to the wrong location twice when trying to type in the URL so here it is in case anybody else has the same problem:

https://packagist.org/

**Comment by susanBuck** [comment]
Note: We'll cover packages (and packagist.org) in Week 7 (don't want anyone reading this to be concerned that they've missed something).
