### ISSUE TITLE
Problems submitting Week 5 progress log

### ISSUE THREAD

**Issue by rrtx2000** [susanBuck/dwa15-fall2017#67]
Is anybody else having a problem submitting the Week 5 progress log? I tried many times last night and have been trying this morning but it isn't successful. After I click Submit Assignment it doesn't submit and the status bar says, "Waiting for instructure-uploads.s3.amazonaws.com...". Eventually it times out.

**Comment by zeguy** [comment]
Just turned mine in without any issues. Not sure what it could be.

**Comment by rrtx2000** [comment]
I was able to get it to work with Chrome. Firefox wouldn't work.

**Comment by HeinrichTremblay** [comment]
It did the same to me, using the upload via Google Docs did the trick.

<img width="905" alt="screenshot 2017-10-09 23 21 07" src="https://user-images.githubusercontent.com/5926155/31345523-a3c471b4-acdb-11e7-8430-8d38ef21ca3f.png">

**Comment by susanBuck** [comment]
FYI for Canvas related problems, I've found [their support chat to be helpful](https://cases.canvaslms.com/apex/liveagentchat).

Alternatively they also have [email support](https://canvas.harvard.edu/#create_ticket).
