### ISSUE TITLE
Issue downloading Composer to DigitalOcean

### ISSUE THREAD

**Issue by erictracy11492** [susanBuck/dwa15-fall2017#68]
When I run sudo swapon -s, it lists '12' under 'Used' instead of '0'. Then when I tried to install Composer, I received the error:

curl: (35) gnutls_handshake() failed: Error in the push function

Here are the commands I ran:

root@et11492:~# sudo swapon -s
Filename				Type		Size	          Used	Priority
/swapfile                         file    	        4194300	  12	        -1
root@et11492:~# sudo cd /usr/local/bin
sudo: cd: command not found
root@et11492:~# mkdir -p /usr/local/bin
root@et11492:~# cd /usr/local/bin
root@et11492:/usr/local/bin# curl -sS https://getcomposer.org/installer | sudo php
curl: (35) gnutls_handshake() failed: Error in the push function.
root@et11492:/usr/local/bin#

**Comment by ysrinu** [comment]
@erictracy11492 
What's the curl version?
Run` curl -V`

![image](https://user-images.githubusercontent.com/25366909/31205782-958410f2-a941-11e7-9873-fd55d57cbe60.png)

**Comment by erictracy11492** [comment]
@ysrinu 
I actually got it to work after restarting my server, thanks for the help though!
