### ISSUE TITLE
composer.phar shortcut

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#69]
This is not an issue but more like a best practice.
https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/06_Getting_DigitalOcean_Laravel_Ready.md

Instead of moving (or copying) `composer.phar` to `composer`, creating short cut is ideal. This ensure that if the composer software is updated and the file content itself is changed (composer.phar) our shortcut doesn't get obsolete.
Shortcut is referenced as 'symbolic link' in unix
`ln -s composer.phar composer`

**Comment by susanBuck** [comment]
Updating composer after renaming is not a concern - it has it's own self-updating command that works regardless of whether you rename or alias.

```
composer self-update
```

The Composer instructions even suggest the renaming approach (<https://getcomposer.org/doc/00-intro.md#globally>).

That being said there's nothing wrong with creating an alias if you prefer.
