### ISSUE TITLE
Static Methods

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#70]
Hello,

In this weeks lecture, we saw how we can access static methods, without instantiating the object, using the `::` notation.  Are there any instances where we would still need to instantiate the object, even if it is static? For example, what if the static method used some variables defined in the class, or called on another class method?

**Comment by ysrinu** [comment]
I didn't go through this week's lecture notes yet. I would think static methods can refer static or constant (both are not the same) variables.
You cannot refer other type of variables inside the static method, since those variables make sense for an object instance only.

http://php.net/manual/en/language.oop5.static.php

**Comment by susanBuck** [comment]
> Are there any instances where we would still need to instantiate the object, even if it is static?

Not that I can think of - if it's declared static, presumably it should be designed to used statically.

> what if the static method used some variables defined in the class

A static method can only access properties defined in the class if they are also static. For example, the following would fail:
```php
class ExampleA {
  
  public $a = 1;
  
  public static function getA() 
  {
    return $this->a;
  }
}

# Uncaught Error: Using $this when not in object context in 
echo Example::getA();
```

But this would not:
```php
class ExampleB {
  
  public static $b = 1; # Note how $b is defined as static
  
  public static function getB() 
  {
    return self::$b; # Note how "self" is used to reference static properties
  }
}

echo ExampleB::getB();
```

**Comment by APuente21** [comment]
thank you both for the feedback! I will close the case.
