### ISSUE TITLE
Github error when trying to sync changes to readme file

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#71]
I'm trying to push the changes I made to the readme.md file, which are inline with what the professor showed in this weeks lecture, but I'm having some issues pushing it to Gihub, see below.

```
C:\xampp\htdocs\TipCalculator_Larvel (master)!
$ git add readme.md
warning: LF will be replaced by CRLF in readme.md.
The file will have its original line endings in your working directory.
```
```
C:\xampp\htdocs\TipCalculator_Larvel (master)!
$ git commit -m 'Updated readme'
error: pathspec 'readme'' did not match any file(s) known to git.
```
```
C:\xampp\htdocs\TipCalculator_Larvel (master)!
$ git push origin master
Everything up-to-date
```

If I check github after running the above, I see that my readme file did not get updated.

**Comment by ysrinu** [comment]
Can you run `git status` after each command and show the output again?

**Comment by APuente21** [comment]
```
C:\xampp\htdocs\TipCalculator_Larvel (master)!
$ git status
warning: LF will be replaced by CRLF in readme.md.
The file will have its original line endings in your working directory.
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   readme.md
```

I tried running the below commands which I found on StackOverflow, but it didn't help.

`git config core.autocrlf false`

**Comment by APuente21** [comment]
Im actually getting this error message for all the files I'm trying to push to the github (controllers and web.php).

**Comment by stbenjam** [comment]
The line ending message is just a warning, not a big deal.

This is the source of your error

```
C:\xampp\htdocs\TipCalculator_Larvel (master)!
$ git commit -m 'Updated readme'
error: pathspec 'readme'' did not match any file(s) known to git.
```

Something weird with Windows and quotes, it's interpreting your command as "commit file readme with message "Updated".

Try using double quotes around the commit message and see if that helps.

**Comment by dianakleban** [comment]
I got the same warning as you, but I did not get any errors afterwards. It got pushed to github fine.
Double check your readme.md file on github.
I noticed that during the lecture our teacher did not have any warnings, wondering if other people got it too?

![image](https://user-images.githubusercontent.com/31451809/31246050-d416ee80-a9d1-11e7-9c39-1cb31c3d1d91.png)

**Comment by APuente21** [comment]
It worked with double quotes. It's weird, as I haven't had any issues in the past. Thanks!
