### ISSUE TITLE
Overlaid Welcome Page

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#72]
@susanBuck I am just wondering if it is ok to push latest changes of Week 6 to Production right now (or we should wait) since it will overlay the original/built-in Laravel Welcome page that you expect to see for week 5 assignment.

**Comment by susanBuck** [comment]
Same answer I gave to #44 applies here.

**Comment by dianakleban** [comment]
I don't think I explained it correctly. Should we deploy all changes that we make to our foobooks and p3 to Production server or wait till next week. I am not sure if we should make these changes locally for our own practice only or we should deploy all of them to Production? I did not see any instructions to Production release, unless I missed them somewhere.

**Comment by susanBuck** [comment]
__Yes, commit *and* deploy progress to P3.__

<img width="679" alt="2017-10-06_1536" src="https://user-images.githubusercontent.com/237711/31295317-2c28a0b6-aaac-11e7-940b-9af568235c6f.png">

__Regarding `foobooks`, it's up to you.__

<img width="658" alt="2017-10-06_1534" src="https://user-images.githubusercontent.com/237711/31295332-404931c8-aaac-11e7-8dbb-416b0376adb8.png">

**Comment by dianakleban** [comment]
Got it. Thank you.
