### ISSUE TITLE
"Beta test" this deployment script

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2017#75]
Hi all,

In Week 7's progress log, the *Explore* topic will have the option of creating a deployment script to streamline the process of getting code deployed to your live server.

As this is new material this semester, I'd like have a few students "beta" test the instructions to work out any kinks.

If you're curious and have the time, [you can preview the instructions here...](https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/999_Extras/04_Deployment_script.md)

Reply to this issue to let me know if you ran into any problems while implementing these instructions.

Thanks!

**Comment by gregorycoleman** [comment]
I did not have any problems per se, but I deploy from a develop branch ( and sometimes a feature branch ). I modified the script to deploy a specific branch if optionally specified. So `./deploy.sh develop` would deploy from the develop branch.  Maybe this is useful to someone else in the class.

<https://github.com/gregorycoleman/p3/blob/master/bash/deploy.sh>

**Comment by nekoCC01** [comment]
Hello,
I tested it in the foobooks app with a small change to the welcome view.
(Added & committed, then run "git pd")
Everything worked perfectly well.

Here the ouput of the terminal:
```
/Applications/MAMP/htdocs/HES Courses/Dynamic Web Applications/foobooks (master)  $ git pd
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 446 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:nekoCC01/foobooks.git
   d930b4b..09f6e7f  master -> master
Detected location: Local
--------------------------------------
Git status on server for /var/www/html/foobooks:
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
--------------------------------------
Do you want to continue with deployment? (y/n)
y
Detected location: Server - Running deployment.
--------------------------------------
git pull origin master:
From github.com:nekoCC01/foobooks
 * branch            master     -> FETCH_HEAD
Updating d930b4b..09f6e7f
Fast-forward
   d930b4b..09f6e7f  master     -> origin/master
 resources/views/welcome.blade.php | 1 +
 1 file changed, 1 insertion(+)
--------------------------------------
composer install:
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Package manifest generated successfully.
```

**Comment by susanBuck** [comment]
Thanks for testing @gregorycoleman & @nekoCC01.

@gregorycoleman Useful mod!
If you want to customize for multiple branches, you may also want to replace `master` with a parameter (`$1`) in the git alias:

```
git config alias.pd '!git push origin $1 && bash/deploy.sh'
```

This way you can specify the branch to push, e.g.:

```bash
$ git pd development
```

**Comment by dmbartles** [comment]
Is there a way to change the comment in the commit command?

**Comment by susanjiang03** [comment]
If you have not push yet. you can do  
git commit --amend

**Comment by sheetaldalvi** [comment]
I used following statements in my shell script for comments
echo "Please insert comment to add for this commit :";
read comment
eval "git commit -m'$comment'"

**Comment by zeguy** [comment]
Ran into 2 issues on windows. First one when I tried to commit after adding the file I just got:
`error: pathspec 'deploy' did not match any file(s) known to git. `
`error: pathspec 'script'' did not match any file(s) known to git.`

Solved it by deleting and recreating the folder/file a couple times.

Then the commad:
`$ git config alias.pd '!git push origin master && bash/deploy.sh'`

Did nothing on my end. Had to manually edit the file like you suggested afterwards.

**Comment by dlabelle101** [comment]
on windows systems you have to use double quotes

git config alias.pd "git push origin master && bash/deploy.sh"

**Comment by susanBuck** [comment]
Thanks @ze and @dlabelle101 for noting the quotation issue.

I've updated the instructions so that examples of git commits with messages use double quotes - this way it will work universally on Mac/Windows.

And to simplify the quote issue for setting the alias, I've updated the instructions so now the alias is added by editing `.git/config` instead of using the `git alias` command. 

__Other updates of note:__
+ Amended `deploy.sh` so that it includes the `--no-dev` flag when running `composer install` (as was shown in today's Week 7 lectures).
+ Amended `deploy.sh` so it no longer uses the `dump` function to make text bold - in testing things on Windows I discovered the bold does not actually work and instead outputs jibberish characters. :(

If you tested this script before today, you should update your `deploy.sh` to reflect these changes.

[Quick link to the latest version of `deploy.sh`...](https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/999_Extras/deploy.sh)

**Comment by helhaggaz** [comment]
The new version of deploy.sh worked fine on windows.

**Comment by susanBuck** [comment]
I wanted to share an alternative deploy script created by one of your classmates (@sheetaldalvi). I find it interesting to read different scripts to see individual developer's preferred flow. 

Note how this version includes the stage/commit step, which may be desirable especially in this course where we typically want to stage everything. I omitted this step from my script because I often want to "cherry pick" which files get staged. Neither option is right/wrong, just depends on how you want to set it up.

```
#!/bin/sh

#---------------------------------------------------------------

# Synopsis      : Deployment script for Laravel project. 
#
# Instructions	: Store this script in htdocs on local machine. 
#               To run the script, simply go to the specific
#               project directory and run shell script
#               using command "../deploy.sh" Before using the
#               script change user and prodServerIP as 
#               appropriate.
#
# Author        : Sheetal Dalvi
#
# Semester      : Fall 2017
#
#----------------------------------------------------------------

# Local server git repository update 

echo "Welcome to the deployment script!";
echo "Your current dir is : " $PWD;
echo "Checking the repository status";
git status $PWD
echo "Adding all files to repository";
git add --all
echo "Please insert comment to add for this commit :";
read comment
echo " You entered :" $comment;
echo "Do you want to continue (y)/edit the comment(e) or quit(q)";
read answer
case $answer in
    y) echo "Let's continue with the deployment";
        ;;
    e) echo "Enter the new comment";
       read comment
        ;;
    *) echo "Sorry to see you go :(";
       exit
       ;;
esac       
        
echo "Comment to commit: " $comment;
echo "Commiting the changes to repository";
eval "git commit -m'$comment'"
echo "Pushing changes to Master repository";
git push origin master
echo "Enter Production server Project diretory : "
read proddir
echo $proddir;
# Production server deployment
ssh user@prodServerIP  ARG1=$proddir 'bash -s'<< 'ENDSSH'
echo "Deploying changes to Directory : " $ARG1;
cd /var/www/html/$ARG1
ls -ltr
echo "Current Dir is : " $PWD
git pull origin master
composer install --no-dev
ENDSSH
```
