### ISSUE TITLE
Route uri parameters

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#77]
While playing with the route parameters, I noticed that the variables used in the string URI need not be the same name as in the Closure function
For example, this works:
```
Route::get('/example/{varA}/{varB}',function ($parmA,$parmB) {
  return 'You are searching for '.$parmA.' and '.$parmB;
});
```
![image](https://user-images.githubusercontent.com/25366909/31415465-a9ebed9e-adf1-11e7-8309-416d993df315.png)

Here varA and varB uri values are passed to the function parameters $parmA and $parmB.
The values are therefore passed in the order of position and names don't have to match.

Same is true if controller method is used instead of closure function.

Thanks,
-Sri

**Comment by luke777gu** [comment]
This is a quite interesting finding and might save some time for naming the long variables.

**Comment by dukesnuz** [comment]
Very good to know.

**Comment by ysrinu** [comment]
Different names makes more sense when calling controller methods instead of closures, since controller code can be written by a developer other than the one writing the router string uri.

I just came across this:
https://laravel.com/docs/5.4/routing#route-parameters

> Route parameters are injected into route callbacks / controllers based on their order - the names of the callback / controller arguments do not matter

**Comment by gabrielsanna** [comment]
In situations like this—is it best practice to name the two variables the same thing, to make it clear that the value for one is injected into the other, or does it make more sense to name them two different things, so it's clear that they're actually two different variables?

**Comment by stbenjam** [comment]
@gabrielsanna If you're writing all the code it seems to me it makes more sense to have the same name so it's clear what's what.

**Comment by ysrinu** [comment]
Agree with @gabrielsanna 
The variables should not be named different just because they can be.
One business scenario where they can be different is when the controller method is written to serve more than one string uri case. Here the controller method parameters are named according to its logic. The string uri parameters should be named based the meaning from uri perspective (not GET variable names).

```
SearchController method 
public function search($keyword1, $keyword2) { ...};
```

```
Route::get('/Book/{topic}/{sub_topic}','SearchController@search');
Route::get('/People/{last_name}/{first_name});
Route::get('/Country/{state}/{search});
```
