### ISSUE TITLE
Why PHP 6 was not released?

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#79]
**Interesting articles on why PHP 6 version number was skipped :**

PHP RFC: Name of Next Release of PHP
https://wiki.php.net/rfc/php6#strong_reasons_of_why_we_actually_should_skip_version_6_into_7

What happened to PHP 6? :: PHP Roundtable (scroll to the bottom of the video)
https://www.phproundtable.com/episode/what-happened-to-php-6

The Good, the Bad, and the Ugly: What Happened to Unicode and PHP 6 (slideshow)
https://www.slideshare.net/andreizm/the-good-the-bad-and-the-ugly-what-happened-to-unicode-and-php-6

PHP 6: The Missing Version Number
https://ma.ttias.be/php6-missing-version-number/

**Other interesting version skipping or failure :**

MariaDB 10.0 and MySQL 5.6
https://mariadb.org/mariadb-10-0-and-mysql-5-6/

Netscape Communicator 5.0 (canceled)
https://en.wikipedia.org/wiki/Netscape_(web_browser)#Netscape_Communicator_5.0_.28canceled.29
https://en.wikipedia.org/wiki/Netscape_6

Symantec version 13 skipped (Superstition?)
https://www.symantec.com/connect/forums/next-version-dlp-dlp-14-beta

Why in The World Would Anyone Use Perl 6?
http://blogs.perl.org/users/zoffix_znet/2016/01/why-in-the-world-would-anyone-use-perl-6.html

Perl 5 and Perl 6 are mortal enemies
http://www.dagolden.com/index.php/2589/perl-5-and-perl-6-are-mortal-enemies/

MySQL 6 not released
https://en.wikipedia.org/wiki/MySQL#Release_history

**Comment by kunista** [comment]
Interesting information. I would add Windows 9 to this list:-)

**Comment by ysrinu** [comment]
I thought about Windows 9 and Samsung Galaxy Note 6. They both were skipped not because of failure. It was more to announce that they are making a 'Big Step'.
Windows wanted the next version to be the last, so they choose '10' instead of '9' and also to mean it's much bigger than '9'. 
Samsung skipped Galaxy Note 6 to indicate a big leap in technology. We all know the 'Note 7 fire mishap'!

**Comment by susanBuck** [comment]
I never realized version skipping was such a common thing! : )

**Comment by gnodar01** [comment]
ECMAScript (standard for JavasScript) version 4 was also abandoned. If it wasn't we would've gotten a lot of the most recent features in JavaScript years ago.
[https://en.wikipedia.org/wiki/ECMAScript#4th_Edition_.28abandoned.29](https://en.wikipedia.org/wiki/ECMAScript#4th_Edition_.28abandoned.29)

**Comment by ysrinu** [comment]
IPv5 (primarily knows as Internet Stream Protocol) was never released
https://en.wikipedia.org/wiki/Internet_Stream_Protocol
