### ISSUE TITLE
HTTP ERROR 500 Problem when Deploying to the Digital Ocean Live Server

### ISSUE THREAD

**Issue by z14165899** [susanBuck/dwa15-fall2017#80]
Hello Everyone: 
                        After I changed some code in the files locally in my computer to meet all requirements of the Progress Log, I changed all the code in corresponding files by copying and pasting the new code into each file in Github repository. Therefore, I did not use "git push origin master" command to push all the local files into the github, but I changed all the file in Github repository manually instead. After I SSH into my live server in digital ocean and clone everything from Github into digital ocean server, both the foobooks page and p3 page show me the HTTP ERROR 500 which I do not know how to solve. 
                        I then want to use  CMD to push all changes to github from my computer using "git push origin master" command, but it does not allow me to do that and gave me an error which is the following:

 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:z14165899/foobooks.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

                        I currently do not know how to solve this problem, so I want to set up the FTP connection with the DigitalOcean server using FileZilla, so that I can upload all my local files through FileZilla. I used my DigitalOcean Ip address as the host name, root as the username, DigitalOcean password or blank (I tried both) as the password, and 22 as the port. However, FileZilla also gave me an error message which is "Disconnected: No supported authentication methods available (server sent: publickey)". As a result, I am now stucking on how to make my live server display normal message and get rid of the HTTP ERROR 500 message. 
                         Is there anyone can tell me how to connect the DigitalOcean server with FileZilla? I think that I may miss some steps about the SSH keys since we set them up before. Also, Can I delete my entire foobooks and p3 folders and recreate them in Github? Anyone who can tell me the solution of these problem is appreciated. 
                         Thank you for your help.

**Comment by SridharSubramaniam** [comment]
Can you paste the error you are getting in digital ocean when you are trying to clone?

The second error is expected as your repo is ahead of your local changes, it doesn't allow you to push again until you merge your local changes.  Before we solve that, it would be good to know the error you were getting in digital ocean so we can solve that first!

**Comment by z14165899** [comment]
Hello Sri:
             Thank you very much for replying. Sorry for this interruption, but if you do not mind, could you please join this online meeting so that I can share my screen with you? Thank you so much.
              Here is the link: https://zoom.us/j/445732633



Best Regards,


Chen Zhao

**Comment by SridharSubramaniam** [comment]
Chen, So the issue you were showing me has nothing related to how you transport the code. It's a runtime error on your code and would need to debug that.

**Comment by ysrinu** [comment]
@z14165899 Can you turn on error reporting and debug from there log messages?
http://php.net/manual/en/function.error-reporting.php

**Comment by z14165899** [comment]
Hello Sri:
             Can you rejoin my chat room? I am some questions to ask you. Thank you. Here is the link: https://zoom.us/j/803535345

**Comment by ysrinu** [comment]
@z14165899 I work 8am-6pm Eastern Time at the client location and therefore can't join the chat room.
If I get lucky I can check once in a while the github during business hours. If you can post the error stack trace, someone of us could help debug the issue.

**Comment by z14165899** [comment]
I have solved the issue, thank you for your help.

**Comment by ysrinu** [comment]
@z14165899  nice!. Can you explain how you debugged and resolved the issue? It would be a learning for others. Thanks

**Comment by z14165899** [comment]
Hello Sri:
  The Problem is that I did not Build the vendor/ directory via composer install, Set permissions, and Set up .env file. These commands are shown in this lecture<https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/07_Deploy_to_DigitalOcean.md>. Once I delete the foobooks directory and rebuild a new one from Github. I forgot to do the above three steps mentioned. I hope that you do not have this issue. Thank you for your help though.


Best Regards,

Chen Zhao
