### ISSUE TITLE
psr-2 coding style and Laravel

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#81]
@susanBuck Do files created by Laravel 100% psr-2 compliant?

**Comment by susanBuck** [comment]
Googling *laravel psr-2* yields two indicators that yes, Laravel is psr-2 compliant.
+ Results #1 shows it was added in v5.1
+ Results #2 is from the [contribution guide](https://laravel.com/docs/5.5/contributions#coding-style) which states: *Laravel follows the PSR-2 coding standard and the PSR-4 autoloading standard.*
