### ISSUE TITLE
Same readings as last week?

### ISSUE THREAD

**Issue by gabrielsanna** [susanBuck/dwa15-fall2017#86]
I noticed that two of the Laravel docs we are assigned to read for week 7 are the same as last week: #basic-routing and #route-parameters. I just want to confirm that we should be reviewing these readings, or is there another doc in there that we're missing?

**Comment by susanBuck** [comment]
That was my mistake. #basic-routing and #route-parameters should not have been listed. I just updated the template to reflect this.
