### ISSUE TITLE
Discrepency in notes for cebe/markdown (lecture 3)

### ISSUE THREAD

**Issue by zeroender** [susanBuck/dwa15-fall2017#87]
In the third lecture this week and readings on packages, it is indicated that the prior package (toolbar) should be in required dev.  The example for manually adding the next package (markdown) has the toolbar package listed in required, rather than required dev:

https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/16_Package_examples.md#cebemarkdown

Looking at my composer.json, I do see laravel-debugbar under require-dev, rather than require, which I think is what is expected - wanted to confirm that is accurate.  Thanks!

**Comment by gregorycoleman** [comment]
cebe/markdown is a package that you would also like to run on your production site, so it should be in the required section. Things like debugbar are for development only, so those go in the required-dev section.

**Comment by peggyo** [comment]
I think @zeroender is just looking for clarification because the example of the composer.json file shown in the code snippet for installing cebemarkdown happens to show the debugbar package in the require section. Because the debugbar uses APP_DEBUG environment setting, too, it is unlikely to be a problem in this case. I guessed it was left over from a different example at some other time.

**Comment by gregorycoleman** [comment]
I was looking at the first composer.json section from the link @zeroender posted.  The second composer.json think is old and probably left over from a previous semester. The require section has ````"php": ">=5.6.4"```` , while we are using  ````"php": ">=7.0.0"```` for Laravel 5.5

As long as they  did ````$ composer require barryvdh/laravel-debugbar --dev```` , I think @zeroender is fine.

**Comment by susanBuck** [comment]
Yup, was a leftover from a previous semester that I missed updating. debugbar should be shown in `require-dev` (fixed now).

In previous semesters we did install debugbar in `require` and occasionally used it on production for debugging purposes. This semester I decided to move it over to `require-dev` as it's better suited there.

**Comment by zeroender** [comment]
Makes sense, thanks all!
