### ISSUE TITLE
Question About 'ls' (Command Line)

### ISSUE THREAD

**Issue by erictracy11492** [susanBuck/dwa15-fall2017#9]
I was unable to use the ‘ls’ command to list the contents of the Applications folder, like with the Desktop items. Is there a different way to list the contents? I was able to access, but it was using a different method. Forgive me, I’m fairly new to Command line.
<img width="700" alt="screen shot 2017-09-06 at 9 40 02 pm" src="https://user-images.githubusercontent.com/31494476/30141898-117afa74-934c-11e7-926e-0dcf4ed00a1d.png">

**Comment by gabrielsanna** [comment]
There are actually two Applications folders, which might be where you're getting confused: there's one at the root of your hard drive, which applies to all users on the Mac, and one in your user folder, which applies only to you and is usually empty. If you try:

`cd /Applications`

and then `ls` again, you should see your applications appear. On the other hand if you try:

`cd ~/Applications`

and `ls` here, nothing will appear, because this folder is empty. Note that the `~` character is a shortcut to your home directory—anything specific to your user account will appear in here (such as your Desktop).

**Comment by sheetaldalvi** [comment]
In case there are no files in the directory, ls command will not show any listing.
You can try ls -ltr command that would return the  following output
[
![lscommand](https://user-images.githubusercontent.com/31496325/30142890-13df0954-9351-11e7-8bd4-963fca6a1dfb.JPG)
](url)

Hope this helps!

**Comment by helhaggaz** [comment]
There are a lot of ways to use the list command `ls` to list the contents of a folder, all can be reviewed by using the help command: `ls --help`.
sample of that would be using `ls -a`, which will list the hidden files (name start with .) as you can see in the below screenshot.
![image](https://user-images.githubusercontent.com/26751023/30143354-5b056768-9353-11e7-8707-baeacbbe131b.png)

**Comment by davida26** [comment]
If you are using the Cmder package provided then you can simply use:

`ll` (the alias for the below command)

if you are on a mac (no alias set) you can use:

`ls -la`

same output :)

**Comment by gnodar01** [comment]
Just FYI you can also pass a path to `ls` as an argument, if you don't want to `cd` into the directory first.

`ls /absolute/path/to/directory`

**Comment by ysrinu** [comment]
Hi erictracy, when you say "I was unable to use the ‘ls’ command", do you mean you get any error message or just no results? Do you see any output like 'total 0'?
It's easy when you provide a screenshot of your commands and results.

I believe you were not able to change directory to the Desktop folder. Please note that on Windows, 'Desktop' and 'My Documents' are virtual folders and have a corresponding 'real' file structure too.
You should use the 'real' file path with shell commands.

![image](https://user-images.githubusercontent.com/25366909/30154707-b8c66f5c-9388-11e7-8d5f-4347f8d9ebf2.png)
![image](https://user-images.githubusercontent.com/25366909/30154733-cf2a1f32-9388-11e7-9eeb-416bb7beae9a.png)

**Comment by susanjiang03** [comment]
if you are using pc cmd, you should use 'dir' instead

**Comment by erictracy11492** [comment]
Thanks for the help everyone!
