### ISSUE TITLE
images directory?

### ISSUE THREAD

**Issue by milliezhou** [susanBuck/dwa15-fall2017#90]
If we wanted to add an image folder to our p3 directory (in htdocs), is there a certain place this should be?

**Comment by susanBuck** [comment]
Yes - you should put an image folder in `public/` since that's the directory which is your document root and accessible to the browser. 

(You'll note `public/` already has other client-side related folders like `js/` and `css/`

**Comment by milliezhou** [comment]
Got it. Thanks for confirming and the prompt response!

**Comment by dukesnuz** [comment]
This issue helped me fix my issue.  I was adding my css to the wrong folder - I was adding the css to the views folder.  Works fine now.

**Comment by zeroender** [comment]
Helped me as well with images.  Thanks for posting this!

**Comment by susanBuck** [comment]
FYI I also touch upon this in this week's (8) lecture videos (in case there's any confusion)
