### ISSUE TITLE
Is it better to have the styling in a CSS file or in the master layout?

### ISSUE THREAD

**Issue by dmbartles** [susanBuck/dwa15-fall2017#92]
Hey all,

I'm wondering if it is better to keep all of the styling in a separate CSS file or written in the master layout blade?

I like the idea of having it all in the master layout, so I can change the styles and whatnot in one place.

However, I'm unsure if this has any downsides...

Thanks for your help!

Matt

**Comment by mconstanti** [comment]
I think it's generally better to have it in a separate CSS file, in case you wanted to use the design scheme somewhere outside of the project. It's also a bit cleaner when you have separation of concerns (separating the structure of the site from the presentation).

**Comment by davida26** [comment]
I would definitely separate them to get into good practice. 

You can of course keep them within your view (as Laravel does on their welcome.blade page) but notice how they are very minimal. If you start adding more css then definitely separate it.

I have been getting familiar with Laravel Mix. Uses NPM to install all packages and then Webpack to build your sass files for example. This is very powerful to learn as in the future you may want to minify, organize and cleanup your css/js.

I can continue further here but the Laravel Docs are amazing at explaining everything. [Check them here](https://laravel.com/docs/5.5/mix)

**Comment by HeinrichTremblay** [comment]
You'll keep your css in its own file, but if you one specific css for a child blade view you can push a css import into the master layout head stack.

[](https://laravel.com/docs/5.5/blade#stacks.)

**Comment by luke777gu** [comment]
It is just like what you write for html file and keep your styles separate in css file. Also, css files should be in your public directory for Lavarel.

**Comment by dukesnuz** [comment]
Check out this [issue](https://github.com/susanBuck/dwa15-fall2017/issues/90)

**Comment by zeroender** [comment]
I'd also say seperate file (as pointed out in the above issue, you'll want to have it under the css directory in your public file).  Having at least one or multiple css files will allow you to take advantage of blade's inheritance (or as Heinrich pointed out, you can push it to a child view).

**Comment by natethegreat418** [comment]
As others have said, it definitely preferable to have your css files separated out from your HTML entirely. It makes your code more readable, adheres to the notice of "separation of concerns" and also gives you flexibility to reuse the styles across the project by simply calling the external css file.

If you have questions about how to call a style sheet from within a blade using Laravel then there is a great explanation available here: https://stackoverflow.com/questions/13433683/using-css-in-laravel-views.

**Comment by SridharSubramaniam** [comment]
Also not to forget the advantage of browser caching & other server-side caching benefits by leveraging a separate file for static resources like css & js. 

The layouts are dynamic in nature as data might change - so not a candidate for caching. but static resources like CSS & js would be cached as they don't have to be regenerated every time a request made to the server.

**Comment by ysrinu** [comment]
Regarding browser caching, note that as part of development, as you frequently make changes to css & js, you may want to clear your cache or run browser incognito mode so you can see the latest changes.
Otherwise the 'caching' meant as 'pro' for enduser can be a 'con' for the developer itself!

**Comment by SridharSubramaniam** [comment]
Good point @ysrinu !

One way to burst cache from a dev side is using some sort of url parameter for versioning..

e.g /bootstrap.css?v=1

If you change the css, you can bump up the version in master layout (benefit of referring the CSS in master layout) as bootstrap.css?v=2 . This will burst the browser cache and forces the CSS to be reloaded until you bump up version again.

**Comment by mfs780** [comment]
Generally the master layout could link to a global styling the is employed across the entire application such as input styling or button styling. The child views should add their own css for view specific styling.

**Comment by asmatmuradi** [comment]
I'm not sure if the location of the css file makes any difference. I stored my css file in public/css/.

**Comment by dmbartles** [comment]
Thanks everyone, the clear consensus is to have it in a separate file. Issue closed!
