### ISSUE TITLE
Q7 in the progress log seems to be incomplete

### ISSUE THREAD

**Issue by helhaggaz** [susanBuck/dwa15-fall2017#93]
The questions number 7 and 8 on the progress log seems to be one question and the numbering is missleading:

```
Q7) Consider the following code from a Blade child view:

@extends('layouts.master')

@section('title')
    Welcome!
@endsection

Q8) What statement would you use in a layout view to render the title section from this child view?
( ) @yield('title') 
( ) <?php echo $child['title']; ?> 
( ) @yield('index') 
( ) <?php yield $title; ?> 
 

```

**Comment by susanBuck** [comment]
Ignore the numbers, that is a mistake. The rest of the question is fine though.

(Moving forward please email me directly for questions/clarifications regarding the quick check portion of the progress log. This post has no revealing info but I don't want to send a message that it's ok to post about those questions here.)
