### ISSUE TITLE
p3 view input form

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#95]
The foobooks example shows view to display value passed as variable ($title).
I have two views, one for input form and the other output.
Does input form fields need to be passed as variables from the controller (these fields are not part of url, just from the controller). The issue I find here is that the variables are not set because input form fields are empty when rendering.
Or for this week project can we ignore input form fields?

**Comment by susanBuck** [comment]
@ysrinu Are you asking if your form inputs need to retain values (similarly to how we saw in Project 2) ? If so, yes.

If you're asking something else, can you provide some more specific context? 
You're free to post your repository URL so we can look at the code, and then you can explain what you're trying to accomplish.

**Comment by ysrinu** [comment]
@susanBuck 
by "If so, yes." should I interpret that we can ignore input form fields?

I am changing my code so the output is different than input form. The output form should display values from input form. Since we haven't covered how to 'grab' and pass values by the Controller, is it okay if my output form doesn't show any of the input form fields (or hardcoded with dummy values)?

In other words, if the Controller can only pass values (to the view) that it grabs from the Route, can we ignore processing/passing all form fields?

My changes in localhost are not final yet and hence not published to digital ocean.

**Comment by TheLivingNick** [comment]
I think she says in the final lecture video that we don't have to worry about passed info from forms yet as that will be covered next week; hardcodeded info should be fine for now.

**Comment by susanBuck** [comment]
In Week 7, no you don't have to worry about processing the forms yet. You simply create the views and the forms. 

In Week 8's material (released this evening), we talk about processing the forms, dealing with the form data, etc. 

(In my original reading of your question I thought you were referring the the final expectations of the project, not what is expected specifically in Week 7. Apologies for that misinterpretation!)

**Comment by ysrinu** [comment]
@TheLivingNick @susanBuck Thanks for the clarification :-)
