### ISSUE TITLE
Cmder prompt with "!"

### ISSUE THREAD

**Issue by ruthnphillips** [susanBuck/dwa15-fall2017#97]
I just switched from MAC to Windows (don't ask). I noticed after executing `composer update`, the Cmder prompt displays **Master in red with !** 

Should I be concerned?

![image](https://user-images.githubusercontent.com/16987911/31784375-723c99cc-b4cf-11e7-83fd-e4c6f581c77b.png)

**Comment by susanBuck** [comment]
Nope - This is output with info about the repo - you'll see it when in a directory that is a git repo.

The master is indicating what branch you're on.
The exclamation point indicates there are changes in the repo.

**Comment by ruthnphillips** [comment]
Gracias!
